from __future__ import annotations

from collections import Counter
from dataclasses import asdict, dataclass
from typing import Any, Literal


TARGET_CONTINUOUS_HOURS = 24
TARGET_MEDIUM_LARGE_UPDATE_COUNT = 100

UpdateSize = Literal["medium", "large"]
UpdateStatus = Literal["shipped", "planned"]


@dataclass(frozen=True)
class LedgerEntry:
    id: str
    title: str
    category: str
    size: UpdateSize
    status: UpdateStatus
    impact: str
    evidence_paths: tuple[str, ...]
    release_gate_links: tuple[str, ...]
    user_need_ids: tuple[str, ...]
    commit_hint: str | None = None

    def to_api(self) -> dict[str, Any]:
        data = asdict(self)
        data["evidence_paths"] = list(self.evidence_paths)
        data["release_gate_links"] = list(self.release_gate_links)
        data["user_need_ids"] = list(self.user_need_ids)
        return data


class ContinuousUpdateLedgerService:
    """Track long-running maintenance progress without claiming completion early."""

    def build_ledger(self) -> dict[str, Any]:
        entries = self._entries()
        completed = [entry for entry in entries if entry.status == "shipped"]
        planned = [entry for entry in entries if entry.status == "planned"]
        category_counts = Counter(entry.category for entry in completed)
        size_counts = Counter(entry.size for entry in completed)
        completed_count = len(completed)
        remaining_count = max(0, TARGET_MEDIUM_LARGE_UPDATE_COUNT - completed_count)

        return {
            "status": "in_progress",
            "goal": {
                "target_continuous_hours": TARGET_CONTINUOUS_HOURS,
                "target_medium_large_update_count": TARGET_MEDIUM_LARGE_UPDATE_COUNT,
                "completion_policy": [
                    "Do not mark the goal complete until both the 24-hour evidence window and 100+ medium/large shipped updates are reviewable.",
                    "Count only repository-backed updates with code, tests, docs, or reviewer-facing evidence.",
                    "Keep laptop-safe quick suites separate from heavier benchmark or public corpus work.",
                ],
            },
            "summary": {
                "completed_medium_large_update_count": completed_count,
                "remaining_medium_large_update_count": remaining_count,
                "planned_update_count": len(planned),
                "large_update_count": size_counts.get("large", 0),
                "medium_update_count": size_counts.get("medium", 0),
                "category_counts": dict(sorted(category_counts.items())),
                "continuous_hours_verified": 0,
                "continuous_hours_remaining": TARGET_CONTINUOUS_HOURS,
                "completion_ready": False,
            },
            "completed_updates": [entry.to_api() for entry in completed],
            "next_update_queue": [entry.to_api() for entry in planned[:12]],
            "twenty_four_hour_evidence_requirements": [
                "Record timestamped commits or CI runs across the full 24-hour window.",
                "Keep each update reviewable through a code path, test, doc, endpoint, or UI surface.",
                "Do not treat local-only benchmark attempts as shipped updates unless results are normalized and stored safely.",
            ],
            "hundred_update_evidence_requirements": [
                "Group updates by model operations, legal benchmark coverage, frontend visibility, maintenance evidence, and safety controls.",
                "Keep small fixture tests serial and cheap-first so low-resource machines can validate the work.",
                "Use release-readiness and OSS-maintenance evidence endpoints as the reviewer-facing index.",
            ],
            "low_resource_test_policy": {
                "default_fixture_limit": 3,
                "max_parallel_requests": 1,
                "network_access": "disabled_by_default",
                "model_call_policy": "manual_serial_only",
                "recommended_endpoint": "/api/v1/maintenance/legal-review-benchmark/quick-suite",
            },
            "release_guardrails": [
                "The ledger is optional release evidence; it must not unblock a release by itself.",
                "Secret values, account credentials, raw client documents, and raw gateway responses must stay out of git.",
                "Public benchmark sources stay metadata-only until license, attribution, and privacy review pass.",
            ],
            "validation_commands": [
                "python -m pytest tests/test_continuous_update_ledger.py -q",
                "python -m pytest tests/test_legal_fixture_quick_suite.py tests/test_legal_review_benchmark.py -q",
            ],
        }

    def _entries(self) -> list[LedgerEntry]:
        return [
            LedgerEntry(
                id="model-gateway-probe-evaluation",
                title="Sanitized model gateway probe evaluation",
                category="model_ops",
                size="large",
                status="shipped",
                impact="Reviews OpenAI-compatible gateway model and chat probes without storing keys or raw secrets.",
                evidence_paths=(
                    "app/backend/services/model_gateway_probe_evaluation.py",
                    "app/backend/tests/test_model_gateway_probe_evaluation.py",
                    "docs/MODEL_GATEWAY_PROBE_EVALUATION.md",
                ),
                release_gate_links=("model-gateway-probe-evaluation", "model-ops-readiness"),
                user_need_ids=("low-cost-routing", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="model-gateway-probe-ui",
                title="Model gateway probe evidence in operations UI",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Surfaces probe recommendations and sanitized defaults in the model operations page.",
                evidence_paths=(
                    "app/frontend/src/lib/modelOpsApi.ts",
                    "app/frontend/src/pages/ModelOpsPage.tsx",
                ),
                release_gate_links=("frontend-typecheck", "frontend-build"),
                user_need_ids=("low-cost-routing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="model-gateway-health-plan",
                title="Gateway health planning before live requests",
                category="model_ops",
                size="large",
                status="shipped",
                impact="Documents cheap JSON probes, base URL checks, and manual health gates before real model calls.",
                evidence_paths=(
                    "app/backend/services/model_gateway_health_plan.py",
                    "app/backend/tests/test_model_gateway_health_plan.py",
                    "docs/MODEL_GATEWAY_HEALTH_PLAN.md",
                ),
                release_gate_links=("model-gateway-health-plan", "model-ops-readiness"),
                user_need_ids=("safe-ai-ops", "low-cost-routing"),
            ),
            LedgerEntry(
                id="legal-research-backlog",
                title="Research-backed legal AI backlog",
                category="user_research",
                size="large",
                status="shipped",
                impact="Maps LegalBench, FrugalGPT, RAGAS, CRAG, and CUAD signals into concrete engineering tasks.",
                evidence_paths=(
                    "app/backend/services/legal_research_backlog.py",
                    "app/backend/tests/test_legal_research_backlog.py",
                    "docs/LEGAL_RESEARCH_BACKLOG.md",
                ),
                release_gate_links=("legal-review-benchmark", "oss-maintenance-evidence"),
                user_need_ids=("grounded-legal-output", "low-cost-routing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-external-research-digest",
                title="External legal AI research digest",
                category="user_research",
                size="large",
                status="shipped",
                impact="Maps LegalBench, CUAD, RAGAS, CRAG, and FrugalGPT signals into local legal benchmark, RAG, and cheap-first routing work.",
                evidence_paths=(
                    "app/backend/services/legal_external_research_digest.py",
                    "app/backend/tests/test_legal_external_research_digest.py",
                    "docs/LEGAL_EXTERNAL_RESEARCH_DIGEST.md",
                ),
                release_gate_links=("legal-review-benchmark", "oss-maintenance-evidence"),
                user_need_ids=("grounded-legal-output", "low-cost-routing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-research-backlog-ui",
                title="Legal research backlog reviewer panel",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Shows research backlog priorities and evidence paths on the maintenance page.",
                evidence_paths=(
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                ),
                release_gate_links=("frontend-typecheck", "frontend-build"),
                user_need_ids=("reviewer-visibility", "grounded-legal-output"),
            ),
            LedgerEntry(
                id="legal-public-benchmark-sampler",
                title="Resource-capped public benchmark sampler",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Keeps public benchmark work as metadata until license and attribution review are complete.",
                evidence_paths=(
                    "app/backend/services/legal_public_benchmark_sampler.py",
                    "app/backend/tests/test_legal_public_benchmark_sampler.py",
                    "docs/LEGAL_PUBLIC_BENCHMARK_SAMPLER.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("grounded-legal-output", "low-resource-testing"),
            ),
            LedgerEntry(
                id="legal-fixture-quick-suite",
                title="Laptop-safe legal fixture quick suite",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Selects a tiny serial fixture subset for low-resource local testing.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_quick_suite.py",
                    "app/backend/tests/test_legal_fixture_quick_suite.py",
                    "docs/LEGAL_FIXTURE_QUICK_SUITE.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("low-resource-testing", "low-cost-routing"),
            ),
            LedgerEntry(
                id="legal-fixture-model-matrix",
                title="Fixture-level Gemini and NewAPI model matrix",
                category="model_ops",
                size="medium",
                status="shipped",
                impact="Assigns cheap-first, fallback, and premium-exception candidates per legal fixture.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_model_matrix.py",
                    "app/backend/tests/test_legal_fixture_model_matrix.py",
                    "docs/LEGAL_FIXTURE_MODEL_MATRIX.md",
                ),
                release_gate_links=("legal-review-benchmark", "model-fallback-chains"),
                user_need_ids=("low-cost-routing", "low-resource-testing"),
            ),
            LedgerEntry(
                id="legal-fixture-prompt-pack",
                title="Cheap-first legal fixture prompt pack",
                category="benchmark",
                size="medium",
                status="shipped",
                impact="Builds small legal document prompts with observation targets for manual gateway checks.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_prompt_pack.py",
                    "app/backend/tests/test_legal_fixture_prompt_pack.py",
                    "docs/LEGAL_FIXTURE_PROMPT_PACK.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("grounded-legal-output", "low-cost-routing"),
            ),
            LedgerEntry(
                id="legal-fixture-gateway-manifest",
                title="Safe legal fixture gateway manifests",
                category="safety",
                size="medium",
                status="shipped",
                impact="Generates OpenAI-compatible request manifests with placeholders instead of real credentials.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_gateway_manifest.py",
                    "app/backend/tests/test_legal_fixture_gateway_manifest.py",
                    "docs/LEGAL_FIXTURE_GATEWAY_MANIFEST.md",
                ),
                release_gate_links=("secret-scan", "legal-review-benchmark"),
                user_need_ids=("safe-ai-ops", "low-resource-testing"),
            ),
            LedgerEntry(
                id="legal-fixture-run-plan",
                title="Serial cheap-first fixture run plan",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Converts fixture manifests into one-at-a-time local batches with conditional escalation.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_run_plan.py",
                    "app/backend/tests/test_legal_fixture_run_plan.py",
                    "docs/LEGAL_FIXTURE_RUN_PLAN.md",
                ),
                release_gate_links=("legal-review-benchmark", "model-escalation-policy"),
                user_need_ids=("low-resource-testing", "low-cost-routing"),
            ),
            LedgerEntry(
                id="legal-fixture-local-run-package",
                title="One-at-a-time local fixture run package",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Bundles request JSON, PowerShell and curl templates, observation slots, and report scaffolding.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_local_run_package.py",
                    "app/backend/tests/test_legal_fixture_local_run_package.py",
                    "docs/LEGAL_FIXTURE_LOCAL_RUN_PACKAGE.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("low-resource-testing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-fixture-response-normalizer",
                title="Local fixture response normalizer",
                category="safety",
                size="medium",
                status="shipped",
                impact="Redacts secret-like values and normalizes local gateway outputs into fixture observations.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_response_normalizer.py",
                    "app/backend/tests/test_legal_fixture_response_normalizer.py",
                    "docs/LEGAL_FIXTURE_RESPONSE_NORMALIZER.md",
                ),
                release_gate_links=("secret-scan", "legal-review-benchmark"),
                user_need_ids=("safe-ai-ops", "low-resource-testing"),
            ),
            LedgerEntry(
                id="legal-fixture-local-run-review",
                title="One-step local fixture run review",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Normalizes local responses, scores smoke coverage, builds run reports, and returns evidence bundles.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_local_run_review.py",
                    "app/backend/tests/test_legal_fixture_local_run_review.py",
                    "docs/LEGAL_FIXTURE_LOCAL_RUN_REVIEW.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("low-resource-testing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-fixture-run-report",
                title="Cheap-first fixture run report",
                category="release_evidence",
                size="medium",
                status="shipped",
                impact="Turns fixture observations into release decisions and fixture-scoped escalation actions.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_run_report.py",
                    "app/backend/tests/test_legal_fixture_run_report.py",
                    "docs/LEGAL_FIXTURE_RUN_REPORT.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("reviewer-visibility", "low-cost-routing"),
            ),
            LedgerEntry(
                id="legal-fixture-evidence-bundle",
                title="Legal fixture evidence bundle",
                category="release_evidence",
                size="medium",
                status="shipped",
                impact="Archives component status, validation commands, release-safe claims, and cheap-first run evidence.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_evidence_bundle.py",
                    "app/backend/tests/test_legal_fixture_evidence_bundle.py",
                    "docs/LEGAL_FIXTURE_EVIDENCE_BUNDLE.md",
                ),
                release_gate_links=("legal-review-benchmark", "oss-maintenance-evidence"),
                user_need_ids=("reviewer-visibility", "grounded-legal-output"),
            ),
            LedgerEntry(
                id="user-needs-radar",
                title="User needs radar",
                category="user_research",
                size="medium",
                status="shipped",
                impact="Ranks target legal-review needs and links them to release gates and evidence paths.",
                evidence_paths=(
                    "app/backend/services/user_needs_radar.py",
                    "app/backend/tests/test_user_needs_radar.py",
                    "docs/USER_NEEDS_RADAR.md",
                ),
                release_gate_links=("user-needs-radar", "oss-maintenance-evidence"),
                user_need_ids=("reviewer-visibility", "grounded-legal-output", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="feedback-roadmap-alignment",
                title="Feedback-to-roadmap alignment",
                category="maintenance",
                size="medium",
                status="shipped",
                impact="Maps support feedback categories to user-need IDs and release gates.",
                evidence_paths=(
                    "app/backend/services/feedback_roadmap_alignment.py",
                    "app/backend/tests/test_feedback_roadmap_alignment.py",
                    "docs/FEEDBACK_ROADMAP_ALIGNMENT.md",
                ),
                release_gate_links=("feedback-roadmap-alignment", "oss-maintenance-evidence"),
                user_need_ids=("reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="product-feature-gap-radar",
                title="Product-wide feature gap radar",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Makes incomplete product modules explicit across case workbench, document generation, contract review, evidence, OCR, billing, team, feedback, model ops, legal knowledge, and safety.",
                evidence_paths=(
                    "app/backend/services/product_feature_gap_radar.py",
                    "app/backend/tests/test_product_feature_gap_radar.py",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                release_gate_links=("product-feature-gap-radar", "oss-maintenance-evidence"),
                user_need_ids=("reviewer-visibility", "product-readiness"),
            ),
            LedgerEntry(
                id="case-evidence-graph-contract",
                title="Case evidence graph contract",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Defines the fact-evidence-citation-risk graph contract and blocking gap flags before a full case workbench graph UI is built.",
                evidence_paths=(
                    "app/backend/services/case_evidence_graph.py",
                    "app/backend/tests/test_case_evidence_graph.py",
                    "docs/CASE_EVIDENCE_GRAPH.md",
                ),
                release_gate_links=("case-evidence-graph", "legal-rag-evaluation"),
                user_need_ids=("grounded-legal-output", "case-workbench"),
            ),
            LedgerEntry(
                id="case-intake-completeness",
                title="Case intake completeness checklist",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Blocks document generation when parties, venue, deadlines, claims, evidence, or risk disclosure fields are incomplete.",
                evidence_paths=(
                    "app/backend/services/case_intake_completeness.py",
                    "app/backend/tests/test_case_intake_completeness.py",
                    "docs/CASE_INTAKE_COMPLETENESS.md",
                ),
                release_gate_links=("case-intake-completeness", "case-evidence-graph"),
                user_need_ids=("case-workbench", "document-generation", "grounded-legal-output"),
            ),
            LedgerEntry(
                id="case-timeline-deadline-risk",
                title="Case timeline deadline risk",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Adds deterministic event, deadline, urgent-blocker, and missing-fact risk metadata for the case workspace.",
                evidence_paths=(
                    "app/backend/services/case_timeline_deadline_risk.py",
                    "app/backend/tests/test_case_timeline_deadline_risk.py",
                    "docs/CASE_TIMELINE_DEADLINE_RISK.md",
                ),
                release_gate_links=("case-timeline-deadline-risk", "case-intake-completeness"),
                user_need_ids=("case-workbench", "reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="case-task-notification-policy",
                title="Case task notification policy",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Defines deterministic task reminders, owner blockers, urgent escalations, client material reminders, and lawyer review notifications.",
                evidence_paths=(
                    "app/backend/services/case_task_notification_policy.py",
                    "app/backend/tests/test_case_task_notification_policy.py",
                    "docs/CASE_TASK_NOTIFICATION_POLICY.md",
                ),
                release_gate_links=("case-task-notification-policy", "case-timeline-deadline-risk"),
                user_need_ids=("case-workbench", "reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="case-team-access-policy",
                title="Case team access policy",
                category="safety",
                size="medium",
                status="shipped",
                impact="Defines least-privilege owner, lawyer, paralegal, reviewer, and client roles with audit-required sensitive operations.",
                evidence_paths=(
                    "app/backend/services/case_team_access_policy.py",
                    "app/backend/tests/test_case_team_access_policy.py",
                    "docs/CASE_TEAM_ACCESS_POLICY.md",
                ),
                release_gate_links=("case-team-access-policy", "product-feature-gap-radar"),
                user_need_ids=("case-workbench", "reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="matter-audit-retention-policy",
                title="Matter audit retention policy",
                category="safety",
                size="medium",
                status="shipped",
                impact="Defines privacy-minimized audit events, forbidden fields, retention buckets, and release blockers for matter workflows.",
                evidence_paths=(
                    "app/backend/services/matter_audit_retention_policy.py",
                    "app/backend/tests/test_matter_audit_retention_policy.py",
                    "docs/MATTER_AUDIT_RETENTION_POLICY.md",
                ),
                release_gate_links=("matter-audit-retention-policy", "case-team-access-policy"),
                user_need_ids=("case-workbench", "reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="client-delivery-risk-checklist",
                title="Client delivery risk checklist",
                category="safety",
                size="medium",
                status="shipped",
                impact="Adds delivery blockers for citation evidence, lawyer review, scope assumptions, AI limitation notices, and client-readable risk language.",
                evidence_paths=(
                    "app/backend/services/client_delivery_risk_checklist.py",
                    "app/backend/tests/test_client_delivery_risk_checklist.py",
                    "docs/CLIENT_DELIVERY_RISK_CHECKLIST.md",
                ),
                release_gate_links=("client-delivery-risk-checklist", "case-intake-completeness"),
                user_need_ids=("grounded-legal-output", "reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="lawyer-review-workflow-policy",
                title="Lawyer review workflow policy",
                category="safety",
                size="medium",
                status="shipped",
                impact="Defines draft, lawyer review, approved, rejected, revise-required, and client-deliverable state transitions.",
                evidence_paths=(
                    "app/backend/services/lawyer_review_workflow_policy.py",
                    "app/backend/tests/test_lawyer_review_workflow_policy.py",
                    "docs/LAWYER_REVIEW_WORKFLOW_POLICY.md",
                ),
                release_gate_links=("lawyer-review-workflow-policy", "client-delivery-risk-checklist"),
                user_need_ids=("reviewer-visibility", "safe-ai-ops", "document-generation"),
            ),
            LedgerEntry(
                id="evidence-exhibit-package-policy",
                title="Evidence exhibit package policy",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Defines exhibit numbering, proof purpose, source and page anchors, three-factor review, and export manifest requirements.",
                evidence_paths=(
                    "app/backend/services/evidence_exhibit_package_policy.py",
                    "app/backend/tests/test_evidence_exhibit_package_policy.py",
                    "docs/EVIDENCE_EXHIBIT_PACKAGE_POLICY.md",
                ),
                release_gate_links=("evidence-exhibit-package-policy", "case-evidence-graph"),
                user_need_ids=("case-workbench", "grounded-legal-output", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-document-template-matrix",
                title="Legal document template matrix",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Defines required fields, formatting requirements, blockers, lawyer-review gates, and export formats for six legal document types.",
                evidence_paths=(
                    "app/backend/services/legal_document_template_matrix.py",
                    "app/backend/tests/test_legal_document_template_matrix.py",
                    "docs/LEGAL_DOCUMENT_TEMPLATE_MATRIX.md",
                ),
                release_gate_links=("legal-document-template-matrix", "product-feature-gap-radar"),
                user_need_ids=("document-generation", "case-workbench", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-document-export-readiness",
                title="Legal document export readiness",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Blocks final export until template fields, blocker clearance, lawyer review, source support, redaction, version lock, and format support pass.",
                evidence_paths=(
                    "app/backend/services/legal_document_export_readiness.py",
                    "app/backend/tests/test_legal_document_export_readiness.py",
                    "docs/LEGAL_DOCUMENT_EXPORT_READINESS.md",
                ),
                release_gate_links=("legal-document-export-readiness", "legal-document-template-matrix"),
                user_need_ids=("document-generation", "grounded-legal-output", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="ocr-import-readiness-policy",
                title="OCR import readiness policy",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Defines uploaded, preflight, OCR-needed, OCR-failed, parsed, blocked, and manual-review states for scanned or low-text files.",
                evidence_paths=(
                    "app/backend/services/ocr_import_readiness_policy.py",
                    "app/backend/tests/test_ocr_import_readiness_policy.py",
                    "docs/OCR_IMPORT_READINESS_POLICY.md",
                ),
                release_gate_links=("ocr-import-readiness-policy", "product-feature-gap-radar"),
                user_need_ids=("document-intake", "case-workbench", "low-resource-testing"),
            ),
            LedgerEntry(
                id="billing-entitlement-gap-evidence",
                title="Billing entitlement gap evidence",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Adds deterministic payment activation and usage-plan guard evidence without integrating a live payment gateway.",
                evidence_paths=(
                    "app/backend/services/billing_entitlement_gap.py",
                    "app/backend/tests/test_billing_entitlement_gap.py",
                    "docs/BILLING_ENTITLEMENT_GAP.md",
                ),
                release_gate_links=("billing-entitlement-gap", "product-feature-gap-radar"),
                user_need_ids=("billing-entitlements", "product-readiness"),
            ),
            LedgerEntry(
                id="continuous-update-ledger-ui",
                title="Reviewer-facing continuous update ledger panel",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Expose the ledger on the maintenance dashboard with completed count, remaining count, and low-resource test policy.",
                evidence_paths=(
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                ),
                release_gate_links=("frontend-typecheck", "frontend-build"),
                user_need_ids=("reviewer-visibility",),
            ),
            LedgerEntry(
                id="cheap-first-result-archive",
                title="Cheap-first fixture result archive",
                category="release_evidence",
                size="large",
                status="shipped",
                impact="Store normalized fixture run summaries without raw client text or raw model output.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_result_archive.py",
                    "app/backend/tests/test_legal_fixture_result_archive.py",
                    "docs/LEGAL_FIXTURE_RESULT_ARCHIVE.md",
                ),
                release_gate_links=("legal-review-benchmark", "secret-scan"),
                user_need_ids=("low-resource-testing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="model-default-recommendation-snapshot",
                title="Gemini/NewAPI default recommendation snapshot",
                category="model_ops",
                size="medium",
                status="shipped",
                impact="Checks high-volume model defaults against stable lowest-tier Gemini recommendations and flags unknown gateway model names for catalog review.",
                evidence_paths=(
                    "app/backend/services/model_default_recommendation_snapshot.py",
                    "app/backend/tests/test_model_default_recommendation_snapshot.py",
                    "docs/MODEL_DEFAULT_RECOMMENDATION_SNAPSHOT.md",
                ),
                release_gate_links=("model-default-recommendation-snapshot", "model-default-optimization"),
                user_need_ids=("low-cost-routing", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="gemini-newapi-cheap-first-policy",
                title="Gemini/NewAPI cheap-first policy",
                category="model_ops",
                size="medium",
                status="shipped",
                impact="Documents supported Gemini families, NewAPI-compatible prefixes, forbidden premium defaults, and explicit-only handling for unknown Gemini-like models.",
                evidence_paths=(
                    "app/backend/services/gemini_newapi_cheap_first_policy.py",
                    "app/backend/tests/test_gemini_newapi_cheap_first_policy.py",
                    "docs/GEMINI_NEWAPI_CHEAP_FIRST_POLICY.md",
                ),
                release_gate_links=("gemini-newapi-cheap-first-policy", "model-default-recommendation-snapshot"),
                user_need_ids=("low-cost-routing", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="legal-document-benchmark-fixtures",
                title="Small legal document benchmark fixtures",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Adds deterministic Chinese legal-document snippets and local classification, extraction, deadline, and risk-label scoring without model calls.",
                evidence_paths=(
                    "app/backend/services/legal_document_benchmark_fixtures.py",
                    "app/backend/tests/test_legal_document_benchmark_fixtures.py",
                    "docs/LEGAL_DOCUMENT_BENCHMARK_FIXTURES.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("grounded-legal-output", "low-resource-testing"),
            ),
            LedgerEntry(
                id="matter-intake-readiness-policy",
                title="Matter intake readiness policy",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Evaluates matter-opening metadata for required fields, conflict screening, engagement materials, urgent deadlines, and lawyer-review gates.",
                evidence_paths=(
                    "app/backend/services/matter_intake_readiness_policy.py",
                    "app/backend/tests/test_matter_intake_readiness_policy.py",
                    "docs/MATTER_INTAKE_READINESS_POLICY.md",
                ),
                release_gate_links=("matter-intake-readiness-policy", "case-intake-completeness"),
                user_need_ids=("case-workbench", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="deadline-validation-policy",
                title="Deadline validation policy",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Adds deterministic date metadata checks for service, evidence, appeal, filing, limitation, and contract-performance deadlines.",
                evidence_paths=(
                    "app/backend/services/deadline_validation_policy.py",
                    "app/backend/tests/test_deadline_validation_policy.py",
                    "docs/DEADLINE_VALIDATION_POLICY.md",
                ),
                release_gate_links=("deadline-validation-policy", "case-timeline-deadline-risk"),
                user_need_ids=("case-workbench", "reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="client-delivery-transparency-policy",
                title="Client delivery transparency policy",
                category="safety",
                size="medium",
                status="shipped",
                impact="Blocks or warns on delivery metadata gaps for client confirmation, version diffs, risk notices, delivery records, and follow-up tasks.",
                evidence_paths=(
                    "app/backend/services/client_delivery_transparency_policy.py",
                    "app/backend/tests/test_client_delivery_transparency_policy.py",
                    "docs/CLIENT_DELIVERY_TRANSPARENCY_POLICY.md",
                ),
                release_gate_links=("client-delivery-transparency-policy", "client-delivery-risk-checklist"),
                user_need_ids=("reviewer-visibility", "safe-ai-ops", "document-generation"),
            ),
            LedgerEntry(
                id="gemini-price-refresh-monitor",
                title="Gemini and gateway price refresh monitor",
                category="model_ops",
                size="medium",
                status="shipped",
                impact="Flags local catalog, forecast, and observed gateway model drift when cheap-first assumptions no longer match price metadata.",
                evidence_paths=(
                    "app/backend/services/model_price_refresh_monitor.py",
                    "app/backend/tests/test_model_price_refresh_monitor.py",
                    "docs/MODEL_PRICE_REFRESH_MONITOR.md",
                ),
                release_gate_links=("model-price-refresh-monitor", "model-cost-forecast"),
                user_need_ids=("low-cost-routing",),
            ),
            LedgerEntry(
                id="small-legal-document-corpus-expansion",
                title="Small legal fixture corpus expansion",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Adds eight local synthetic Chinese legal-document scenarios across labor, lease, sales, service, lending, tort, and consumer workflows.",
                evidence_paths=(
                    "app/backend/services/small_legal_document_corpus_expansion.py",
                    "app/backend/tests/test_small_legal_document_corpus_expansion.py",
                    "docs/SMALL_LEGAL_DOCUMENT_CORPUS_EXPANSION.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("grounded-legal-output", "low-resource-testing"),
            ),
            LedgerEntry(
                id="legal-rag-failure-fixtures",
                title="Legal RAG failure fixtures",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Adds deterministic RAG failure fixtures for missing citations, stale law, jurisdiction mismatch, unsupported conclusions, hallucinated articles, and conflicting facts.",
                evidence_paths=(
                    "app/backend/services/legal_rag_failure_fixtures.py",
                    "app/backend/tests/test_legal_rag_failure_fixtures.py",
                    "docs/LEGAL_RAG_FAILURE_FIXTURES.md",
                ),
                release_gate_links=("legal-review-benchmark", "legal-rag-evaluation"),
                user_need_ids=("grounded-legal-output",),
            ),
            LedgerEntry(
                id="maintenance-dashboard-filtering",
                title="Maintenance dashboard filtering",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Adds category, status, and search filters that combine completed and queued ledger entries in the maintenance page.",
                evidence_paths=("app/frontend/src/pages/MaintenanceEvidencePage.tsx",),
                release_gate_links=("frontend-typecheck", "frontend-build"),
                user_need_ids=("reviewer-visibility",),
            ),
            LedgerEntry(
                id="model-cost-regression-snapshots",
                title="Model cost regression snapshots",
                category="model_ops",
                size="large",
                status="shipped",
                impact="Compares deterministic cheap-first monthly costs against premium-only baselines and drift thresholds for fast, classification, OCR, review, and PDF routes.",
                evidence_paths=(
                    "app/backend/services/model_cost_regression_snapshots.py",
                    "app/backend/tests/test_model_cost_regression_snapshots.py",
                    "docs/MODEL_COST_REGRESSION_SNAPSHOTS.md",
                ),
                release_gate_links=("model-cost-regression-snapshots", "model-cost-guardrails", "model-routing-replay"),
                user_need_ids=("low-cost-routing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="twenty-four-hour-heartbeat-evidence",
                title="24-hour heartbeat evidence export",
                category="maintenance",
                size="medium",
                status="shipped",
                impact="Defines a privacy-safe heartbeat evidence format for commit, test, push, and review events across a long maintenance window without claiming completion early.",
                evidence_paths=(
                    "app/backend/services/maintenance_heartbeat_evidence.py",
                    "app/backend/tests/test_maintenance_heartbeat_evidence.py",
                    "docs/MAINTENANCE_HEARTBEAT_EVIDENCE.md",
                ),
                release_gate_links=("maintenance-heartbeat-evidence", "oss-maintenance-evidence"),
                user_need_ids=("reviewer-visibility",),
            ),
            LedgerEntry(
                id="frontend-local-run-review-form",
                title="Frontend local run review form",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Lets maintainers paste already-redacted local fixture responses into the existing response normalizer flow.",
                evidence_paths=("app/frontend/src/pages/MaintenanceEvidencePage.tsx",),
                release_gate_links=("frontend-typecheck", "legal-review-benchmark"),
                user_need_ids=("low-resource-testing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="route-telemetry-persistence-plan",
                title="Route telemetry persistence plan",
                category="model_ops",
                size="large",
                status="shipped",
                impact="Defines sanitized route telemetry event schema, allowed and forbidden fields, retention policy, and sample-event validation before durable storage.",
                evidence_paths=(
                    "app/backend/services/route_telemetry_persistence_plan.py",
                    "app/backend/tests/test_route_telemetry_persistence_plan.py",
                    "docs/ROUTE_TELEMETRY_PERSISTENCE_PLAN.md",
                ),
                release_gate_links=("route-telemetry-persistence-plan", "model-route-telemetry", "secret-scan"),
                user_need_ids=("low-cost-routing", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="legal-source-freshness-policy",
                title="Legal source freshness and jurisdiction policy",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Adds deterministic metadata checks for jurisdiction, citation, effective date, and freshness before legal sources can support RAG answers.",
                evidence_paths=(
                    "app/backend/services/legal_source_freshness_policy.py",
                    "app/backend/tests/test_legal_source_freshness_policy.py",
                    "docs/LEGAL_SOURCE_FRESHNESS_POLICY.md",
                ),
                release_gate_links=("legal-source-freshness-policy", "legal-rag-evaluation", "legal-knowledge-audit"),
                user_need_ids=("grounded-legal-output", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="case-workbench-payload",
                title="Case workbench payload contract",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Assembles matter intake, deadline validation, timeline risk, task notifications, and evidence graph metadata into a deterministic dashboard payload.",
                evidence_paths=(
                    "app/backend/services/case_workbench_payload.py",
                    "app/backend/tests/test_case_workbench_payload.py",
                    "docs/CASE_WORKBENCH_PAYLOAD.md",
                ),
                release_gate_links=("case-workbench-payload", "case-evidence-graph", "matter-intake-readiness-policy"),
                user_need_ids=("case-workbench", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="document-delivery-package-manifest",
                title="Document delivery package manifest",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Adds metadata-only checks for documents, source support, missing facts, lawyer review, client notices, export formats, and version notes before delivery.",
                evidence_paths=(
                    "app/backend/services/document_delivery_package_manifest.py",
                    "app/backend/tests/test_document_delivery_package_manifest.py",
                    "docs/DOCUMENT_DELIVERY_PACKAGE_MANIFEST.md",
                ),
                release_gate_links=("document-delivery-package-manifest", "client-delivery-transparency-policy"),
                user_need_ids=("document-generation", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="case-role-permission-matrix",
                title="Case role permission matrix",
                category="safety",
                size="large",
                status="shipped",
                impact="Defines privacy-safe allow, deny, and approval-required decisions for case roles across read, write, export, share, billing, audit, and review operations.",
                evidence_paths=(
                    "app/backend/services/case_role_permission_matrix.py",
                    "app/backend/tests/test_case_role_permission_matrix.py",
                    "docs/CASE_ROLE_PERMISSION_MATRIX.md",
                ),
                release_gate_links=("case-role-permission-matrix", "case-team-access-policy"),
                user_need_ids=("case-workbench", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="billing-usage-quota-policy",
                title="Billing usage quota policy",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Adds local plan limits, review credits, upload quotas, generated document quotas, premium escalation gates, and privacy-safe usage aggregation.",
                evidence_paths=(
                    "app/backend/services/billing_usage_quota_policy.py",
                    "app/backend/tests/test_billing_usage_quota_policy.py",
                    "docs/BILLING_USAGE_QUOTA_POLICY.md",
                ),
                release_gate_links=("billing-usage-quota-policy", "billing-entitlement-gap"),
                user_need_ids=("billing-entitlements", "low-cost-routing"),
            ),
            LedgerEntry(
                id="feedback-lifecycle-policy",
                title="Feedback lifecycle policy",
                category="maintenance",
                size="large",
                status="shipped",
                impact="Defines feedback states from intake through triage, roadmap linkage, release validation, customer-visible resolution, and closure.",
                evidence_paths=(
                    "app/backend/services/feedback_lifecycle_policy.py",
                    "app/backend/tests/test_feedback_lifecycle_policy.py",
                    "docs/FEEDBACK_LIFECYCLE_POLICY.md",
                ),
                release_gate_links=("feedback-lifecycle-policy", "feedback-roadmap-alignment"),
                user_need_ids=("reviewer-visibility", "product-readiness"),
            ),
            LedgerEntry(
                id="case-workbench-ui-binding",
                title="Case workbench UI binding",
                category="frontend_ui",
                size="large",
                status="planned",
                impact="Bind the case workbench payload contract into an operator-facing case workspace view.",
                evidence_paths=("app/frontend/src/pages/MaintenanceEvidencePage.tsx",),
                release_gate_links=("frontend-typecheck", "case-workbench-payload"),
                user_need_ids=("case-workbench", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-source-ingestion-metadata",
                title="Legal source ingestion metadata",
                category="benchmark",
                size="large",
                status="planned",
                impact="Persist source jurisdiction, citation, effective-date, and freshness metadata for legal knowledge retrieval.",
                evidence_paths=("app/backend/services/legal_source_freshness_policy.py",),
                release_gate_links=("legal-source-freshness-policy", "legal-rag-evaluation"),
                user_need_ids=("grounded-legal-output",),
            ),
            LedgerEntry(
                id="billing-quota-persistence",
                title="Billing quota persistence",
                category="product_planning",
                size="large",
                status="planned",
                impact="Persist privacy-safe quota counters and expose deterministic over-limit reasons in entitlement responses.",
                evidence_paths=("app/backend/services/billing_usage_quota_policy.py",),
                release_gate_links=("billing-usage-quota-policy", "billing-entitlement-gap"),
                user_need_ids=("billing-entitlements", "low-cost-routing"),
            ),
        ]
