from __future__ import annotations

from collections import Counter
from dataclasses import asdict, dataclass
from typing import Any, Literal


TARGET_CONTINUOUS_HOURS = 24
TARGET_MEDIUM_LARGE_UPDATE_COUNT = 100

UpdateSize = Literal["medium", "large"]
UpdateStatus = Literal["shipped", "planned"]


@dataclass(frozen=True)
class LedgerEntry:
    id: str
    title: str
    category: str
    size: UpdateSize
    status: UpdateStatus
    impact: str
    evidence_paths: tuple[str, ...]
    release_gate_links: tuple[str, ...]
    user_need_ids: tuple[str, ...]
    commit_hint: str | None = None

    def to_api(self) -> dict[str, Any]:
        data = asdict(self)
        data["evidence_paths"] = list(self.evidence_paths)
        data["release_gate_links"] = list(self.release_gate_links)
        data["user_need_ids"] = list(self.user_need_ids)
        return data


class ContinuousUpdateLedgerService:
    """Track long-running maintenance progress without claiming completion early."""

    def build_ledger(self) -> dict[str, Any]:
        entries = self._entries()
        completed = [entry for entry in entries if entry.status == "shipped"]
        planned = [entry for entry in entries if entry.status == "planned"]
        category_counts = Counter(entry.category for entry in completed)
        size_counts = Counter(entry.size for entry in completed)
        completed_count = len(completed)
        remaining_count = max(0, TARGET_MEDIUM_LARGE_UPDATE_COUNT - completed_count)

        return {
            "status": "in_progress",
            "goal": {
                "target_continuous_hours": TARGET_CONTINUOUS_HOURS,
                "target_medium_large_update_count": TARGET_MEDIUM_LARGE_UPDATE_COUNT,
                "completion_policy": [
                    "Do not mark the goal complete until both the 24-hour evidence window and 100+ medium/large shipped updates are reviewable.",
                    "Count only repository-backed updates with code, tests, docs, or reviewer-facing evidence.",
                    "Keep laptop-safe quick suites separate from heavier benchmark or public corpus work.",
                ],
            },
            "summary": {
                "completed_medium_large_update_count": completed_count,
                "remaining_medium_large_update_count": remaining_count,
                "planned_update_count": len(planned),
                "large_update_count": size_counts.get("large", 0),
                "medium_update_count": size_counts.get("medium", 0),
                "category_counts": dict(sorted(category_counts.items())),
                "continuous_hours_verified": 0,
                "continuous_hours_remaining": TARGET_CONTINUOUS_HOURS,
                "completion_ready": False,
            },
            "completed_updates": [entry.to_api() for entry in completed],
            "next_update_queue": [entry.to_api() for entry in planned[:12]],
            "twenty_four_hour_evidence_requirements": [
                "Record timestamped commits or CI runs across the full 24-hour window.",
                "Keep each update reviewable through a code path, test, doc, endpoint, or UI surface.",
                "Do not treat local-only benchmark attempts as shipped updates unless results are normalized and stored safely.",
            ],
            "hundred_update_evidence_requirements": [
                "Group updates by model operations, legal benchmark coverage, frontend visibility, maintenance evidence, and safety controls.",
                "Keep small fixture tests serial and cheap-first so low-resource machines can validate the work.",
                "Use release-readiness and OSS-maintenance evidence endpoints as the reviewer-facing index.",
            ],
            "low_resource_test_policy": {
                "default_fixture_limit": 3,
                "max_parallel_requests": 1,
                "network_access": "disabled_by_default",
                "model_call_policy": "manual_serial_only",
                "recommended_endpoint": "/api/v1/maintenance/legal-review-benchmark/quick-suite",
            },
            "release_guardrails": [
                "The ledger is optional release evidence; it must not unblock a release by itself.",
                "Secret values, account credentials, raw client documents, and raw gateway responses must stay out of git.",
                "Public benchmark sources stay metadata-only until license, attribution, and privacy review pass.",
            ],
            "validation_commands": [
                "python -m pytest tests/test_continuous_update_ledger.py -q",
                "python -m pytest tests/test_continuous_session_evidence.py -q",
                "python -m pytest tests/test_continuous_session_timeline.py -q",
                "python -m pytest tests/test_continuous_session_review_packet.py -q",
                "python -m pytest tests/test_git_history_evidence.py -q",
                "python -m pytest tests/test_validation_event_evidence.py -q",
                "python -m pytest tests/test_runtime_router_discovery.py -q",
                "python -m pytest tests/test_legal_fixture_quick_suite.py tests/test_legal_review_benchmark.py -q",
            ],
        }

    def _entries(self) -> list[LedgerEntry]:
        return [
            LedgerEntry(
                id="model-gateway-probe-evaluation",
                title="Sanitized model gateway probe evaluation",
                category="model_ops",
                size="large",
                status="shipped",
                impact="Reviews OpenAI-compatible gateway model and chat probes without storing keys or raw secrets.",
                evidence_paths=(
                    "app/backend/services/model_gateway_probe_evaluation.py",
                    "app/backend/tests/test_model_gateway_probe_evaluation.py",
                    "docs/MODEL_GATEWAY_PROBE_EVALUATION.md",
                ),
                release_gate_links=("model-gateway-probe-evaluation", "model-ops-readiness"),
                user_need_ids=("low-cost-routing", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="model-gateway-probe-ui",
                title="Model gateway probe evidence in operations UI",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Surfaces probe recommendations and sanitized defaults in the model operations page.",
                evidence_paths=(
                    "app/frontend/src/lib/modelOpsApi.ts",
                    "app/frontend/src/pages/ModelOpsPage.tsx",
                ),
                release_gate_links=("frontend-typecheck", "frontend-build"),
                user_need_ids=("low-cost-routing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="model-gateway-health-plan",
                title="Gateway health planning before live requests",
                category="model_ops",
                size="large",
                status="shipped",
                impact="Documents cheap JSON probes, base URL checks, and manual health gates before real model calls.",
                evidence_paths=(
                    "app/backend/services/model_gateway_health_plan.py",
                    "app/backend/tests/test_model_gateway_health_plan.py",
                    "docs/MODEL_GATEWAY_HEALTH_PLAN.md",
                ),
                release_gate_links=("model-gateway-health-plan", "model-ops-readiness"),
                user_need_ids=("safe-ai-ops", "low-cost-routing"),
            ),
            LedgerEntry(
                id="legal-research-backlog",
                title="Research-backed legal AI backlog",
                category="user_research",
                size="large",
                status="shipped",
                impact="Maps LegalBench, FrugalGPT, RAGAS, CRAG, and CUAD signals into concrete engineering tasks.",
                evidence_paths=(
                    "app/backend/services/legal_research_backlog.py",
                    "app/backend/tests/test_legal_research_backlog.py",
                    "docs/LEGAL_RESEARCH_BACKLOG.md",
                ),
                release_gate_links=("legal-review-benchmark", "oss-maintenance-evidence"),
                user_need_ids=("grounded-legal-output", "low-cost-routing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-external-research-digest",
                title="External legal AI research digest",
                category="user_research",
                size="large",
                status="shipped",
                impact="Maps LegalBench, CUAD, RAGAS, CRAG, and FrugalGPT signals into local legal benchmark, RAG, and cheap-first routing work.",
                evidence_paths=(
                    "app/backend/services/legal_external_research_digest.py",
                    "app/backend/tests/test_legal_external_research_digest.py",
                    "docs/LEGAL_EXTERNAL_RESEARCH_DIGEST.md",
                ),
                release_gate_links=("legal-review-benchmark", "oss-maintenance-evidence"),
                user_need_ids=("grounded-legal-output", "low-cost-routing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-research-backlog-ui",
                title="Legal research backlog reviewer panel",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Shows research backlog priorities and evidence paths on the maintenance page.",
                evidence_paths=(
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                ),
                release_gate_links=("frontend-typecheck", "frontend-build"),
                user_need_ids=("reviewer-visibility", "grounded-legal-output"),
            ),
            LedgerEntry(
                id="legal-public-benchmark-sampler",
                title="Resource-capped public benchmark sampler",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Keeps public benchmark work as metadata until license and attribution review are complete.",
                evidence_paths=(
                    "app/backend/services/legal_public_benchmark_sampler.py",
                    "app/backend/tests/test_legal_public_benchmark_sampler.py",
                    "docs/LEGAL_PUBLIC_BENCHMARK_SAMPLER.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("grounded-legal-output", "low-resource-testing"),
            ),
            LedgerEntry(
                id="legal-fixture-quick-suite",
                title="Laptop-safe legal fixture quick suite",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Selects a tiny serial fixture subset for low-resource local testing.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_quick_suite.py",
                    "app/backend/tests/test_legal_fixture_quick_suite.py",
                    "docs/LEGAL_FIXTURE_QUICK_SUITE.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("low-resource-testing", "low-cost-routing"),
            ),
            LedgerEntry(
                id="legal-fixture-model-matrix",
                title="Fixture-level Gemini and NewAPI model matrix",
                category="model_ops",
                size="medium",
                status="shipped",
                impact="Assigns cheap-first, fallback, and premium-exception candidates per legal fixture.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_model_matrix.py",
                    "app/backend/tests/test_legal_fixture_model_matrix.py",
                    "docs/LEGAL_FIXTURE_MODEL_MATRIX.md",
                ),
                release_gate_links=("legal-review-benchmark", "model-fallback-chains"),
                user_need_ids=("low-cost-routing", "low-resource-testing"),
            ),
            LedgerEntry(
                id="legal-fixture-prompt-pack",
                title="Cheap-first legal fixture prompt pack",
                category="benchmark",
                size="medium",
                status="shipped",
                impact="Builds small legal document prompts with observation targets for manual gateway checks.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_prompt_pack.py",
                    "app/backend/tests/test_legal_fixture_prompt_pack.py",
                    "docs/LEGAL_FIXTURE_PROMPT_PACK.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("grounded-legal-output", "low-cost-routing"),
            ),
            LedgerEntry(
                id="legal-fixture-gateway-manifest",
                title="Safe legal fixture gateway manifests",
                category="safety",
                size="medium",
                status="shipped",
                impact="Generates OpenAI-compatible request manifests with placeholders instead of real credentials.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_gateway_manifest.py",
                    "app/backend/tests/test_legal_fixture_gateway_manifest.py",
                    "docs/LEGAL_FIXTURE_GATEWAY_MANIFEST.md",
                ),
                release_gate_links=("secret-scan", "legal-review-benchmark"),
                user_need_ids=("safe-ai-ops", "low-resource-testing"),
            ),
            LedgerEntry(
                id="legal-fixture-run-plan",
                title="Serial cheap-first fixture run plan",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Converts fixture manifests into one-at-a-time local batches with conditional escalation.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_run_plan.py",
                    "app/backend/tests/test_legal_fixture_run_plan.py",
                    "docs/LEGAL_FIXTURE_RUN_PLAN.md",
                ),
                release_gate_links=("legal-review-benchmark", "model-escalation-policy"),
                user_need_ids=("low-resource-testing", "low-cost-routing"),
            ),
            LedgerEntry(
                id="legal-fixture-local-run-package",
                title="One-at-a-time local fixture run package",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Bundles request JSON, PowerShell and curl templates, observation slots, and report scaffolding.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_local_run_package.py",
                    "app/backend/tests/test_legal_fixture_local_run_package.py",
                    "docs/LEGAL_FIXTURE_LOCAL_RUN_PACKAGE.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("low-resource-testing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-fixture-response-normalizer",
                title="Local fixture response normalizer",
                category="safety",
                size="medium",
                status="shipped",
                impact="Redacts secret-like values and normalizes local gateway outputs into fixture observations.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_response_normalizer.py",
                    "app/backend/tests/test_legal_fixture_response_normalizer.py",
                    "docs/LEGAL_FIXTURE_RESPONSE_NORMALIZER.md",
                ),
                release_gate_links=("secret-scan", "legal-review-benchmark"),
                user_need_ids=("safe-ai-ops", "low-resource-testing"),
            ),
            LedgerEntry(
                id="legal-fixture-local-run-review",
                title="One-step local fixture run review",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Normalizes local responses, scores smoke coverage, builds run reports, and returns evidence bundles.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_local_run_review.py",
                    "app/backend/tests/test_legal_fixture_local_run_review.py",
                    "docs/LEGAL_FIXTURE_LOCAL_RUN_REVIEW.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("low-resource-testing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-fixture-run-report",
                title="Cheap-first fixture run report",
                category="release_evidence",
                size="medium",
                status="shipped",
                impact="Turns fixture observations into release decisions and fixture-scoped escalation actions.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_run_report.py",
                    "app/backend/tests/test_legal_fixture_run_report.py",
                    "docs/LEGAL_FIXTURE_RUN_REPORT.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("reviewer-visibility", "low-cost-routing"),
            ),
            LedgerEntry(
                id="legal-fixture-evidence-bundle",
                title="Legal fixture evidence bundle",
                category="release_evidence",
                size="medium",
                status="shipped",
                impact="Archives component status, validation commands, release-safe claims, and cheap-first run evidence.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_evidence_bundle.py",
                    "app/backend/tests/test_legal_fixture_evidence_bundle.py",
                    "docs/LEGAL_FIXTURE_EVIDENCE_BUNDLE.md",
                ),
                release_gate_links=("legal-review-benchmark", "oss-maintenance-evidence"),
                user_need_ids=("reviewer-visibility", "grounded-legal-output"),
            ),
            LedgerEntry(
                id="user-needs-radar",
                title="User needs radar",
                category="user_research",
                size="medium",
                status="shipped",
                impact="Ranks target legal-review needs and links them to release gates and evidence paths.",
                evidence_paths=(
                    "app/backend/services/user_needs_radar.py",
                    "app/backend/tests/test_user_needs_radar.py",
                    "docs/USER_NEEDS_RADAR.md",
                ),
                release_gate_links=("user-needs-radar", "oss-maintenance-evidence"),
                user_need_ids=("reviewer-visibility", "grounded-legal-output", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="feedback-roadmap-alignment",
                title="Feedback-to-roadmap alignment",
                category="maintenance",
                size="medium",
                status="shipped",
                impact="Maps support feedback categories to user-need IDs and release gates.",
                evidence_paths=(
                    "app/backend/services/feedback_roadmap_alignment.py",
                    "app/backend/tests/test_feedback_roadmap_alignment.py",
                    "docs/FEEDBACK_ROADMAP_ALIGNMENT.md",
                ),
                release_gate_links=("feedback-roadmap-alignment", "oss-maintenance-evidence"),
                user_need_ids=("reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="product-feature-gap-radar",
                title="Product-wide feature gap radar",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Makes incomplete product modules explicit across case workbench, document generation, contract review, evidence, OCR, billing, team, feedback, model ops, legal knowledge, and safety.",
                evidence_paths=(
                    "app/backend/services/product_feature_gap_radar.py",
                    "app/backend/tests/test_product_feature_gap_radar.py",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                release_gate_links=("product-feature-gap-radar", "oss-maintenance-evidence"),
                user_need_ids=("reviewer-visibility", "product-readiness"),
            ),
            LedgerEntry(
                id="case-evidence-graph-contract",
                title="Case evidence graph contract",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Defines the fact-evidence-citation-risk graph contract and blocking gap flags before a full case workbench graph UI is built.",
                evidence_paths=(
                    "app/backend/services/case_evidence_graph.py",
                    "app/backend/tests/test_case_evidence_graph.py",
                    "docs/CASE_EVIDENCE_GRAPH.md",
                ),
                release_gate_links=("case-evidence-graph", "legal-rag-evaluation"),
                user_need_ids=("grounded-legal-output", "case-workbench"),
            ),
            LedgerEntry(
                id="case-intake-completeness",
                title="Case intake completeness checklist",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Blocks document generation when parties, venue, deadlines, claims, evidence, or risk disclosure fields are incomplete.",
                evidence_paths=(
                    "app/backend/services/case_intake_completeness.py",
                    "app/backend/tests/test_case_intake_completeness.py",
                    "docs/CASE_INTAKE_COMPLETENESS.md",
                ),
                release_gate_links=("case-intake-completeness", "case-evidence-graph"),
                user_need_ids=("case-workbench", "document-generation", "grounded-legal-output"),
            ),
            LedgerEntry(
                id="case-timeline-deadline-risk",
                title="Case timeline deadline risk",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Adds deterministic event, deadline, urgent-blocker, and missing-fact risk metadata for the case workspace.",
                evidence_paths=(
                    "app/backend/services/case_timeline_deadline_risk.py",
                    "app/backend/tests/test_case_timeline_deadline_risk.py",
                    "docs/CASE_TIMELINE_DEADLINE_RISK.md",
                ),
                release_gate_links=("case-timeline-deadline-risk", "case-intake-completeness"),
                user_need_ids=("case-workbench", "reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="case-task-notification-policy",
                title="Case task notification policy",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Defines deterministic task reminders, owner blockers, urgent escalations, client material reminders, and lawyer review notifications.",
                evidence_paths=(
                    "app/backend/services/case_task_notification_policy.py",
                    "app/backend/tests/test_case_task_notification_policy.py",
                    "docs/CASE_TASK_NOTIFICATION_POLICY.md",
                ),
                release_gate_links=("case-task-notification-policy", "case-timeline-deadline-risk"),
                user_need_ids=("case-workbench", "reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="case-team-access-policy",
                title="Case team access policy",
                category="safety",
                size="medium",
                status="shipped",
                impact="Defines least-privilege owner, lawyer, paralegal, reviewer, and client roles with audit-required sensitive operations.",
                evidence_paths=(
                    "app/backend/services/case_team_access_policy.py",
                    "app/backend/tests/test_case_team_access_policy.py",
                    "docs/CASE_TEAM_ACCESS_POLICY.md",
                ),
                release_gate_links=("case-team-access-policy", "product-feature-gap-radar"),
                user_need_ids=("case-workbench", "reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="matter-audit-retention-policy",
                title="Matter audit retention policy",
                category="safety",
                size="medium",
                status="shipped",
                impact="Defines privacy-minimized audit events, forbidden fields, retention buckets, and release blockers for matter workflows.",
                evidence_paths=(
                    "app/backend/services/matter_audit_retention_policy.py",
                    "app/backend/tests/test_matter_audit_retention_policy.py",
                    "docs/MATTER_AUDIT_RETENTION_POLICY.md",
                ),
                release_gate_links=("matter-audit-retention-policy", "case-team-access-policy"),
                user_need_ids=("case-workbench", "reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="client-delivery-risk-checklist",
                title="Client delivery risk checklist",
                category="safety",
                size="medium",
                status="shipped",
                impact="Adds delivery blockers for citation evidence, lawyer review, scope assumptions, AI limitation notices, and client-readable risk language.",
                evidence_paths=(
                    "app/backend/services/client_delivery_risk_checklist.py",
                    "app/backend/tests/test_client_delivery_risk_checklist.py",
                    "docs/CLIENT_DELIVERY_RISK_CHECKLIST.md",
                ),
                release_gate_links=("client-delivery-risk-checklist", "case-intake-completeness"),
                user_need_ids=("grounded-legal-output", "reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="lawyer-review-workflow-policy",
                title="Lawyer review workflow policy",
                category="safety",
                size="medium",
                status="shipped",
                impact="Defines draft, lawyer review, approved, rejected, revise-required, and client-deliverable state transitions.",
                evidence_paths=(
                    "app/backend/services/lawyer_review_workflow_policy.py",
                    "app/backend/tests/test_lawyer_review_workflow_policy.py",
                    "docs/LAWYER_REVIEW_WORKFLOW_POLICY.md",
                ),
                release_gate_links=("lawyer-review-workflow-policy", "client-delivery-risk-checklist"),
                user_need_ids=("reviewer-visibility", "safe-ai-ops", "document-generation"),
            ),
            LedgerEntry(
                id="evidence-exhibit-package-policy",
                title="Evidence exhibit package policy",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Defines exhibit numbering, proof purpose, source and page anchors, three-factor review, and export manifest requirements.",
                evidence_paths=(
                    "app/backend/services/evidence_exhibit_package_policy.py",
                    "app/backend/tests/test_evidence_exhibit_package_policy.py",
                    "docs/EVIDENCE_EXHIBIT_PACKAGE_POLICY.md",
                ),
                release_gate_links=("evidence-exhibit-package-policy", "case-evidence-graph"),
                user_need_ids=("case-workbench", "grounded-legal-output", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-document-template-matrix",
                title="Legal document template matrix",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Defines required fields, formatting requirements, blockers, lawyer-review gates, and export formats for six legal document types.",
                evidence_paths=(
                    "app/backend/services/legal_document_template_matrix.py",
                    "app/backend/tests/test_legal_document_template_matrix.py",
                    "docs/LEGAL_DOCUMENT_TEMPLATE_MATRIX.md",
                ),
                release_gate_links=("legal-document-template-matrix", "product-feature-gap-radar"),
                user_need_ids=("document-generation", "case-workbench", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-document-export-readiness",
                title="Legal document export readiness",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Blocks final export until template fields, blocker clearance, lawyer review, source support, redaction, version lock, and format support pass.",
                evidence_paths=(
                    "app/backend/services/legal_document_export_readiness.py",
                    "app/backend/tests/test_legal_document_export_readiness.py",
                    "docs/LEGAL_DOCUMENT_EXPORT_READINESS.md",
                ),
                release_gate_links=("legal-document-export-readiness", "legal-document-template-matrix"),
                user_need_ids=("document-generation", "grounded-legal-output", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="ocr-import-readiness-policy",
                title="OCR import readiness policy",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Defines uploaded, preflight, OCR-needed, OCR-failed, parsed, blocked, and manual-review states for scanned or low-text files.",
                evidence_paths=(
                    "app/backend/services/ocr_import_readiness_policy.py",
                    "app/backend/tests/test_ocr_import_readiness_policy.py",
                    "docs/OCR_IMPORT_READINESS_POLICY.md",
                ),
                release_gate_links=("ocr-import-readiness-policy", "product-feature-gap-radar"),
                user_need_ids=("document-intake", "case-workbench", "low-resource-testing"),
            ),
            LedgerEntry(
                id="billing-entitlement-gap-evidence",
                title="Billing entitlement gap evidence",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Adds deterministic payment activation and usage-plan guard evidence without integrating a live payment gateway.",
                evidence_paths=(
                    "app/backend/services/billing_entitlement_gap.py",
                    "app/backend/tests/test_billing_entitlement_gap.py",
                    "docs/BILLING_ENTITLEMENT_GAP.md",
                ),
                release_gate_links=("billing-entitlement-gap", "product-feature-gap-radar"),
                user_need_ids=("billing-entitlements", "product-readiness"),
            ),
            LedgerEntry(
                id="continuous-update-ledger-ui",
                title="Reviewer-facing continuous update ledger panel",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Expose the ledger on the maintenance dashboard with completed count, remaining count, and low-resource test policy.",
                evidence_paths=(
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                ),
                release_gate_links=("frontend-typecheck", "frontend-build"),
                user_need_ids=("reviewer-visibility",),
            ),
            LedgerEntry(
                id="cheap-first-result-archive",
                title="Cheap-first fixture result archive",
                category="release_evidence",
                size="large",
                status="shipped",
                impact="Store normalized fixture run summaries without raw client text or raw model output.",
                evidence_paths=(
                    "app/backend/services/legal_fixture_result_archive.py",
                    "app/backend/tests/test_legal_fixture_result_archive.py",
                    "docs/LEGAL_FIXTURE_RESULT_ARCHIVE.md",
                ),
                release_gate_links=("legal-review-benchmark", "secret-scan"),
                user_need_ids=("low-resource-testing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="model-default-recommendation-snapshot",
                title="Gemini/NewAPI default recommendation snapshot",
                category="model_ops",
                size="medium",
                status="shipped",
                impact="Checks high-volume model defaults against stable lowest-tier Gemini recommendations and flags unknown gateway model names for catalog review.",
                evidence_paths=(
                    "app/backend/services/model_default_recommendation_snapshot.py",
                    "app/backend/tests/test_model_default_recommendation_snapshot.py",
                    "docs/MODEL_DEFAULT_RECOMMENDATION_SNAPSHOT.md",
                ),
                release_gate_links=("model-default-recommendation-snapshot", "model-default-optimization"),
                user_need_ids=("low-cost-routing", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="gemini-newapi-cheap-first-policy",
                title="Gemini/NewAPI cheap-first policy",
                category="model_ops",
                size="medium",
                status="shipped",
                impact="Documents supported Gemini families, NewAPI-compatible prefixes, forbidden premium defaults, and explicit-only handling for unknown Gemini-like models.",
                evidence_paths=(
                    "app/backend/services/gemini_newapi_cheap_first_policy.py",
                    "app/backend/tests/test_gemini_newapi_cheap_first_policy.py",
                    "docs/GEMINI_NEWAPI_CHEAP_FIRST_POLICY.md",
                ),
                release_gate_links=("gemini-newapi-cheap-first-policy", "model-default-recommendation-snapshot"),
                user_need_ids=("low-cost-routing", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="legal-document-benchmark-fixtures",
                title="Small legal document benchmark fixtures",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Adds deterministic Chinese legal-document snippets and local classification, extraction, deadline, and risk-label scoring without model calls.",
                evidence_paths=(
                    "app/backend/services/legal_document_benchmark_fixtures.py",
                    "app/backend/tests/test_legal_document_benchmark_fixtures.py",
                    "docs/LEGAL_DOCUMENT_BENCHMARK_FIXTURES.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("grounded-legal-output", "low-resource-testing"),
            ),
            LedgerEntry(
                id="matter-intake-readiness-policy",
                title="Matter intake readiness policy",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Evaluates matter-opening metadata for required fields, conflict screening, engagement materials, urgent deadlines, and lawyer-review gates.",
                evidence_paths=(
                    "app/backend/services/matter_intake_readiness_policy.py",
                    "app/backend/tests/test_matter_intake_readiness_policy.py",
                    "docs/MATTER_INTAKE_READINESS_POLICY.md",
                ),
                release_gate_links=("matter-intake-readiness-policy", "case-intake-completeness"),
                user_need_ids=("case-workbench", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="deadline-validation-policy",
                title="Deadline validation policy",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Adds deterministic date metadata checks for service, evidence, appeal, filing, limitation, and contract-performance deadlines.",
                evidence_paths=(
                    "app/backend/services/deadline_validation_policy.py",
                    "app/backend/tests/test_deadline_validation_policy.py",
                    "docs/DEADLINE_VALIDATION_POLICY.md",
                ),
                release_gate_links=("deadline-validation-policy", "case-timeline-deadline-risk"),
                user_need_ids=("case-workbench", "reviewer-visibility", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="client-delivery-transparency-policy",
                title="Client delivery transparency policy",
                category="safety",
                size="medium",
                status="shipped",
                impact="Blocks or warns on delivery metadata gaps for client confirmation, version diffs, risk notices, delivery records, and follow-up tasks.",
                evidence_paths=(
                    "app/backend/services/client_delivery_transparency_policy.py",
                    "app/backend/tests/test_client_delivery_transparency_policy.py",
                    "docs/CLIENT_DELIVERY_TRANSPARENCY_POLICY.md",
                ),
                release_gate_links=("client-delivery-transparency-policy", "client-delivery-risk-checklist"),
                user_need_ids=("reviewer-visibility", "safe-ai-ops", "document-generation"),
            ),
            LedgerEntry(
                id="gemini-price-refresh-monitor",
                title="Gemini and gateway price refresh monitor",
                category="model_ops",
                size="medium",
                status="shipped",
                impact="Flags local catalog, forecast, and observed gateway model drift when cheap-first assumptions no longer match price metadata.",
                evidence_paths=(
                    "app/backend/services/model_price_refresh_monitor.py",
                    "app/backend/tests/test_model_price_refresh_monitor.py",
                    "docs/MODEL_PRICE_REFRESH_MONITOR.md",
                ),
                release_gate_links=("model-price-refresh-monitor", "model-cost-forecast"),
                user_need_ids=("low-cost-routing",),
            ),
            LedgerEntry(
                id="small-legal-document-corpus-expansion",
                title="Small legal fixture corpus expansion",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Adds eight local synthetic Chinese legal-document scenarios across labor, lease, sales, service, lending, tort, and consumer workflows.",
                evidence_paths=(
                    "app/backend/services/small_legal_document_corpus_expansion.py",
                    "app/backend/tests/test_small_legal_document_corpus_expansion.py",
                    "docs/SMALL_LEGAL_DOCUMENT_CORPUS_EXPANSION.md",
                ),
                release_gate_links=("legal-review-benchmark",),
                user_need_ids=("grounded-legal-output", "low-resource-testing"),
            ),
            LedgerEntry(
                id="legal-rag-failure-fixtures",
                title="Legal RAG failure fixtures",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Adds deterministic RAG failure fixtures for missing citations, stale law, jurisdiction mismatch, unsupported conclusions, hallucinated articles, and conflicting facts.",
                evidence_paths=(
                    "app/backend/services/legal_rag_failure_fixtures.py",
                    "app/backend/tests/test_legal_rag_failure_fixtures.py",
                    "docs/LEGAL_RAG_FAILURE_FIXTURES.md",
                ),
                release_gate_links=("legal-review-benchmark", "legal-rag-evaluation"),
                user_need_ids=("grounded-legal-output",),
            ),
            LedgerEntry(
                id="maintenance-dashboard-filtering",
                title="Maintenance dashboard filtering",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Adds category, status, and search filters that combine completed and queued ledger entries in the maintenance page.",
                evidence_paths=("app/frontend/src/pages/MaintenanceEvidencePage.tsx",),
                release_gate_links=("frontend-typecheck", "frontend-build"),
                user_need_ids=("reviewer-visibility",),
            ),
            LedgerEntry(
                id="model-cost-regression-snapshots",
                title="Model cost regression snapshots",
                category="model_ops",
                size="large",
                status="shipped",
                impact="Compares deterministic cheap-first monthly costs against premium-only baselines and drift thresholds for fast, classification, OCR, review, and PDF routes.",
                evidence_paths=(
                    "app/backend/services/model_cost_regression_snapshots.py",
                    "app/backend/tests/test_model_cost_regression_snapshots.py",
                    "docs/MODEL_COST_REGRESSION_SNAPSHOTS.md",
                ),
                release_gate_links=("model-cost-regression-snapshots", "model-cost-guardrails", "model-routing-replay"),
                user_need_ids=("low-cost-routing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="twenty-four-hour-heartbeat-evidence",
                title="24-hour heartbeat evidence export",
                category="maintenance",
                size="medium",
                status="shipped",
                impact="Defines a privacy-safe heartbeat evidence format for commit, test, push, and review events across a long maintenance window without claiming completion early.",
                evidence_paths=(
                    "app/backend/services/maintenance_heartbeat_evidence.py",
                    "app/backend/tests/test_maintenance_heartbeat_evidence.py",
                    "docs/MAINTENANCE_HEARTBEAT_EVIDENCE.md",
                ),
                release_gate_links=("maintenance-heartbeat-evidence", "oss-maintenance-evidence"),
                user_need_ids=("reviewer-visibility",),
            ),
            LedgerEntry(
                id="continuous-session-evidence-validator",
                title="Continuous session evidence validator",
                category="maintenance",
                size="large",
                status="shipped",
                impact="Validates explicit 24-hour maintenance-session metadata with max-gap, credential-scan, low-resource test, and 100+ update-count checks without inventing completion evidence.",
                evidence_paths=(
                    "app/backend/services/continuous_session_evidence.py",
                    "app/backend/tests/test_continuous_session_evidence.py",
                    "docs/CONTINUOUS_SESSION_EVIDENCE.md",
                ),
                release_gate_links=("continuous-session-evidence", "continuous-update-ledger", "oss-maintenance-evidence"),
                user_need_ids=("reviewer-visibility", "low-resource-testing"),
            ),
            LedgerEntry(
                id="continuous-session-timeline",
                title="Continuous session reviewer timeline",
                category="maintenance",
                size="large",
                status="shipped",
                impact="Combines ledger progress, explicit session validation, heartbeat records, low-resource fixture evidence, blockers, and privacy boundaries into a single reviewer-facing timeline.",
                evidence_paths=(
                    "app/backend/services/continuous_session_timeline.py",
                    "app/backend/tests/test_continuous_session_timeline.py",
                    "docs/CONTINUOUS_SESSION_TIMELINE.md",
                ),
                release_gate_links=("continuous-session-timeline", "continuous-session-evidence", "continuous-update-ledger"),
                user_need_ids=("reviewer-visibility", "low-resource-testing"),
            ),
            LedgerEntry(
                id="git-history-cadence-evidence",
                title="Git history cadence evidence",
                category="maintenance",
                size="large",
                status="shipped",
                impact="Extracts metadata-only git commit cadence evidence, longest windows, and gap analysis without reading raw diffs, author emails, credentials, or legal text.",
                evidence_paths=(
                    "app/backend/services/git_history_evidence.py",
                    "app/backend/tests/test_git_history_evidence.py",
                    "docs/GIT_HISTORY_EVIDENCE.md",
                ),
                release_gate_links=("git-history-evidence", "continuous-session-timeline", "continuous-update-ledger"),
                user_need_ids=("reviewer-visibility", "low-resource-testing"),
            ),
            LedgerEntry(
                id="validation-event-evidence-normalizer",
                title="Validation event evidence normalizer",
                category="maintenance",
                size="large",
                status="shipped",
                impact="Normalizes metadata-only test, credential-scan, push, release-review, and low-resource legal fixture events into continuous-session timeline records while rejecting raw logs, legal text, model output, credentials, and emails.",
                evidence_paths=(
                    "app/backend/services/validation_event_evidence.py",
                    "app/backend/tests/test_validation_event_evidence.py",
                    "app/backend/services/continuous_session_timeline.py",
                    "docs/VALIDATION_EVENT_EVIDENCE.md",
                ),
                release_gate_links=("validation-event-evidence", "continuous-session-timeline", "git-history-evidence"),
                user_need_ids=("reviewer-visibility", "low-resource-testing", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="continuous-session-review-packet",
                title="Continuous session review packet",
                category="maintenance",
                size="large",
                status="shipped",
                impact="Combines the continuous update ledger, session timeline, git cadence, validation event evidence, privacy boundary, blockers, reviewer questions, and a stable metadata hash into a support-review packet without echoing raw logs, legal text, model outputs, credentials, or emails.",
                evidence_paths=(
                    "app/backend/services/continuous_session_review_packet.py",
                    "app/backend/tests/test_continuous_session_review_packet.py",
                    "app/backend/routers/maintenance.py",
                    "docs/CONTINUOUS_SESSION_REVIEW_PACKET.md",
                ),
                release_gate_links=("continuous-session-review-packet", "continuous-session-timeline", "validation-event-evidence"),
                user_need_ids=("reviewer-visibility", "low-resource-testing", "product-readiness"),
            ),
            LedgerEntry(
                id="frontend-local-run-review-form",
                title="Frontend local run review form",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Lets maintainers paste already-redacted local fixture responses into the existing response normalizer flow.",
                evidence_paths=("app/frontend/src/pages/MaintenanceEvidencePage.tsx",),
                release_gate_links=("frontend-typecheck", "legal-review-benchmark"),
                user_need_ids=("low-resource-testing", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="route-telemetry-persistence-plan",
                title="Route telemetry persistence plan",
                category="model_ops",
                size="large",
                status="shipped",
                impact="Defines sanitized route telemetry event schema, allowed and forbidden fields, retention policy, and sample-event validation before durable storage.",
                evidence_paths=(
                    "app/backend/services/route_telemetry_persistence_plan.py",
                    "app/backend/tests/test_route_telemetry_persistence_plan.py",
                    "docs/ROUTE_TELEMETRY_PERSISTENCE_PLAN.md",
                ),
                release_gate_links=("route-telemetry-persistence-plan", "model-route-telemetry", "secret-scan"),
                user_need_ids=("low-cost-routing", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="legal-source-freshness-policy",
                title="Legal source freshness and jurisdiction policy",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Adds deterministic metadata checks for jurisdiction, citation, effective date, and freshness before legal sources can support RAG answers.",
                evidence_paths=(
                    "app/backend/services/legal_source_freshness_policy.py",
                    "app/backend/tests/test_legal_source_freshness_policy.py",
                    "docs/LEGAL_SOURCE_FRESHNESS_POLICY.md",
                ),
                release_gate_links=("legal-source-freshness-policy", "legal-rag-evaluation", "legal-knowledge-audit"),
                user_need_ids=("grounded-legal-output", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="case-workbench-payload",
                title="Case workbench payload contract",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Assembles matter intake, deadline validation, timeline risk, task notifications, and evidence graph metadata into a deterministic dashboard payload.",
                evidence_paths=(
                    "app/backend/services/case_workbench_payload.py",
                    "app/backend/tests/test_case_workbench_payload.py",
                    "docs/CASE_WORKBENCH_PAYLOAD.md",
                ),
                release_gate_links=("case-workbench-payload", "case-evidence-graph", "matter-intake-readiness-policy"),
                user_need_ids=("case-workbench", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="document-delivery-package-manifest",
                title="Document delivery package manifest",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Adds metadata-only checks for documents, source support, missing facts, lawyer review, client notices, export formats, and version notes before delivery.",
                evidence_paths=(
                    "app/backend/services/document_delivery_package_manifest.py",
                    "app/backend/tests/test_document_delivery_package_manifest.py",
                    "docs/DOCUMENT_DELIVERY_PACKAGE_MANIFEST.md",
                ),
                release_gate_links=("document-delivery-package-manifest", "client-delivery-transparency-policy"),
                user_need_ids=("document-generation", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="case-role-permission-matrix",
                title="Case role permission matrix",
                category="safety",
                size="large",
                status="shipped",
                impact="Defines privacy-safe allow, deny, and approval-required decisions for case roles across read, write, export, share, billing, audit, and review operations.",
                evidence_paths=(
                    "app/backend/services/case_role_permission_matrix.py",
                    "app/backend/tests/test_case_role_permission_matrix.py",
                    "docs/CASE_ROLE_PERMISSION_MATRIX.md",
                ),
                release_gate_links=("case-role-permission-matrix", "case-team-access-policy"),
                user_need_ids=("case-workbench", "safe-ai-ops"),
            ),
            LedgerEntry(
                id="billing-usage-quota-policy",
                title="Billing usage quota policy",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Adds local plan limits, review credits, upload quotas, generated document quotas, premium escalation gates, and privacy-safe usage aggregation.",
                evidence_paths=(
                    "app/backend/services/billing_usage_quota_policy.py",
                    "app/backend/tests/test_billing_usage_quota_policy.py",
                    "docs/BILLING_USAGE_QUOTA_POLICY.md",
                ),
                release_gate_links=("billing-usage-quota-policy", "billing-entitlement-gap"),
                user_need_ids=("billing-entitlements", "low-cost-routing"),
            ),
            LedgerEntry(
                id="feedback-lifecycle-policy",
                title="Feedback lifecycle policy",
                category="maintenance",
                size="large",
                status="shipped",
                impact="Defines feedback states from intake through triage, roadmap linkage, release validation, customer-visible resolution, and closure.",
                evidence_paths=(
                    "app/backend/services/feedback_lifecycle_policy.py",
                    "app/backend/tests/test_feedback_lifecycle_policy.py",
                    "docs/FEEDBACK_LIFECYCLE_POLICY.md",
                ),
                release_gate_links=("feedback-lifecycle-policy", "feedback-roadmap-alignment"),
                user_need_ids=("reviewer-visibility", "product-readiness"),
            ),
            LedgerEntry(
                id="contract-clause-extraction-schema",
                title="Contract clause extraction schema",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Defines supported contract clause types, required metadata fields, missing-clause flags, source anchors, and lawyer-review gates for clause-level review.",
                evidence_paths=(
                    "app/backend/services/contract_clause_extraction_schema.py",
                    "app/backend/tests/test_contract_clause_extraction_schema.py",
                    "docs/CONTRACT_CLAUSE_EXTRACTION_SCHEMA.md",
                ),
                release_gate_links=("contract-clause-extraction-schema", "legal-review-benchmark"),
                user_need_ids=("grounded-legal-output", "document-generation"),
            ),
            LedgerEntry(
                id="document-version-diff-checklist",
                title="Document version diff checklist",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Adds client-safe metadata checks for generated document version ids, changed sections, change summaries, reviewer role, and source support before delivery.",
                evidence_paths=(
                    "app/backend/services/document_version_diff_checklist.py",
                    "app/backend/tests/test_document_version_diff_checklist.py",
                    "docs/DOCUMENT_VERSION_DIFF_CHECKLIST.md",
                ),
                release_gate_links=("document-version-diff-checklist", "document-delivery-package-manifest"),
                user_need_ids=("document-generation", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="case-workbench-ui-binding",
                title="Case workbench UI binding",
                category="frontend_ui",
                size="large",
                status="shipped",
                impact="Binds the case workbench payload contract into the maintenance evidence page with dashboard, section, blocker, and action visibility.",
                evidence_paths=(
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                ),
                release_gate_links=("frontend-typecheck", "case-workbench-payload"),
                user_need_ids=("case-workbench", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-source-ingestion-metadata",
                title="Legal source ingestion metadata",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Defines metadata-only source record schema, jurisdiction, effective date, citation, freshness, dedupe keys, and forbidden fields for legal source ingestion.",
                evidence_paths=(
                    "app/backend/services/legal_source_ingestion_metadata.py",
                    "app/backend/tests/test_legal_source_ingestion_metadata.py",
                    "docs/LEGAL_SOURCE_INGESTION_METADATA.md",
                ),
                release_gate_links=("legal-source-ingestion-metadata", "legal-source-freshness-policy", "legal-rag-evaluation"),
                user_need_ids=("grounded-legal-output",),
            ),
            LedgerEntry(
                id="billing-quota-persistence",
                title="Billing quota persistence",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Defines privacy-safe usage counter schema, aggregation buckets, retention, idempotency keys, and over-limit reason persistence before database migrations.",
                evidence_paths=(
                    "app/backend/services/billing_quota_persistence_plan.py",
                    "app/backend/tests/test_billing_quota_persistence_plan.py",
                    "docs/BILLING_QUOTA_PERSISTENCE_PLAN.md",
                ),
                release_gate_links=("billing-quota-persistence-plan", "billing-usage-quota-policy", "billing-entitlement-gap"),
                user_need_ids=("billing-entitlements", "low-cost-routing"),
            ),
            LedgerEntry(
                id="case-workbench-persistence-plan",
                title="Case workbench persistent state",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Defines privacy-safe case workbench state schema, event validation, repository method contracts, retention buckets, and forbidden raw content fields before durable storage.",
                evidence_paths=(
                    "app/backend/services/case_workbench_persistence_plan.py",
                    "app/backend/tests/test_case_workbench_persistence_plan.py",
                    "docs/CASE_WORKBENCH_PERSISTENCE_PLAN.md",
                ),
                release_gate_links=("case-workbench-persistence-plan", "case-workbench-payload"),
                user_need_ids=("case-workbench",),
            ),
            LedgerEntry(
                id="legal-source-durable-index-plan",
                title="Legal source durable index",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Defines metadata-only source index entries, jurisdiction and freshness filters, dedupe keys, rebuild policy, and forbidden raw text/vector fields before durable retrieval storage.",
                evidence_paths=(
                    "app/backend/services/legal_source_durable_index_plan.py",
                    "app/backend/tests/test_legal_source_durable_index_plan.py",
                    "docs/LEGAL_SOURCE_DURABLE_INDEX_PLAN.md",
                ),
                release_gate_links=("legal-source-durable-index-plan", "legal-source-ingestion-metadata", "legal-source-freshness-policy"),
                user_need_ids=("grounded-legal-output",),
            ),
            LedgerEntry(
                id="billing-quota-migration-plan",
                title="Billing quota migration plan",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Maps quota counter schema into migration tables, unique constraints, idempotency replay, rollback checks, and privacy-safe sample migration validation.",
                evidence_paths=(
                    "app/backend/services/billing_quota_migration_plan.py",
                    "app/backend/tests/test_billing_quota_migration_plan.py",
                    "docs/BILLING_QUOTA_MIGRATION_PLAN.md",
                ),
                release_gate_links=("billing-quota-migration-plan", "billing-quota-persistence-plan"),
                user_need_ids=("billing-entitlements",),
            ),
            LedgerEntry(
                id="case-workbench-repository-implementation",
                title="Case workbench repository implementation",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Implements validated async SQLAlchemy state and event repositories for case workbench section state, with event hash replay protection and user-scoped reads.",
                evidence_paths=(
                    "app/backend/models/case_workbench_section_states.py",
                    "app/backend/models/case_workbench_state_events.py",
                    "app/backend/services/case_workbench_state_repository.py",
                    "app/backend/tests/test_case_workbench_state_repository.py",
                    "app/backend/alembic/versions/b7a2c9d4e6f1_repository_persistence_indexes.py",
                ),
                release_gate_links=("case-workbench-state-repository", "case-workbench-persistence-plan"),
                user_need_ids=("case-workbench",),
            ),
            LedgerEntry(
                id="legal-source-index-repository",
                title="Legal source index repository",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Implements metadata-only async SQLAlchemy legal source index persistence and validated query filters for jurisdiction, freshness, source type, and citation lookup.",
                evidence_paths=(
                    "app/backend/models/legal_source_index_entries.py",
                    "app/backend/services/legal_source_index_repository.py",
                    "app/backend/tests/test_legal_source_index_repository.py",
                    "app/backend/alembic/versions/b7a2c9d4e6f1_repository_persistence_indexes.py",
                ),
                release_gate_links=("legal-source-index-repository", "legal-source-durable-index-plan"),
                user_need_ids=("grounded-legal-output",),
            ),
            LedgerEntry(
                id="billing-quota-repository-implementation",
                title="Billing quota repository implementation",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Implements privacy-safe quota counter and idempotency repositories with source-event dedupe, no raw billing payloads, and aggregate usage snapshots.",
                evidence_paths=(
                    "app/backend/models/billing_quota_usage_counters.py",
                    "app/backend/models/billing_quota_idempotency_keys.py",
                    "app/backend/services/billing_quota_repository.py",
                    "app/backend/tests/test_billing_quota_repository.py",
                    "app/backend/alembic/versions/b7a2c9d4e6f1_repository_persistence_indexes.py",
                ),
                release_gate_links=("billing-quota-repository", "billing-quota-migration-plan"),
                user_need_ids=("billing-entitlements",),
            ),
            LedgerEntry(
                id="case-workbench-runtime-binding",
                title="Case workbench runtime binding",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Adds an API-ready facade for repository-backed case workbench state payloads, section event application, idempotent replay, and audit-trail serialization.",
                evidence_paths=(
                    "app/backend/services/case_workbench_runtime_binding.py",
                    "app/backend/tests/test_case_workbench_runtime_binding.py",
                    "app/backend/services/case_workbench_state_repository.py",
                ),
                release_gate_links=("case-workbench-runtime-binding", "case-workbench-state-repository"),
                user_need_ids=("case-workbench", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-rag-query-index-binding",
                title="Legal RAG query index binding",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Binds legal RAG source selection to the durable metadata index, filters stale or missing sources, and builds evaluation payloads from fixture source IDs.",
                evidence_paths=(
                    "app/backend/services/legal_rag_index_binding.py",
                    "app/backend/tests/test_legal_rag_index_binding.py",
                    "app/backend/services/legal_source_index_repository.py",
                    "app/backend/services/legal_rag_evaluation.py",
                ),
                release_gate_links=("legal-rag-index-binding", "legal-source-index-repository", "legal-rag-evaluation"),
                user_need_ids=("grounded-legal-output",),
            ),
            LedgerEntry(
                id="billing-entitlement-repository-binding",
                title="Billing entitlement repository binding",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Combines entitlement plan limits with persisted quota snapshots and idempotent report usage events using opaque quota subject hashes.",
                evidence_paths=(
                    "app/backend/services/billing_entitlement_quota_binding.py",
                    "app/backend/tests/test_billing_entitlement_quota_binding.py",
                    "app/backend/services/billing_quota_repository.py",
                    "app/backend/services/entitlements.py",
                ),
                release_gate_links=("billing-entitlement-quota-binding", "billing-quota-repository", "billing-usage-quota-policy"),
                user_need_ids=("billing-entitlements", "low-cost-routing"),
            ),
            LedgerEntry(
                id="case-workbench-runtime-router",
                title="Case workbench runtime router",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Exposes repository-backed case workbench state payloads, state events, and audit trails through authenticated case routes with path/body case binding checks.",
                evidence_paths=(
                    "app/backend/routers/case_workbench_runtime.py",
                    "app/backend/tests/test_case_workbench_runtime_router.py",
                    "app/backend/services/case_workbench_runtime_binding.py",
                ),
                release_gate_links=("case-workbench-runtime-router", "case-workbench-runtime-binding"),
                user_need_ids=("case-workbench", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-rag-index-route",
                title="Legal RAG index route",
                category="benchmark",
                size="large",
                status="shipped",
                impact="Exposes durable-index retrieval plans and legal RAG evaluation payloads through metadata-only research routes that suppress raw claim and PII details.",
                evidence_paths=(
                    "app/backend/routers/legal_rag.py",
                    "app/backend/tests/test_legal_rag_router.py",
                    "app/backend/services/legal_rag_index_binding.py",
                ),
                release_gate_links=("legal-rag-index-route", "legal-rag-index-binding"),
                user_need_ids=("grounded-legal-output",),
            ),
            LedgerEntry(
                id="billing-quota-consumption-route",
                title="Billing quota consumption route",
                category="product_planning",
                size="large",
                status="shipped",
                impact="Adds authenticated billing usage summary and report-consumption routes backed by persisted quota counters and opaque quota subject hashes.",
                evidence_paths=(
                    "app/backend/routers/billing_usage.py",
                    "app/backend/tests/test_billing_usage_router.py",
                    "app/backend/services/billing_entitlement_quota_binding.py",
                ),
                release_gate_links=("billing-quota-consumption-route", "billing-entitlement-quota-binding"),
                user_need_ids=("billing-entitlements", "low-cost-routing"),
            ),
            LedgerEntry(
                id="frontend-runtime-api-client-bindings",
                title="Frontend runtime API client bindings",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Adds typed frontend API helpers for case workbench runtime state, legal RAG retrieval/evaluation, and billing usage summaries before page-level UI integration.",
                evidence_paths=(
                    "app/frontend/src/lib/workbenchRuntimeApi.ts",
                    "app/frontend/src/lib/legalRagApi.ts",
                    "app/frontend/src/lib/billingUsageApi.ts",
                ),
                release_gate_links=("frontend-typecheck", "case-workbench-runtime-router", "legal-rag-index-route", "billing-quota-consumption-route"),
                user_need_ids=("case-workbench", "grounded-legal-output", "billing-entitlements"),
            ),
            LedgerEntry(
                id="runtime-router-discovery-smoke",
                title="Runtime router discovery smoke",
                category="maintenance",
                size="medium",
                status="shipped",
                impact="Adds a main-app OpenAPI smoke check for case workbench, legal RAG, and billing usage runtime paths before page-level frontend wiring.",
                evidence_paths=(
                    "app/backend/main.py",
                    "app/backend/tests/test_runtime_router_discovery.py",
                    "app/backend/routers/case_workbench_runtime.py",
                    "app/backend/routers/legal_rag.py",
                    "app/backend/routers/billing_usage.py",
                ),
                release_gate_links=(
                    "runtime-router-discovery-smoke",
                    "case-workbench-runtime-router",
                    "legal-rag-index-route",
                    "billing-quota-consumption-route",
                ),
                user_need_ids=("case-workbench", "grounded-legal-output", "billing-entitlements"),
            ),
            LedgerEntry(
                id="case-workbench-frontend-state-events",
                title="Case workbench frontend state events",
                category="frontend_ui",
                size="large",
                status="shipped",
                impact="Surfaces repository-backed workbench state and recent audit events in the case overview, with a lightweight privacy-safe task state event submitter.",
                evidence_paths=(
                    "app/frontend/src/components/cases/CaseWorkbenchRuntimePanel.tsx",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/lib/workbenchRuntimeApi.ts",
                    "app/backend/routers/case_workbench_runtime.py",
                    "app/backend/tests/test_runtime_router_discovery.py",
                ),
                release_gate_links=("frontend-typecheck", "case-workbench-runtime-router", "runtime-router-discovery-smoke"),
                user_need_ids=("case-workbench", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-rag-case-research-ui",
                title="Legal RAG case research UI",
                category="frontend_ui",
                size="large",
                status="shipped",
                impact="Replaces the case research pane with a metadata-only legal RAG evaluation panel showing readiness, source metadata, coverage, and safety counts without raw text or PII.",
                evidence_paths=(
                    "app/frontend/src/components/cases/LegalRagResearchPanel.tsx",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/lib/legalRagApi.ts",
                    "app/backend/routers/legal_rag.py",
                    "app/backend/tests/test_runtime_router_discovery.py",
                ),
                release_gate_links=("frontend-typecheck", "legal-rag-index-route", "runtime-router-discovery-smoke"),
                user_need_ids=("grounded-legal-output",),
            ),
            LedgerEntry(
                id="billing-usage-workspace-badge",
                title="Billing usage workspace badge",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Surfaces the authenticated billing usage summary in the global layout on desktop and mobile, including plan, quota, and allow/block state.",
                evidence_paths=(
                    "app/frontend/src/components/billing/BillingUsageBadge.tsx",
                    "app/frontend/src/components/Layout.tsx",
                    "app/frontend/src/lib/billingUsageApi.ts",
                    "app/backend/routers/billing_usage.py",
                    "app/backend/tests/test_runtime_router_discovery.py",
                ),
                release_gate_links=("frontend-typecheck", "billing-quota-consumption-route", "runtime-router-discovery-smoke"),
                user_need_ids=("billing-entitlements", "low-cost-routing"),
            ),
            LedgerEntry(
                id="billing-report-preflight-route",
                title="Billing report preflight route",
                category="product_planning",
                size="medium",
                status="shipped",
                impact="Adds a non-mutating report quota preflight endpoint that returns allow/block decisions without writing quota counters or idempotency records.",
                evidence_paths=(
                    "app/backend/routers/billing_usage.py",
                    "app/backend/tests/test_billing_usage_router.py",
                    "app/backend/services/billing_entitlement_quota_binding.py",
                ),
                release_gate_links=("billing-report-preflight-route", "billing-quota-consumption-route"),
                user_need_ids=("billing-entitlements", "low-cost-routing"),
            ),
            LedgerEntry(
                id="case-edit-runtime-event-binding",
                title="Case edit runtime event binding",
                category="frontend_ui",
                size="large",
                status="shipped",
                impact="Binds material intake, evidence review, fact updates, task creation, and task status changes to privacy-safe workbench state events that carry refs, counts, and statuses only.",
                evidence_paths=(
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/lib/workbenchRuntimeApi.ts",
                    "app/backend/routers/case_workbench_runtime.py",
                    "app/backend/tests/test_case_workbench_runtime_router.py",
                ),
                release_gate_links=("frontend-typecheck", "case-workbench-frontend-state-events", "case-workbench-runtime-router"),
                user_need_ids=("case-workbench", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-rag-research-context-cache",
                title="Legal RAG research context cache",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Adds metadata-only localStorage summaries, Copy context, and Clear cache controls for case legal RAG research without storing raw legal text, claims, or PII.",
                evidence_paths=(
                    "app/frontend/src/components/cases/LegalRagResearchPanel.tsx",
                    "app/frontend/src/lib/legalRagApi.ts",
                    "app/backend/routers/legal_rag.py",
                ),
                release_gate_links=("frontend-typecheck", "legal-rag-case-research-ui", "legal-rag-index-route"),
                user_need_ids=("grounded-legal-output", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="document-generation-quota-consumption-attempt",
                title="Document generation quota consumption attempt",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Attempts report quota consumption after successful document generation from the case page while leaving full server-side deep-review quota enforcement as future work.",
                evidence_paths=(
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/lib/billingUsageApi.ts",
                    "app/backend/routers/billing_usage.py",
                    "app/backend/tests/test_billing_usage_router.py",
                ),
                release_gate_links=("frontend-typecheck", "billing-quota-consumption-route"),
                user_need_ids=("document-generation", "billing-entitlements", "low-cost-routing"),
            ),
            LedgerEntry(
                id="generated-documents-crud-quota-guard",
                title="Generated documents CRUD quota guard",
                category="backend_api",
                size="medium",
                status="shipped",
                impact="Adds server-side report quota preflight and consumption to the generated_documents create routes with privacy-safe idempotency and batch preflight behavior.",
                evidence_paths=(
                    "app/backend/routers/generated_documents.py",
                    "app/backend/tests/test_generated_documents_quota.py",
                    "app/backend/services/billing_entitlement_quota_binding.py",
                ),
                release_gate_links=("generated-documents-crud-quota-guard", "billing-quota-consumption-route"),
                user_need_ids=("document-generation", "billing-entitlements", "low-cost-routing"),
            ),
            LedgerEntry(
                id="case-generation-quota-guard",
                title="Case generation quota guard",
                category="backend_api",
                size="medium",
                status="shipped",
                impact="Extends report quota consumption to case evidence-catalog and civil-complaint generation before persisting generated documents, with privacy-safe quota events.",
                evidence_paths=(
                    "app/backend/services/case_intelligence.py",
                    "app/backend/routers/case_intelligence.py",
                    "app/backend/tests/test_case_generation_quota.py",
                    "app/backend/services/billing_entitlement_quota_binding.py",
                ),
                release_gate_links=("case-generation-quota-guard", "billing-quota-consumption-route"),
                user_need_ids=("document-generation", "billing-entitlements", "case-workbench"),
            ),
            LedgerEntry(
                id="deep-review-document-generation-quota-guard",
                title="Deep-review document generation quota guard",
                category="backend_api",
                size="medium",
                status="shipped",
                impact="Consumes report quota before /api/v1/deep-review/generate-document performs first-principles AI drafting, blocks exhausted users with HTTP 402, and stores only privacy-safe quota event metadata.",
                evidence_paths=(
                    "app/backend/services/deep_review_document_quota.py",
                    "app/backend/routers/deep_review.py",
                    "app/backend/tests/test_deep_review_document_quota.py",
                    "app/backend/services/billing_entitlement_quota_binding.py",
                ),
                release_gate_links=("deep-review-document-generation-quota-guard", "billing-quota-consumption-route"),
                user_need_ids=("document-generation", "billing-entitlements", "low-cost-routing"),
            ),
            LedgerEntry(
                id="legal-rag-selected-source-request-metadata",
                title="Legal RAG selected-source request metadata",
                category="full_stack",
                size="medium",
                status="shipped",
                impact="Propagates selected Legal RAG source IDs through case AI, document generation request metadata, generation plans, and citation maps without legal text, user claims, or PII.",
                evidence_paths=(
                    "app/frontend/src/components/cases/LegalRagResearchPanel.tsx",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/lib/caseApi.ts",
                    "app/backend/services/legal_rag_request_metadata.py",
                    "app/backend/tests/test_legal_rag_request_metadata.py",
                ),
                release_gate_links=("frontend-typecheck", "legal-rag-selected-source-request-metadata"),
                user_need_ids=("grounded-legal-output", "case-workbench", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-rag-selected-source-citation-validation",
                title="Legal RAG selected-source citation validation",
                category="backend_api",
                size="medium",
                status="shipped",
                impact="Adds deterministic validation that generated citation maps and generation plans cite only selected Legal RAG source IDs, with stale/unknown/missing source reason codes and no raw text echo.",
                evidence_paths=(
                    "app/backend/services/legal_rag_selected_source_validation.py",
                    "app/backend/tests/test_legal_rag_selected_source_validation.py",
                ),
                release_gate_links=("legal-rag-selected-source-citation-validation", "legal-rag-selected-source-request-metadata"),
                user_need_ids=("grounded-legal-output", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-rag-selected-source-validation-maintenance-route",
                title="Legal RAG selected-source validation maintenance route",
                category="backend_api",
                size="medium",
                status="shipped",
                impact="Exposes a metadata-only maintenance self-check route for selected-source citation validation, covering pass, stale, unknown, unexpected, missing, and privacy non-echo cases.",
                evidence_paths=(
                    "app/backend/routers/maintenance.py",
                    "app/backend/tests/test_maintenance_legal_rag_selected_source_validation_route.py",
                    "app/backend/services/legal_rag_selected_source_validation.py",
                ),
                release_gate_links=("legal-rag-selected-source-citation-validation",),
                user_need_ids=("grounded-legal-output", "reviewer-visibility", "product-readiness"),
            ),
            LedgerEntry(
                id="billing-payment-reconciliation-policy",
                title="Billing payment reconciliation policy",
                category="backend_api",
                size="medium",
                status="shipped",
                impact="Adds a local-only payment, invoice, and plan-change reconciliation policy that uses hashed references and does not verify real provider settlement.",
                evidence_paths=(
                    "app/backend/services/billing_payment_reconciliation.py",
                    "app/backend/tests/test_billing_payment_reconciliation.py",
                ),
                release_gate_links=("billing-payment-reconciliation-policy",),
                user_need_ids=("billing-entitlements", "product-readiness"),
            ),
            LedgerEntry(
                id="case-task-runtime-notification-summary",
                title="Case task runtime notification summary",
                category="backend_api",
                size="medium",
                status="shipped",
                impact="Summarizes task runtime events into notification and escalation policy suggestions without dispatching notifications or storing message bodies.",
                evidence_paths=(
                    "app/backend/services/case_task_notification_policy.py",
                    "app/backend/tests/test_case_task_notification_policy.py",
                ),
                release_gate_links=("case-task-runtime-notification-summary", "case-task-notification-policy"),
                user_need_ids=("case-workbench", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="legal-document-benchmark-suite",
                title="Legal document benchmark suite",
                category="benchmark",
                size="medium",
                status="shipped",
                impact="Adds three deterministic laptop-safe legal document fixture checks for structure, citations, PII exclusion, and risk labels without model calls or dataset downloads.",
                evidence_paths=(
                    "app/backend/services/legal_document_benchmark_suite.py",
                    "app/backend/tests/test_legal_document_benchmark_suite.py",
                ),
                release_gate_links=("legal-document-benchmark-suite", "legal-review-benchmark"),
                user_need_ids=("grounded-legal-output", "low-resource-testing"),
            ),
            LedgerEntry(
                id="legal-benchmark-research-registry",
                title="Legal benchmark research registry",
                category="benchmark",
                size="medium",
                status="shipped",
                impact="Maps LegalBench, LexGLUE, and COLIEE lessons into local synthetic, low-resource legal validation strategy without dataset downloads or leaderboard claims.",
                evidence_paths=(
                    "app/backend/services/legal_benchmark_research_registry.py",
                    "app/backend/tests/test_legal_benchmark_research_registry.py",
                    "app/backend/routers/maintenance.py",
                ),
                release_gate_links=("legal-benchmark-research-registry", "legal-review-benchmark"),
                user_need_ids=("grounded-legal-output", "low-resource-testing", "product-readiness"),
            ),
            LedgerEntry(
                id="legal-benchmark-research-registry-ui",
                title="Legal benchmark research registry UI",
                category="frontend_ui",
                size="medium",
                status="shipped",
                impact="Adds a maintenance evidence page section and typed API client for the metadata-only LegalBench, LexGLUE, and COLIEE research registry without benchmark download or score claims.",
                evidence_paths=(
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                    "app/backend/services/legal_benchmark_research_registry.py",
                ),
                release_gate_links=("legal-benchmark-research-registry-ui", "frontend-typecheck"),
                user_need_ids=("low-resource-testing", "product-readiness", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="deep-review-selected-source-binding",
                title="Deep-review selected-source binding",
                category="backend_api",
                size="medium",
                status="shipped",
                impact="Binds selected-source citation validation into deep-review report metadata and delivery blockers without echoing raw legal text, claims, or PII.",
                evidence_paths=(
                    "app/backend/services/deep_review_selected_source_binding.py",
                    "app/backend/tests/test_deep_review_selected_source_binding.py",
                    "app/backend/routers/maintenance.py",
                ),
                release_gate_links=("deep-review-selected-source-binding", "legal-rag-selected-source-citation-validation"),
                user_need_ids=("grounded-legal-output", "reviewer-visibility", "document-generation"),
            ),
            LedgerEntry(
                id="quota-delivery-decision",
                title="Quota delivery decision",
                category="backend_api",
                size="medium",
                status="shipped",
                impact="Converts sanitized quota and release metadata into export, client-delivery, and account-plan review decisions.",
                evidence_paths=(
                    "app/backend/services/quota_delivery_decision.py",
                    "app/backend/tests/test_quota_delivery_decision.py",
                    "app/backend/routers/maintenance.py",
                ),
                release_gate_links=("quota-delivery-decision", "deep-review-document-generation-quota-guard"),
                user_need_ids=("billing-entitlements", "document-generation", "product-readiness"),
            ),
            LedgerEntry(
                id="feedback-issue-cluster",
                title="Feedback issue cluster",
                category="user_research",
                size="medium",
                status="shipped",
                impact="Clusters repeated feedback and defect themes with deterministic local rules, safe evidence refs, user segment tags, and no raw PII echo.",
                evidence_paths=(
                    "app/backend/services/feedback_issue_cluster.py",
                    "app/backend/tests/test_feedback_issue_cluster.py",
                    "app/backend/routers/maintenance.py",
                ),
                release_gate_links=("feedback-issue-cluster", "feedback-lifecycle-policy"),
                user_need_ids=("feedback-loop", "product-readiness"),
            ),
            LedgerEntry(
                id="evidence-bundle-integrity",
                title="Evidence bundle integrity",
                category="backend_api",
                size="medium",
                status="shipped",
                impact="Checks evidence bundles for duplicates, missing sources, missing proof purposes, date/amount/checksum gaps, and sensitive metadata without reading files or model calls.",
                evidence_paths=(
                    "app/backend/services/evidence_bundle_integrity.py",
                    "app/backend/tests/test_evidence_bundle_integrity.py",
                    "app/backend/routers/maintenance.py",
                ),
                release_gate_links=("evidence-bundle-integrity", "evidence-exhibit-package-policy"),
                user_need_ids=("evidence-management", "case-workbench"),
            ),
            LedgerEntry(
                id="privacy-retention-rules",
                title="Privacy retention rules",
                category="safety",
                size="medium",
                status="shipped",
                impact="Maps legal artifacts to retention windows, deletion triggers, and reviewer confirmation rules without raw legal text or PII.",
                evidence_paths=(
                    "app/backend/services/privacy_retention_rules.py",
                    "app/backend/tests/test_privacy_retention_rules.py",
                    "app/backend/routers/maintenance.py",
                ),
                release_gate_links=("privacy-retention-rules", "privacy-redaction"),
                user_need_ids=("safety-compliance", "product-readiness"),
            ),
            LedgerEntry(
                id="release-claim-compliance",
                title="Release claim compliance",
                category="safety",
                size="medium",
                status="shipped",
                impact="Blocks unsupported public claims about adoption, benchmark scores, payment settlement, production accuracy, or third-party PR volume using hash-only claim checks.",
                evidence_paths=(
                    "app/backend/services/release_claim_compliance.py",
                    "app/backend/tests/test_release_claim_compliance.py",
                    "app/backend/routers/maintenance.py",
                ),
                release_gate_links=("release-claim-compliance", "oss-maintenance-evidence"),
                user_need_ids=("safety-compliance", "product-readiness"),
            ),
            LedgerEntry(
                id="case-export-readiness",
                title="Case export readiness",
                category="backend_api",
                size="medium",
                status="shipped",
                impact="Checks report section completeness, release blockers, and selected-source validation before export without echoing report text.",
                evidence_paths=(
                    "app/backend/services/case_export_readiness.py",
                    "app/backend/tests/test_case_export_readiness.py",
                    "app/backend/routers/maintenance.py",
                ),
                release_gate_links=("case-export-readiness", "deep-review-selected-source-binding"),
                user_need_ids=("document-generation", "case-workbench", "reviewer-visibility"),
            ),
            LedgerEntry(
                id="admin-audit-policy",
                title="Admin audit policy",
                category="safety",
                size="medium",
                status="shipped",
                impact="Evaluates sensitive admin actions for approval and audit requirements while excluding raw payloads and PII.",
                evidence_paths=(
                    "app/backend/services/admin_audit_policy.py",
                    "app/backend/tests/test_admin_audit_policy.py",
                    "app/backend/routers/maintenance.py",
                ),
                release_gate_links=("admin-audit-policy", "case-role-permission-matrix"),
                user_need_ids=("safety-compliance", "permissions-team"),
            ),
        ]
