from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Literal


Language = Literal["en", "zh"]


REPOSITORY_URL = "https://github.com/lixinglongye/xiaolvshi"


@dataclass(frozen=True)
class MaintenanceSignal:
    id: str
    category: str
    title: str
    description: str
    responsibility: str
    cadence: str
    evidence_paths: tuple[str, ...]
    weight: int

    def to_api(self) -> dict:
        data = asdict(self)
        data["evidence_paths"] = list(self.evidence_paths)
        return data


class MaintenanceEvidenceService:
    """Builds application-safe OSS maintenance evidence for this project."""

    def build_profile(self, language: Language = "en") -> dict:
        language = self._normalize_language(language)
        signals = self._signals()

        return {
            "project": {
                "name": "xiaolvshi",
                "display_name": "律审雷达",
                "repository_url": REPOSITORY_URL,
                "domain": "Legal document review, case material organization, and litigation preparation",
            },
            "maintainer_role": "primary_project_maintainer",
            "evidence_score": self._evidence_score(signals),
            "active_maintenance_summary": self._summary(language),
            "form_answer": self.build_form_answer(language),
            "signals": [signal.to_api() for signal in signals],
            "responsibilities": self._responsibilities(signals),
            "release_management": {
                "current_stage": "active_pre_release_development",
                "release_readiness_controls": [
                    "Deep-review quality gate",
                    "Citation audit",
                    "Evidence audit",
                    "Risk scoring",
                    "Unified release decision",
                    "Model configuration audit",
                    "Model default optimization",
                    "Model default recommendation snapshot",
                    "Model default ladder review boundaries",
                    "Gemini/NewAPI cheap-first policy",
                    "Gemini/NewAPI model selector",
                    "Gemini/NewAPI observed model extraction",
                    "Gemini/NewAPI extractor rejection taxonomy",
                    "Gemini/NewAPI model alias matrix",
                    "Gemini/NewAPI alias capability coverage",
                    "Gemini official preview alias review",
                    "Gemini/NewAPI selector replay",
                    "Gemini/NewAPI cheap-first calibration",
                    "Gemini model variant matrix",
                    "ModelOps Gemini variant review form",
                    "Gemini model-list ingestion",
                    "Gemini catalog source audit",
                    "Gemini and gateway price refresh monitor",
                    "Model cost regression snapshots",
                    "Model gateway compatibility",
                    "Model gateway connection profile",
                    "Model gateway runtime configuration",
                    "Route telemetry repository",
                    "Route telemetry catalog cost estimation",
                    "Runtime route reason codes",
                    "Route telemetry operations summary",
                    "Route telemetry triage queue",
                    "Route telemetry reason-code hotspots",
                    "Route telemetry remediation plan",
                    "Model operations readiness",
                    "Model operations readiness warning drilldown",
                    "ModelOps cheap-first release decision",
                    "ModelOps user-need release bridge",
                    "ModelOps default change queue",
                    "ModelOps cheap-first canary plan",
                    "ModelOps cheap-first canary observation review",
                    "ModelOps cheap-first canary promotion decision",
                    "ModelOps cheap-first canary approval packet",
                    "ModelOps cheap-first canary rollback drill",
                    "ModelOps cheap-first canary change manifest",
                    "ModelOps Gemini cheap-first coverage gate",
                    "ModelOps Gemini cheap-first route preflight",
                    "ModelOps AIHub endpoint route coverage gate",
                    "ModelOps runtime explicit model fit gate",
                    "ModelOps legal micro benchmark preflight",
                    "ModelOps legal fixture cheap-first benchmark gate",
                    "ModelOps legal fixture cheap-first default promotion packet",
                    "ModelOps agentic grounded defaults",
                    "ModelOps default template alignment audit",
                    "ModelOps Gemini default change proposal review",
                    "ModelOps Gemini default cost impact forecast",
                    "ModelOps observed Gemini model intake queue",
                    "ModelOps observed Gemini coverage gap queue",
                    "ModelOps observed Gemini premium exception review",
                    "Model catalog candidate patch plan",
                    "ModelOps load performance budget",
                    "ModelOps performance observation review",
                    "Cheap-first route quality budget",
                    "ModelOps cheap-first escalation budget",
                    "Model failure upgrade budget",
                    "Case workbench payload contract",
                "Model route guardrails",
                "Gemini reasoning effort policy",
                "Generation request parameter policy",
                "Model request cost bounds",
                "Model cache policy",
                "Continuous update ledger",
                "Continuous ledger low-resource fixture evidence",
                "Maintenance heartbeat evidence",
                "Continuous session evidence validator",
                "Continuous session timeline",
                "Continuous session run monitor",
                "Continuous run monitor fixture evidence",
                "Continuous session review packet",
                "Continuous session low-resource fixture review",
                "Git history cadence evidence",
                "Validation event evidence normalizer",
                "Case team access policy",
                "Case role permission matrix",
                "Document delivery package manifest",
                "Document version diff checklist",
                "Client delivery risk checklist",
                "Legal document template matrix",
                "Legal document export readiness",
                "OCR import readiness policy",
                "Case timeline deadline risk",
                "Deadline validation policy",
                "Matter intake readiness policy",
                "Matter audit retention policy",
                "Lawyer review workflow policy",
                "Evidence exhibit package policy",
                "Case task notification policy",
                "Client delivery transparency policy",
                "Legal document benchmark fixtures",
                "Contract clause extraction schema",
                "Small legal document corpus expansion",
                "Legal RAG failure fixtures",
                "Legal source freshness policy",
                "Legal source ingestion metadata",
                "Legal source durable index plan",
                "Legal source index repository",
                "Legal RAG index binding",
                "Legal RAG index route",
                "Billing usage quota policy",
                "Billing quota persistence plan",
                "Billing quota migration plan",
                "Billing quota repository",
                "Billing entitlement quota binding",
                "Billing quota consumption route",
                "Billing report preflight route",
                "Case access control runtime gate",
                "Case workbench persistence plan",
                "Case workbench state repository",
                "Case workbench runtime binding",
                "Case workbench runtime router",
                "Case workbench risk refresh plan",
                "Frontend runtime API client bindings",
                "Case edit runtime event binding",
                "Case export readiness download gate",
                "Legal RAG research context cache",
                "Document generation quota consumption attempt",
                "Generated documents CRUD quota guard",
                "Case generation quota guard",
                "Case evidence catalog export preflight",
                "Deep-review document generation quota guard",
                "Legal RAG selected-source request metadata",
                "Legal RAG selected-source citation validation",
                "Legal RAG selected-source validation maintenance route",
                "Deep-review selected-source binding",
                "Quota delivery decision",
                "Feedback issue cluster",
                "Evidence bundle integrity",
                "Privacy retention rules",
                "Release claim compliance",
                "Case export readiness",
                "Admin audit policy",
                "Billing payment reconciliation policy",
                "Case task runtime notification summary",
                    "Legal document benchmark suite",
                    "Legal document benchmark gap fixtures",
                    "Legal document benchmark coverage matrix",
                    "Legal document fact consistency benchmark",
                    "Legal document coverage claim policy",
                "User need public benchmark mapping",
                "User need cheap-first calibration mapping",
                "Legal benchmark research registry UI",
                "Legal benchmark research refresh",
                "Model route legal benchmark risk queue",
                "Observed gateway model fit matrix",
                "User need implementation priority queue",
                "User need Gemini route coverage",
                "Legal RAG authority citation gate",
                "Legal RAG hallucination triage gate",
                "Legal RAG abstention escalation gate",
                "Legal RAG retrieval diagnostics gate",
                "Legal RAG index coverage gate",
                "Legal RAG embedding readiness gate",
                "Legal RAG embedding chunk policy gate",
                "Legal RAG embedding index dry-run gate",
                "Legal RAG embedding batch budget gate",
                "Legal RAG embedding batch approval packet",
                "Legal RAG embedding batch observation gate",
                "Legal RAG embedding index commit review packet",
                "Legal RAG embedding index post-commit verification gate",
                "Legal RAG embedding retrieval diagnostics handoff gate",
                "Legal RAG retrieval observation gate",
                "Legal RAG answer release readiness gate",
                "Legal adoption research bridge",
                "Feedback lifecycle policy",
            ],
                "client_delivery_policy": "Reports are not marked client-deliverable until release_decision allows delivery.",
            },
            "application_guardrails": [
                "Only claim maintenance work that is visible in this repository.",
                "Do not claim external ecosystem adoption without public evidence.",
                "Do not claim third-party PR or issue volume unless GitHub records show it.",
                "Payment evidence is currently local policy only; do not claim real provider settlement, webhook signature verification, or invoice collection until external integration evidence is merged.",
                "Selected-source Legal RAG evidence now includes metadata propagation and citation-map validation; do not claim automatic deep-review report binding until merged evidence exists.",
                "Deep-review selected-source binding exists as metadata evidence; do not claim live report persistence/export integration until it is wired into production flows.",
                "The continuous session evidence validator can review explicit 24-hour metadata, but it does not prove completion unless the submitted events cover the full window.",
                "The continuous session timeline joins metadata evidence for reviewers, but support claims must remain blocked until real timestamped events prove the full 24-hour window.",
                "The continuous session run monitor shows active-run gaps, checkpoints, blockers, and next actions, but it is not proof that the 24-hour window is complete.",
                "The continuous run monitor fixture evidence is archive-safe and non-mutating; it cannot replace real timestamped 24-hour events or update-count evidence.",
                "The continuous session review packet is a metadata-only index with blockers, review questions, and a stable hash; it is not a substitute for real timestamped 24-hour evidence.",
                "Git history cadence evidence can show commit windows and gaps, but it does not prove tests, pushes, credential scans, low-resource fixture runs, or release review by itself.",
                "Validation event evidence accepts only sanitized test, credential-scan, push, release-review, and legal fixture metadata; raw logs, legal text, model output, credentials, and emails stay out of the support claim.",
                "Generated document CRUD, case generation, and deep-review first-principles generation are quota guarded; quota delivery decisions exist as metadata evidence but do not prove real payment provider settlement or universal cross-endpoint quota coverage.",
                "The legal document coverage claim policy allows only repository-backed synthetic fixture wording and blocks broad, real-client, public-benchmark, unsupported-document, or sensitive-material claims.",
                "The user-need public benchmark mapping reports sampler and license-review metadata only; it does not claim public benchmark scores, dataset downloads, or external legal text validation.",
                "The user-need cheap-first calibration mapping reports task IDs, status, release gates, and decisions only; it does not claim live NewAPI execution or echo calibration payloads.",
                "The legal benchmark research refresh is metadata-only maintenance evidence; it does not download datasets, claim public benchmark scores, store external legal text, call models, or handle credentials.",
                "The model route legal benchmark risk queue is metadata-only route review evidence; it does not call gateways, write model routes, download datasets, claim public benchmark scores, store raw legal text, or handle credentials.",
                "The user-need implementation priority queue is metadata-only planning evidence; it joins high-priority user needs, legal benchmark coverage gaps, cheap-first calibration/model routing risk, and product execution actions without downloading public datasets, calling NewAPI, Gemini, OpenAI, Google, gateways, or the network, writing real env values, or storing raw legal text, prompts, payloads, model outputs, or credentials.",
                "The ModelOps user-need release bridge is metadata-only default-review evidence; it joins user-need implementation planning with Gemini route coverage so high-priority implementation or route blockers can block default changes while public benchmark license, premium exception, partial coverage, route-hint calibration, and medium/low implementation gaps stay maintainer-review only without downloading datasets, calling NewAPI, Gemini, OpenAI, Google, gateways, or the network, writing configuration, shifting traffic, or storing raw legal text, benchmark samples, prompts, payloads, model outputs, emails, identifiers, or credentials.",
                "The Legal RAG authority citation gate is metadata-only authority and citation evidence; it does not call NewAPI, Gemini, or gateways, download datasets, store raw legal text, prompts, model outputs, or credentials.",
                "The Legal RAG hallucination triage gate is metadata-only triage evidence; it does not call NewAPI, Gemini, or gateways, download datasets, store raw legal text, retrieved snippets, prompts, model outputs, or credentials.",
                "The Legal RAG abstention escalation gate is metadata-only answer-routing evidence; it does not call models, gateways, or the network, download datasets, store fixture questions, dangerous answers, raw retrieved context, raw legal text, prompts, model outputs, or credentials.",
                "The Legal RAG retrieval diagnostics gate is metadata-only retrieval evidence for query intent, authority coverage, top-k depth, jurisdiction/freshness, citation gaps, retrieval gaps, cheap-first defaults, and premium-exception boundaries; it does not call models, gateways, or the network, download datasets, store raw query, raw retrieved context, raw legal text, prompts, model outputs, or credentials.",
                "The Legal RAG embedding readiness gate is metadata-only Gemini embedding and Legal RAG index-readiness evidence; it links cheap-first text embedding defaults, multimodal embedding review boundaries, index coverage blockers, and retrieval diagnostics without calling NewAPI, Gemini, models, gateways, or the network, writing indexes, downloading datasets, storing or returning source ids, raw query, raw retrieved context, raw legal text, embedding vectors, prompts, model outputs, gateway payloads, or credentials.",
                "The Legal RAG embedding chunk policy gate is metadata-only chunk planning evidence for cheap Gemini Legal RAG embeddings; it links token estimates, source-type split strategies, citation anchors, retrieval locators, freshness, embedding readiness, durable index planning, and ingestion metadata without calling NewAPI, Gemini, models, gateways, or the network, creating embeddings, writing indexes, downloading datasets, storing or returning source ids, raw query, raw retrieved context, raw legal text, source chunks, embedding vectors, prompts, model outputs, gateway payloads, or credentials.",
                "The Legal RAG embedding index dry-run gate is metadata-only manifest evidence before any embedding index write; it links chunk-policy rows, planned vector-slot counts, durable index persistence fields, repository validation, and commit-action blockers without calling NewAPI, Gemini, models, gateways, or the network, creating embeddings, writing indexes or databases, downloading datasets, storing or returning source ids, raw query, raw retrieved context, raw legal text, source chunks, embedding vectors, prompts, model outputs, gateway payloads, or credentials.",
                "The Legal RAG embedding batch budget gate is metadata-only cheap Gemini batch-budget evidence before any embedding run; it links dry-run manifest rows, planned batch counts, laptop-safe chunk and token limits, local catalog batch-cost estimates, and release-action blockers without calling NewAPI, Gemini, models, gateways, or the network, creating embeddings, writing indexes or databases, downloading datasets, storing or returning source ids, raw query, raw retrieved context, raw legal text, source chunks, embedding vectors, prompts, model outputs, gateway payloads, credentials, or live pricing claims.",
                "The Legal RAG embedding batch approval packet is metadata-only maintainer review evidence before any embedding run; it links batch-budget rows, serial low-resource queue order, max_parallel_embedding_requests=1, required maintainer/RAG-index reviewer roles, pre-approval checks, and advance/hold/block actions without claiming approval, collecting approver identity, writing approval records, calling NewAPI, Gemini, models, gateways, or the network, creating embeddings, writing indexes or databases, downloading datasets, storing or returning source ids, raw query, raw retrieved context, raw legal text, source chunks, embedding vectors, prompts, model outputs, gateway payloads, credentials, or live pricing claims.",
                "The Legal RAG embedding batch observation gate is metadata-only aggregate observation evidence after an external embedding batch run; it links sanitized observed batch/chunk/vector-slot/token counts, cost deltas, max_parallel_embedding_requests=1, and index-review actions without claiming maintainer approval, executing embeddings, calling NewAPI, Gemini, models, gateways, or the network, writing indexes or databases, collecting approver identity, downloading datasets, storing or returning source ids, approval item ids, raw query, raw retrieved context, raw legal text, source chunks, embedding vectors, prompts, model outputs, gateway payloads, credentials, or live pricing claims.",
                "The Legal RAG embedding index commit review packet is metadata-only maintainer review evidence before any embedding index commit; it links ready aggregate observations, vector-slot match evidence, observed chunk/cost evidence, required maintainer/RAG-index/privacy signoffs, pre-commit checks, and prepare/hold/block actions without claiming commit approval, executing embeddings, calling NewAPI, Gemini, models, gateways, or the network, writing indexes or databases, writing commit records, collecting committer identity, downloading datasets, storing or returning source ids, approval item ids, raw query, raw retrieved context, raw legal text, source chunks, embedding vectors, prompts, model outputs, gateway payloads, credentials, or live pricing claims.",
                "The Legal RAG embedding index post-commit verification gate is metadata-only observation evidence after external index commit review; it links expected/observed vector slots, index entry counts, metadata records, retrieval locators, checksum records, failed-entry totals, rollback signals, and retrieval-diagnostics review actions without claiming commit approval, executing embeddings, calling NewAPI, Gemini, models, gateways, or the network, writing indexes or databases, writing commit records, enabling production retrieval, collecting committer identity, downloading datasets, storing or returning source ids, approval item ids, raw query, raw retrieved context, raw legal text, source chunks, embedding vectors, prompts, model outputs, gateway payloads, credentials, or live pricing claims.",
                "The Legal RAG embedding retrieval diagnostics handoff gate is metadata-only handoff evidence between post-commit verification and retrieval diagnostics; it links ready/hold/block handoff rows, safe handoff payload fields, diagnostics-review-only actions, rollback review links, and production-retrieval false flags without executing retrieval diagnostics, enabling production retrieval, claiming index or retrieval quality, executing embeddings, calling NewAPI, Gemini, models, gateways, or the network, writing indexes or databases, writing commit records, collecting committer identity, downloading datasets, storing or returning source ids, raw query, user questions, raw retrieved context, raw legal text, source chunks, embedding vectors, prompts, model outputs, gateway payloads, credentials, or live pricing claims.",
                "The Legal RAG retrieval observation gate is metadata-only local retrieval observation evidence for selected-source citation validation counts, source coverage, top-k depth, jurisdiction/freshness, cheap-first routing decisions, and answer-release actions; it does not call NewAPI, Gemini, models, gateways, or the network, download datasets, store or return source ids, raw query, raw retrieved context, raw legal text, prompts, model outputs, or credentials.",
                "The Legal RAG answer release readiness gate is metadata-only answer-release evidence for converting sanitized retrieval observations into ready/review/block rows, internal draft actions, citation packet requirements, lawyer-review requirements, cheap-first verify/escalate boundaries, and client-delivery false flags without calling NewAPI, Gemini, models, gateways, or the network, writing answers, sending client delivery, claiming legal advice or answer quality, downloading datasets, storing or returning source ids, raw query, user questions, raw retrieved context, raw legal text, prompts, model outputs, gateway payloads, or credentials.",
                "The ModelOps cheap-first canary rollback drill is rehearsal metadata only; it does not execute rollback, write configuration, persist drill state, call gateways, or shift traffic.",
                "The ModelOps cheap-first canary change manifest is proposed-change metadata only; it does not write configuration, store secret values, call gateways, shift traffic, or record approver identity.",
                "The ModelOps Gemini cheap-first coverage gate is metadata-only coverage evidence; it does not call NewAPI, Gemini, OpenAI, Google, gateways, or the network, and it does not return raw prompts, payloads, model outputs, or credentials.",
                "The ModelOps Gemini cheap-first route preflight is metadata-only route review evidence; it joins official source refresh notes, local task defaults, variant review states, alias capability coverage, and coverage-gate status without NewAPI, Gemini, OpenAI, Google, gateway, app-AI, or network calls, configuration writes, traffic shifts, request or response bodies, headers, prompts, raw payloads, legal text, model outputs, gateway responses, credentials, emails, or user identifiers.",
                "The ModelOps AIHub endpoint route coverage gate is metadata-only endpoint wiring evidence; it inventories runtime-router coverage, budget-decision coverage, route telemetry coverage, response route-payload coverage, and media/speech catalog review gaps without NewAPI, Gemini, OpenAI, Google, gateway, app-AI, model, or network calls, configuration writes, traffic shifts, request or response bodies, headers, prompts, raw payloads, legal text, model outputs, gateway responses, credentials, emails, or user identifiers.",
                "The ModelOps runtime explicit model fit gate is metadata-only runtime route evidence; it runs sanitized task/model scenarios through local routing to surface unknown gateway guards, reviewed gateway pass-through exceptions, explicit over-budget exceptions, local downgrades, cheap-first alignment, and observed gateway fit review states without NewAPI, Gemini, OpenAI, Google, gateway, app-AI, model, or network calls, configuration writes, default changes, traffic shifts, request or response bodies, headers, messages, prompts, raw payloads, legal text, model outputs, gateway responses, credentials, emails, or user identifiers.",
                "The Model gateway connection profile is metadata-only OpenAI-compatible URL-shape evidence; it normalizes remote bare NewAPI/Gemini hosts to /v1, blocks credential-bearing URL claims, and reports key presence with placeholders only without calling NewAPI, Gemini, OpenAI, Google, gateway, app-AI, model, or network endpoints, writing configuration, shifting traffic, or including API keys, Authorization headers, request or response bodies, prompts, raw payloads, legal text, model outputs, gateway responses, emails, or user identifiers.",
                "The Model gateway runtime configuration evidence checks APP_AI_BASE_URL normalization, APP_AI_KEY placeholder use, cheap-first Gemini role defaults, and safe probe ordering before live gateway use without writing env files, changing defaults, shifting traffic, calling NewAPI, Gemini, OpenAI, Google, yibuapi, gateways, app-AI, model, or network endpoints, or including API keys, Authorization headers, request/response bodies, prompts, raw legal text, model outputs, gateway responses, credentials, emails, or user identifiers.",
                "The observed gateway model fit matrix is metadata-only inventory fit evidence; it maps sanitized NewAPI/Gemini/OpenAI-compatible model-list ids to cheap-first task capabilities, lowest-cost observed candidates, missing task coverage, and review-only Pro/preview/image/unknown/external/unpriced boundaries without calling NewAPI, Gemini, OpenAI, Google, gateway, app-AI, model, or network endpoints, validating account inventory, writing configuration, changing defaults, shifting traffic, or including API keys, Authorization headers, request or response bodies, prompts, raw payloads, legal text, model outputs, gateway responses, emails, or user identifiers.",
                "The ModelOps legal micro benchmark preflight is metadata-only low-resource legal benchmark run-planning evidence using fixture ids, document case ids, fact-consistency case ids, serial run order, cost estimates, and follow-up gate bindings only; it does not call NewAPI, Gemini, OpenAI, Google, gateways, app AI endpoints, or the network, write configuration, shift traffic, or include request bodies, messages, prompts, fixture excerpts, legal text, generated document text, model outputs, gateway responses, credentials, or emails.",
                "The Gemini/NewAPI model alias matrix is metadata-only alias evidence; it maps sanitized model ids to canonical catalog ids, cheap-first eligibility, premium/manual review boundaries, and unknown-model review states without calling NewAPI, Gemini, OpenAI, Google, gateways, or the network, writing configuration, shifting traffic, or storing raw payloads, prompts, legal text, model outputs, credentials, or emails.",
                "The Gemini/NewAPI observed model extraction evidence is metadata-only parsing evidence for OpenAI-compatible /models responses, Gemini native model-list wrappers, gateway probe rows, and intake queue rows; it returns sanitized model ids, source field names, counts, sensitive/invalid/total rejection counts, and no raw rejected values, without NewAPI, Gemini, OpenAI, Google, gateway, or network calls, raw payload echoing, prompts, legal text, model outputs, emails, headers, or credentials.",
                "The Gemini/NewAPI alias capability coverage evidence maps sanitized alias ids to local catalog capabilities, task coverage, cheap-first eligibility, and explicit-review boundaries without calling NewAPI, Gemini, OpenAI, Google, gateways, or the network, writing configuration, shifting traffic, or storing raw payloads, prompts, legal text, model outputs, emails, or credentials.",
                "The Legal document fact consistency benchmark is metadata-only amount/date/fact consistency evidence using structured synthetic expectations, case ids, counts, and reason codes only; it does not call NewAPI, Gemini, OpenAI, Google, gateways, or the network, download datasets, store raw legal text, prompts, generated document text, raw model output, credentials, or client identifiers.",
                "The legal document benchmark fixture UI renders synthetic fixture ids, document types, expected-check counts, field keys, snippet lengths, scoring state, resource policy, and validation commands only; it deliberately does not render raw fixture snippets, prompts, model responses, gateway payloads, credentials, emails, or client material.",
                "The ModelOps legal fixture cheap-first benchmark gate is metadata-only small legal-document benchmark/risk evidence using redacted fixture ids, document case ids, fact-consistency case ids, linked cheap-first calibration task ids, calibration decisions, release gates, expected issue tags, amount/date/fact consistency counts, cost metadata, and escalation metadata only; it does not call NewAPI, Gemini, OpenAI, Google, gateways, or the network, and it does not include real legal text, prompts, calibration payloads, model outputs, credentials, or emails.",
                "The ModelOps legal fixture cheap-first default promotion packet is metadata-only maintainer review evidence; it joins gate, document benchmark, fact-consistency, and cheap-first calibration metadata without writing configuration, calling NewAPI, Gemini, OpenAI, Google, gateways, or the network, shifting traffic, or including real legal text, fixture snippets, generated document text, prompts, calibration payloads, model outputs, credentials, or emails.",
                "The ModelOps agentic grounded defaults evidence is metadata-only/default routing evidence; it does not call NewAPI, Gemini, OpenAI, Google, gateways, or the network, write real environment values, or include raw prompts, payloads, model outputs, or credentials.",
                "The ModelOps default template alignment audit is metadata-only env/template evidence for Settings defaults, app/backend/.env.example, the README env block, and docs/AI_MODEL_STRATEGY; it does not call NewAPI, Gemini, OpenAI, Google, gateways, or the network, write real environment values, or include raw prompts, payloads, model outputs, or credentials.",
                "The ModelOps Gemini default change proposal review is metadata-only proposal evidence for cost tier, lifecycle, capabilities, gateway compatibility, and premium/manual review boundary checks before a new Gemini default variant is applied; it does not call NewAPI, Gemini, OpenAI, Google, gateways, or the network, write real environment values, or include raw prompts, payloads, model outputs, or credentials.",
                "The ModelOps Gemini default cost impact forecast is metadata-only cost evidence for estimated monthly cost delta, cheap-first savings or regression, unknown pricing, and premium exception/manual review boundary checks before a new Gemini default variant is applied; it does not call NewAPI, Gemini, OpenAI, Google, gateways, or the network, write real environment values, or include raw prompts, payloads, model outputs, or credentials.",
                "The ModelOps observed Gemini model intake queue is metadata-only intake evidence for OpenAI-compatible gateway /models or manually observed Gemini-like model ids, known/unknown status, price, lifecycle, cost tier, cheap-first eligibility, and default-promotion block/review/ready state; it does not call NewAPI, Gemini, OpenAI, Google, gateways, or the network, write real environment values, or include raw prompts, payloads, model outputs, or credentials.",
                "The ModelOps observed Gemini premium exception review is metadata-only premium-route evidence for Pro or premium Gemini variants, explicit-only premium routes, high-frequency default blocks, and no automatic configuration changes; it does not call NewAPI, Gemini, OpenAI, Google, gateways, or the network, write real environment values, shift traffic, or include raw prompts, payloads, model outputs, legal text, emails, or credentials.",
                "The ModelOps readiness warning drilldown is metadata-only warning triage evidence; it classifies existing readiness warnings by review category, priority, next action, and validation hint without calling NewAPI, Gemini, OpenAI, Google, gateways, or the network, and without returning raw payloads, prompts, model outputs, credentials, or legal text.",
                "The model catalog candidate patch plan is metadata-only catalog maintenance evidence for sanitized observed Gemini-like model ids; it does not edit model_catalog.py, write configuration, call NewAPI, Gemini, OpenAI, Google, gateways, or the network, shift traffic, or include raw payloads, prompts, legal text, model outputs, credentials, or emails.",
                "Human maintainer must confirm ownership and final form attestations before submission.",
            ],
        }

    def build_form_answer(self, language: Language = "en") -> str:
        language = self._normalize_language(language)
        if language == "zh":
            return (
                "我是 xiaolvshi 项目的维护者，仓库地址为 "
                f"{REPOSITORY_URL}。该项目正在持续维护，目前包含 FastAPI 后端、React/Vite "
                "前端、本地法律知识库、文件处理、深度审查流水线、自动化测试和维护文档。"
                "近期维护内容包括 Gemini/NewAPI 模型路由与预算策略、确定性风险评分、报告质量门禁、"
                "引用审计、证据审计，以及法律深度审查报告的统一交付决策流程。"
                "我持续负责发布就绪检查、质量控制、测试覆盖、文档更新和问题分级处理，使该项目作为"
                "可维护的开源法律审查工具持续演进，而不是一次性演示项目。"
            )

        return (
            "I am the maintainer of the xiaolvshi project: "
            f"{REPOSITORY_URL}. The repository is under active development and includes a FastAPI "
            "backend, React/Vite frontend, local legal knowledge base, file processing, deep-review "
            "pipeline, automated tests, and maintenance documentation. Recent maintenance work includes "
            "Gemini/NewAPI model routing and budget policy, deterministic risk scoring, report quality "
            "gates, citation auditing, evidence auditing, and a unified release decision workflow for "
            "legal deep-review reports. I actively handle release readiness, quality checks, test coverage, "
            "documentation updates, and issue-style triage logic so the project can be maintained as a usable "
            "open-source legal review tool rather than a one-time demo."
        )

    def _signals(self) -> list[MaintenanceSignal]:
        return [
            MaintenanceSignal(
                id="model-routing-cost-control",
                category="model_ops",
                title="Cost-aware Gemini/NewAPI routing",
                description="OpenAI-compatible gateway routing prefers cheaper Gemini models for routine tasks and keeps defaults pinned to stable lifecycle-safe models with safe gateway connection profile evidence, runtime gateway configuration evidence, observed gateway model fit matrix evidence, runtime explicit model fit gate evidence, safe gateway health planning, model selector audits, default ladder review-boundary evidence, Gemini/NewAPI observed model extraction evidence, Gemini/NewAPI extractor rejection taxonomy evidence, Gemini/NewAPI model alias matrix evidence, Gemini/NewAPI alias capability coverage evidence, Gemini official preview alias review evidence, selector replay evidence, cheap-first calibration, Gemini variant matrix review, sanitized ModelOps Gemini variant review, sanitized gateway model-list ingestion, Gemini catalog source audit, model catalog candidate patch planning, ModelOps readiness warning drilldown evidence, ModelOps cheap-first release decision review, ModelOps user-need release bridge review, ModelOps default change queue review, ModelOps cheap-first canary plan review, ModelOps cheap-first canary observation review, ModelOps cheap-first canary promotion decision review, ModelOps cheap-first canary approval packet review, ModelOps cheap-first canary rollback drill review, ModelOps cheap-first canary change manifest review, ModelOps Gemini cheap-first coverage gate review, ModelOps Gemini cheap-first route preflight review, ModelOps AIHub endpoint route coverage gate review, ModelOps runtime explicit model fit gate review, ModelOps legal micro benchmark preflight review, ModelOps legal fixture cheap-first benchmark gate review, ModelOps legal fixture cheap-first default promotion packet review, ModelOps agentic/grounded default routing evidence, ModelOps default template alignment audit evidence, ModelOps Gemini default change proposal review evidence, ModelOps Gemini default cost impact forecast evidence, ModelOps observed Gemini model intake queue evidence, ModelOps observed Gemini coverage gap evidence, ModelOps observed Gemini premium exception review evidence, ModelOps load performance budgets, sanitized ModelOps performance observation review, cheap-first route quality budgets, cheap-first escalation budget review, model failure upgrade budget review, legal benchmark route risk queue review, sanitized ModelOps calibration review, public benchmark research mappings, default recommendation snapshots, price-refresh monitoring, cost regression snapshots, route telemetry persistence planning, privacy-safe route telemetry repository evidence, catalog-priced route telemetry cost estimation, runtime route reason-code evidence, runtime explicit model fit review states, AIHub endpoint runtime-router and route telemetry coverage evidence, route telemetry reason-code hotspot evidence, route telemetry operations summary checks, route telemetry triage actions, route telemetry remediation plans, and sanitized probe evaluation.",
                responsibility="Model catalog maintenance, catalog source-audit review, model catalog candidate patch-plan review, budget policy review, task-level selector review, model default ladder review-boundary review, Gemini/NewAPI observed model extraction review, observed gateway model fit matrix review, runtime gateway configuration review, runtime explicit model fit gate review, Gemini/NewAPI extractor rejection taxonomy review, Gemini/NewAPI alias matrix review, Gemini/NewAPI alias capability coverage review, Gemini official preview alias review, selector replay review, cheap-first calibration and sanitized review-form upkeep, legal benchmark route risk queue review, Gemini variant matrix review, gateway model-list ingestion review, gateway connection profile review, ModelOps readiness warning triage review, ModelOps cheap-first release decision review, ModelOps user-need release bridge review, ModelOps default change queue review, ModelOps cheap-first canary plan review, ModelOps cheap-first canary observation review, ModelOps cheap-first canary promotion decision review, ModelOps cheap-first canary approval packet review, ModelOps cheap-first canary rollback drill review, ModelOps cheap-first canary change manifest review, ModelOps Gemini cheap-first coverage gate review, ModelOps Gemini cheap-first route preflight review, ModelOps AIHub endpoint route coverage gate review, ModelOps runtime explicit model fit gate review, ModelOps legal micro benchmark preflight review, ModelOps legal fixture cheap-first benchmark gate review, ModelOps legal fixture cheap-first default promotion packet review, ModelOps agentic/grounded defaults review, ModelOps default template alignment audit review, ModelOps Gemini default change proposal review, ModelOps Gemini default cost impact forecast review, ModelOps observed Gemini model intake queue review, ModelOps observed Gemini coverage gap review, ModelOps observed Gemini premium exception review, ModelOps performance-budget review, ModelOps performance-observation review, route quality-budget review, escalation-budget review, model failure-upgrade budget review, AIHub endpoint runtime-router coverage review, runtime explicit model fit review, AIHub route telemetry coverage review, observed-model form upkeep, public benchmark mapping review, default recommendation review, price-refresh review, cost regression review, route telemetry privacy review, route telemetry repository review, route telemetry catalog cost-estimation review, runtime route reason-code review, route telemetry reason-code hotspot review, route telemetry operations summary review, route telemetry triage review, route telemetry remediation review, gateway compatibility updates, gateway health-plan review, sanitized probe evaluation, and Gemini lifecycle policy review.",
                cadence="Review when gateway model names, pricing, or task defaults change.",
                evidence_paths=(
                    "app/backend/services/model_catalog.py",
                    "app/backend/services/model_budget.py",
                    "app/backend/services/model_capability_matrix.py",
                    "app/backend/services/model_default_candidate_selector.py",
                    "app/backend/services/model_configuration_audit.py",
                    "app/backend/services/model_default_optimization.py",
                    "app/backend/services/model_default_recommendation_snapshot.py",
                    "app/backend/services/gemini_newapi_cheap_first_policy.py",
                    "app/backend/services/gemini_newapi_observed_model_extraction.py",
                    "app/backend/services/gemini_newapi_model_selector.py",
                    "app/backend/services/gemini_newapi_model_alias_matrix.py",
                    "app/backend/services/gemini_newapi_alias_capability_coverage.py",
                    "app/backend/services/gemini_newapi_selector_replay.py",
                    "app/backend/services/gemini_newapi_cheap_first_calibration.py",
                    "app/backend/services/gemini_model_variant_matrix.py",
                    "app/backend/services/model_ops_observed_gemini_coverage_gap_queue.py",
                    "app/backend/services/model_ops_observed_gemini_premium_exception_review.py",
                    "app/backend/services/model_price_refresh_monitor.py",
                    "app/backend/services/model_cost_regression_snapshots.py",
                    "app/backend/services/route_telemetry_persistence_plan.py",
                    "app/backend/services/route_telemetry_repository.py",
                    "app/backend/services/model_usage.py",
                    "app/backend/services/route_telemetry_ops_summary.py",
                    "app/backend/services/route_telemetry_triage_queue.py",
                    "app/backend/services/route_telemetry_remediation_plan.py",
                    "app/backend/services/model_gateway_compatibility.py",
                    "app/backend/services/model_gateway_connection_profile.py",
                    "app/backend/services/model_gateway_runtime_configuration.py",
                    "app/backend/services/model_gateway_health_plan.py",
                    "app/backend/services/model_gateway_probe_evaluation.py",
                    "app/backend/services/model_lifecycle_policy.py",
                    "app/backend/services/model_ops_readiness.py",
                    "app/backend/services/model_ops_cheap_first_escalation_budget.py",
                    "app/backend/services/model_failure_upgrade_budget.py",
                    "app/backend/services/model_ops_cheap_first_release_decision.py",
                    "app/backend/services/model_ops_user_need_release_bridge.py",
                    "app/backend/services/model_ops_default_change_queue.py",
                    "app/backend/services/model_ops_cheap_first_canary_plan.py",
                    "app/backend/services/model_ops_cheap_first_canary_observation.py",
                    "app/backend/services/model_ops_cheap_first_canary_promotion_decision.py",
                    "app/backend/services/model_ops_cheap_first_canary_approval_packet.py",
                    "app/backend/services/model_ops_cheap_first_canary_rollback_drill.py",
                    "app/backend/services/model_ops_cheap_first_canary_change_manifest.py",
                    "app/backend/services/modelops_gemini_cheap_first_coverage_gate.py",
                    "app/backend/services/model_ops_gemini_cheap_first_route_preflight.py",
                    "app/backend/services/model_ops_aihub_endpoint_route_coverage_gate.py",
                    "app/backend/services/model_ops_runtime_explicit_model_fit_gate.py",
                    "app/backend/services/modelops_observed_gateway_model_fit_matrix.py",
                    "app/backend/services/modelops_legal_micro_benchmark_preflight.py",
                    "app/backend/services/modelops_legal_fixture_cheap_first_benchmark_gate.py",
                    "app/backend/services/modelops_legal_fixture_default_promotion_packet.py",
                    "app/backend/services/model_catalog_candidate_patch_plan.py",
                    "app/backend/routers/maintenance.py",
                    "app/backend/.env.example",
                    "README.md",
                    "app/backend/services/release_readiness.py",
                    "app/backend/services/continuous_update_ledger.py",
                    "app/backend/services/maintenance_evidence.py",
                    "app/backend/services/model_catalog_source_audit.py",
                    "app/backend/services/model_ops_performance_budget.py",
                    "app/backend/services/model_route_quality_budget.py",
                    "app/backend/services/model_route_legal_benchmark_risk_queue.py",
                    "app/backend/services/model_runtime_router.py",
                    "app/backend/services/model_reasoning_policy.py",
                    "app/backend/services/model_request_policy.py",
                    "app/backend/services/model_request_cost_bounds.py",
                    "app/backend/services/model_cache_policy.py",
                    "app/backend/services/model_route_telemetry.py",
                    "app/backend/services/model_route_guardrails.py",
                    "app/backend/services/model_task_inference.py",
                    "app/backend/services/model_callsite_audit.py",
                    "app/backend/services/model_escalation_policy.py",
                    "app/backend/services/model_cost_forecast.py",
                    "app/backend/services/model_cost_guardrails.py",
                    "app/backend/services/model_routing_replay.py",
                    "app/backend/services/model_fallback_chains.py",
                    "app/backend/tests/test_model_catalog.py",
                    "app/backend/tests/test_model_capability_matrix.py",
                    "app/backend/tests/test_model_default_candidate_selector.py",
                    "app/backend/tests/test_model_configuration_audit.py",
                    "app/backend/tests/test_model_default_optimization.py",
                    "app/backend/tests/test_model_default_recommendation_snapshot.py",
                    "app/backend/tests/test_gemini_newapi_cheap_first_policy.py",
                    "app/backend/tests/test_gemini_newapi_observed_model_extraction.py",
                    "app/backend/tests/test_gemini_newapi_model_selector.py",
                    "app/backend/tests/test_gemini_newapi_model_alias_matrix.py",
                    "app/backend/tests/test_gemini_newapi_alias_capability_coverage.py",
                    "app/backend/tests/test_gemini_newapi_selector_replay.py",
                    "app/backend/tests/test_gemini_newapi_cheap_first_calibration.py",
                    "app/backend/tests/test_gemini_model_variant_matrix.py",
                    "app/backend/tests/test_model_ops_observed_gemini_coverage_gap_queue.py",
                    "app/backend/tests/test_model_ops_observed_gemini_premium_exception_review.py",
                    "app/backend/tests/test_modelops_legal_micro_benchmark_preflight.py",
                    "app/frontend/src/lib/modelOpsApi.ts",
                    "app/frontend/src/pages/ModelOpsPage.tsx",
                    "docs/GEMINI_NEWAPI_CHEAP_FIRST_CALIBRATION.md",
                    "docs/GEMINI_MODEL_VARIANT_MATRIX.md",
                    "docs/MODELOPS_GEMINI_CHEAP_FIRST_ROUTE_PREFLIGHT.md",
                    "docs/MODELOPS_AIHUB_ENDPOINT_ROUTE_COVERAGE_GATE.md",
                    "docs/MODELOPS_RUNTIME_EXPLICIT_MODEL_FIT_GATE.md",
                    "docs/MODELOPS_OBSERVED_GATEWAY_MODEL_FIT_MATRIX.md",
                    "docs/MODELOPS_OBSERVED_GEMINI_COVERAGE_GAP_QUEUE.md",
                    "docs/MODELOPS_OBSERVED_GEMINI_PREMIUM_EXCEPTION_REVIEW.md",
                    "app/backend/tests/test_model_price_refresh_monitor.py",
                    "app/backend/tests/test_model_cost_regression_snapshots.py",
                    "app/backend/tests/test_route_telemetry_persistence_plan.py",
                    "app/backend/tests/test_route_telemetry_repository.py",
                    "app/backend/tests/test_route_telemetry_ops_summary.py",
                    "app/backend/tests/test_route_telemetry_triage_queue.py",
                    "app/backend/tests/test_route_telemetry_remediation_plan.py",
                    "docs/ROUTE_TELEMETRY_OPS_SUMMARY.md",
                    "docs/ROUTE_TELEMETRY_TRIAGE_QUEUE.md",
                    "docs/ROUTE_TELEMETRY_REMEDIATION_PLAN.md",
                    "app/backend/tests/test_model_gateway_compatibility.py",
                    "app/backend/tests/test_model_gateway_runtime_configuration.py",
                    "app/backend/tests/test_model_gateway_health_plan.py",
                    "app/backend/tests/test_model_gateway_probe_evaluation.py",
                    "app/backend/tests/test_model_lifecycle_policy.py",
                    "app/backend/tests/test_model_ops_readiness.py",
                    "app/backend/tests/test_model_ops_cheap_first_escalation_budget.py",
                    "app/backend/tests/test_model_failure_upgrade_budget.py",
                    "app/backend/tests/test_model_ops_cheap_first_release_decision.py",
                    "app/backend/tests/test_model_ops_user_need_release_bridge.py",
                    "app/backend/tests/test_model_ops_default_change_queue.py",
                    "app/backend/tests/test_model_ops_cheap_first_canary_plan.py",
                    "app/backend/tests/test_model_ops_cheap_first_canary_observation.py",
                    "app/backend/tests/test_model_ops_cheap_first_canary_promotion_decision.py",
                    "app/backend/tests/test_model_ops_cheap_first_canary_approval_packet.py",
                    "app/backend/tests/test_model_ops_cheap_first_canary_rollback_drill.py",
                    "app/backend/tests/test_model_ops_cheap_first_canary_change_manifest.py",
                    "app/backend/tests/test_modelops_gemini_cheap_first_coverage_gate.py",
                    "app/backend/tests/test_model_ops_gemini_cheap_first_route_preflight.py",
                    "app/backend/tests/test_model_ops_aihub_endpoint_route_coverage_gate.py",
                    "app/backend/tests/test_model_ops_runtime_explicit_model_fit_gate.py",
                    "app/backend/tests/test_modelops_observed_gateway_model_fit_matrix.py",
                    "app/backend/tests/test_modelops_legal_fixture_cheap_first_benchmark_gate.py",
                    "app/backend/tests/test_modelops_legal_fixture_default_promotion_packet.py",
                    "app/backend/tests/test_model_catalog_candidate_patch_plan.py",
                    "app/backend/tests/test_release_readiness.py",
                    "app/backend/tests/test_continuous_update_ledger.py",
                    "app/backend/tests/test_maintenance_evidence.py",
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                    "app/frontend/scripts/ui-regression.mjs",
                    "app/backend/tests/test_model_catalog_source_audit.py",
                    "app/backend/tests/test_model_ops_performance_budget.py",
                    "app/backend/tests/test_model_route_quality_budget.py",
                    "app/backend/tests/test_model_route_legal_benchmark_risk_queue.py",
                    "app/backend/tests/test_model_runtime_router.py",
                    "app/backend/tests/test_model_reasoning_policy.py",
                    "app/backend/tests/test_model_request_policy.py",
                    "app/backend/tests/test_model_request_cost_bounds.py",
                    "app/backend/tests/test_model_cache_policy.py",
                    "app/backend/tests/test_model_route_telemetry.py",
                    "app/backend/tests/test_model_route_guardrails.py",
                    "app/backend/tests/test_aihub_runtime_routing.py",
                    "app/backend/tests/test_model_task_inference.py",
                    "app/backend/tests/test_model_callsite_audit.py",
                    "app/backend/tests/test_model_escalation_policy.py",
                    "app/backend/tests/test_model_cost_forecast.py",
                    "app/backend/tests/test_model_cost_guardrails.py",
                    "app/backend/tests/test_model_routing_replay.py",
                    "app/backend/tests/test_model_fallback_chains.py",
                    "docs/AI_MODEL_STRATEGY.md",
                    "docs/MODEL_CONFIGURATION_AUDIT.md",
                    "docs/MODEL_DEFAULT_OPTIMIZATION.md",
                    "docs/MODEL_DEFAULT_RECOMMENDATION_SNAPSHOT.md",
                    "docs/GEMINI_NEWAPI_CHEAP_FIRST_POLICY.md",
                    "docs/GEMINI_NEWAPI_MODEL_SELECTOR.md",
                    "docs/GEMINI_NEWAPI_MODEL_ALIAS_MATRIX.md",
                    "docs/GEMINI_NEWAPI_ALIAS_CAPABILITY_COVERAGE.md",
                    "docs/GEMINI_NEWAPI_SELECTOR_REPLAY.md",
                    "docs/MODELOPS_OBSERVED_GATEWAY_MODEL_FIT_MATRIX.md",
                    "docs/MODELOPS_RUNTIME_EXPLICIT_MODEL_FIT_GATE.md",
                    "docs/MODELOPS_OBSERVED_GEMINI_COVERAGE_GAP_QUEUE.md",
                    "docs/MODEL_PRICE_REFRESH_MONITOR.md",
                    "docs/MODEL_COST_REGRESSION_SNAPSHOTS.md",
                    "docs/ROUTE_TELEMETRY_PERSISTENCE_PLAN.md",
                    "docs/MODEL_GATEWAY_COMPATIBILITY.md",
                    "docs/MODEL_GATEWAY_CONNECTION_PROFILE.md",
                    "docs/MODEL_GATEWAY_RUNTIME_CONFIGURATION.md",
                    "docs/MODEL_GATEWAY_HEALTH_PLAN.md",
                    "docs/MODEL_GATEWAY_PROBE_EVALUATION.md",
                    "docs/MODEL_LIFECYCLE_POLICY.md",
                    "docs/MODEL_OPS_READINESS.md",
                    "docs/MODEL_OPS_CHEAP_FIRST_ESCALATION_BUDGET.md",
                    "docs/MODEL_FAILURE_UPGRADE_BUDGET.md",
                    "docs/MODEL_OPS_CHEAP_FIRST_RELEASE_DECISION.md",
                    "docs/MODEL_OPS_USER_NEED_RELEASE_BRIDGE.md",
                    "docs/MODEL_OPS_DEFAULT_CHANGE_QUEUE.md",
                    "docs/MODEL_OPS_CHEAP_FIRST_CANARY_PLAN.md",
                    "docs/MODEL_OPS_CHEAP_FIRST_CANARY_OBSERVATION.md",
                    "docs/MODEL_OPS_CHEAP_FIRST_CANARY_PROMOTION_DECISION.md",
                    "docs/MODEL_OPS_CHEAP_FIRST_CANARY_APPROVAL_PACKET.md",
                    "docs/MODEL_OPS_CHEAP_FIRST_CANARY_ROLLBACK_DRILL.md",
                    "docs/MODEL_OPS_CHEAP_FIRST_CANARY_CHANGE_MANIFEST.md",
                    "docs/MODELOPS_GEMINI_CHEAP_FIRST_COVERAGE_GATE.md",
                    "docs/MODELOPS_LEGAL_FIXTURE_CHEAP_FIRST_BENCHMARK_GATE.md",
                    "docs/MODELOPS_LEGAL_FIXTURE_DEFAULT_PROMOTION_PACKET.md",
                    "docs/MODEL_CATALOG_CANDIDATE_PATCH_PLAN.md",
                    "docs/CONTINUOUS_UPDATE_LEDGER.md",
                    "docs/MODEL_CATALOG_SOURCE_AUDIT.md",
                    "docs/MODEL_OPS_PERFORMANCE_BUDGET.md",
                    "docs/MODEL_ROUTE_QUALITY_BUDGET.md",
                    "docs/MODEL_ROUTE_LEGAL_BENCHMARK_RISK_QUEUE.md",
                    "docs/MODEL_RUNTIME_ROUTER.md",
                    "docs/MODEL_REASONING_POLICY.md",
                    "docs/MODEL_REQUEST_POLICY.md",
                    "docs/MODEL_REQUEST_COST_BOUNDS.md",
                    "docs/MODEL_CACHE_POLICY.md",
                    "docs/MODEL_ROUTE_TELEMETRY.md",
                    "docs/MODEL_ROUTE_GUARDRAILS.md",
                    "docs/MODEL_TASK_INFERENCE.md",
                    "docs/MODEL_CALLSITE_AUDIT.md",
                    "docs/MODEL_ESCALATION_POLICY.md",
                    "docs/MODEL_COST_FORECAST.md",
                    "docs/MODEL_COST_GUARDRAILS.md",
                    "docs/MODEL_ROUTING_REPLAY.md",
                    "docs/MODEL_FALLBACK_CHAINS.md",
                ),
                weight=15,
            ),
            MaintenanceSignal(
                id="deep-review-quality-gates",
                category="quality",
                title="Deep-review quality gate",
                description="Deterministic gates, legal document template coverage, contract clause extraction schema, export-readiness checks, research-backed legal AI backlog planning, LegalBench/LexGLUE/LegalBench-RAG/LexEval/CaseGen/COLIEE research registry mapping and UI evidence, metadata-only legal benchmark research refresh evidence, public adoption/research bridge mapping, public benchmark sampling plans, quick laptop-safe fixture suites, small legal document benchmark fixtures, deterministic legal document benchmark suite checks, metadata-only legal document fact consistency benchmark evidence, synthetic evidence-catalog/settlement/legal-opinion gap fixtures, metadata-only document coverage matrices, claim-policy checks for legal-document coverage wording, small synthetic corpus expansion, RAG failure fixtures, legal source freshness policy, durable source index planning, metadata-only RAG index binding and route exposure, metadata-only authority/citation gate evidence, metadata-only retrieval diagnostics gate evidence, metadata-only retrieval observation gate evidence, metadata-only research context cache/copy controls, selected-source request metadata propagation and citation validation, selected-source validation maintenance self-checks, deep-review selected-source binding, case export readiness, fixture-level Gemini/NewAPI model matrices, cheap-first fixture prompt packs, safe gateway manifests, laptop-safe fixture run plans, one-at-a-time local run packages, response normalizers, one-step local run reviews, cheap-first run reports, evidence bundles, archive-safe result summaries, fixture smoke tests, and fixture improvement plans verify report structure, grounding, pending-fact handling, disclaimers, fact consistency, and small legal document coverage before review.",
                responsibility="Quality gate tuning, legal template matrix review, contract clause schema review, export-readiness review, research backlog review, benchmark research registry, refresh, and UI review, adoption research bridge review, public benchmark sampler review, document benchmark fixture review, benchmark-suite review, fact-consistency benchmark review, gap-fixture review, coverage-matrix and coverage-claim-policy review, small corpus review, RAG failure fixture review, source freshness, durable-index, RAG-index-binding, authority/citation gate review, retrieval diagnostics gate review, retrieval observation gate review, selected-source metadata, citation validation, deep-review binding, maintenance self-check route, quick-suite review, legal fixture model matrix review, prompt coverage, safe gateway manifest upkeep, fixture run-plan, local-package, response-normalizer, local-run-review, result-archive, run-report, and evidence-bundle maintenance, smoke coverage, prompt/schema improvement planning, regression tests, and release criteria maintenance.",
                cadence="Review whenever report schema, legal source handling, or delivery policy changes.",
                evidence_paths=(
                    "app/backend/services/report_quality_gate.py",
                    "app/backend/services/legal_review_benchmark.py",
                    "app/backend/services/contract_clause_extraction_schema.py",
                    "app/backend/services/legal_document_benchmark_fixtures.py",
                    "app/backend/services/legal_benchmark_research_registry.py",
                    "app/backend/services/legal_benchmark_research_refresh.py",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                    "app/backend/services/legal_document_benchmark_suite.py",
                    "app/backend/services/legal_document_benchmark_coverage.py",
                    "app/backend/services/legal_document_fact_consistency_benchmark.py",
                    "app/backend/services/legal_document_coverage_claim_policy.py",
                    "app/backend/services/small_legal_document_corpus_expansion.py",
                    "app/backend/services/legal_rag_failure_fixtures.py",
                    "app/backend/services/legal_source_ingestion_metadata.py",
                    "app/backend/services/legal_source_freshness_policy.py",
                    "app/backend/services/legal_source_durable_index_plan.py",
                    "app/backend/services/legal_source_index_repository.py",
                    "app/backend/services/legal_rag_index_binding.py",
                    "app/backend/services/legal_rag_authority_citation_gate.py",
                    "app/backend/services/legal_rag_retrieval_diagnostics_gate.py",
                    "app/backend/services/legal_rag_retrieval_observation_gate.py",
                    "app/backend/routers/legal_rag.py",
                    "app/backend/services/legal_rag_request_metadata.py",
                    "app/backend/services/legal_rag_selected_source_validation.py",
                    "app/backend/services/deep_review_selected_source_binding.py",
                    "app/backend/services/case_export_readiness.py",
                    "app/backend/routers/case_intelligence.py",
                    "app/backend/services/case_intelligence.py",
                    "app/backend/services/case_ai_workbench.py",
                    "app/backend/services/legal_external_research_digest.py",
                    "app/backend/services/legal_adoption_research_bridge.py",
                    "app/backend/services/legal_document_export_readiness.py",
                    "app/backend/services/legal_document_template_matrix.py",
                    "app/backend/services/legal_research_backlog.py",
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                    "app/backend/services/legal_public_benchmark_sampler.py",
                    "app/backend/services/legal_fixture_quick_suite.py",
                    "app/backend/services/legal_fixture_model_matrix.py",
                    "app/backend/services/legal_fixture_prompt_pack.py",
                    "app/backend/services/legal_fixture_gateway_manifest.py",
                    "app/backend/services/legal_fixture_run_plan.py",
                    "app/backend/services/legal_fixture_local_run_package.py",
                    "app/backend/services/legal_fixture_response_normalizer.py",
                    "app/backend/services/legal_fixture_local_run_review.py",
                    "app/backend/services/legal_fixture_result_archive.py",
                    "app/backend/services/legal_fixture_run_report.py",
                    "app/backend/services/legal_fixture_evidence_bundle.py",
                    "app/backend/services/legal_fixture_improvement.py",
                    "app/backend/tests/test_report_quality_gate.py",
                    "app/backend/tests/test_legal_review_benchmark.py",
                    "app/backend/tests/test_contract_clause_extraction_schema.py",
                    "app/backend/tests/test_legal_document_benchmark_fixtures.py",
                    "app/backend/tests/test_legal_benchmark_research_registry.py",
                    "app/backend/tests/test_legal_benchmark_research_refresh.py",
                    "app/backend/tests/test_legal_document_benchmark_suite.py",
                    "app/backend/tests/test_legal_document_benchmark_coverage.py",
                    "app/backend/tests/test_legal_document_fact_consistency_benchmark.py",
                    "app/backend/tests/test_legal_document_coverage_claim_policy.py",
                    "app/backend/tests/test_small_legal_document_corpus_expansion.py",
                    "app/backend/tests/test_legal_rag_failure_fixtures.py",
                    "app/backend/tests/test_legal_source_ingestion_metadata.py",
                    "app/backend/tests/test_legal_source_freshness_policy.py",
                    "app/backend/tests/test_legal_source_durable_index_plan.py",
                    "app/backend/tests/test_legal_source_index_repository.py",
                    "app/backend/tests/test_legal_rag_index_binding.py",
                    "app/backend/tests/test_legal_rag_authority_citation_gate.py",
                    "app/backend/tests/test_legal_rag_retrieval_diagnostics_gate.py",
                    "app/backend/tests/test_legal_rag_retrieval_observation_gate.py",
                    "app/backend/tests/test_legal_rag_router.py",
                    "app/backend/tests/test_legal_rag_request_metadata.py",
                    "app/backend/tests/test_legal_rag_selected_source_validation.py",
                    "app/frontend/src/components/cases/LegalRagResearchPanel.tsx",
                    "app/frontend/src/lib/legalRagApi.ts",
                    "app/backend/tests/test_legal_external_research_digest.py",
                    "app/backend/tests/test_legal_adoption_research_bridge.py",
                    "app/backend/tests/test_legal_document_export_readiness.py",
                    "app/backend/tests/test_legal_document_template_matrix.py",
                    "app/backend/tests/test_legal_research_backlog.py",
                    "app/backend/tests/test_legal_public_benchmark_sampler.py",
                    "app/backend/tests/test_legal_fixture_quick_suite.py",
                    "app/backend/tests/test_legal_fixture_model_matrix.py",
                    "app/backend/tests/test_legal_fixture_prompt_pack.py",
                    "app/backend/tests/test_legal_fixture_gateway_manifest.py",
                    "app/backend/tests/test_legal_fixture_run_plan.py",
                    "app/backend/tests/test_legal_fixture_local_run_package.py",
                    "app/backend/tests/test_legal_fixture_response_normalizer.py",
                    "app/backend/tests/test_legal_fixture_local_run_review.py",
                    "app/backend/tests/test_legal_fixture_result_archive.py",
                    "app/backend/tests/test_legal_fixture_run_report.py",
                    "app/backend/tests/test_legal_fixture_evidence_bundle.py",
                    "app/backend/tests/test_legal_fixture_improvement.py",
                    "docs/DEEP_REVIEW_QUALITY_GATES.md",
                    "docs/LEGAL_REVIEW_BENCHMARK.md",
                    "docs/CONTRACT_CLAUSE_EXTRACTION_SCHEMA.md",
                    "docs/LEGAL_DOCUMENT_BENCHMARK_FIXTURES.md",
                    "docs/LEGAL_BENCHMARK_RESEARCH_REFRESH.md",
                    "docs/LEGAL_DOCUMENT_BENCHMARK_COVERAGE.md",
                    "docs/LEGAL_DOCUMENT_FACT_CONSISTENCY_BENCHMARK.md",
                    "docs/LEGAL_DOCUMENT_COVERAGE_CLAIM_POLICY.md",
                    "docs/SMALL_LEGAL_DOCUMENT_CORPUS_EXPANSION.md",
                    "docs/LEGAL_RAG_FAILURE_FIXTURES.md",
                    "docs/LEGAL_SOURCE_INGESTION_METADATA.md",
                    "docs/LEGAL_SOURCE_FRESHNESS_POLICY.md",
                    "docs/LEGAL_SOURCE_DURABLE_INDEX_PLAN.md",
                    "docs/LEGAL_RAG_AUTHORITY_CITATION_GATE.md",
                    "docs/LEGAL_RAG_RETRIEVAL_DIAGNOSTICS_GATE.md",
                    "docs/LEGAL_RAG_RETRIEVAL_OBSERVATION_GATE.md",
                    "docs/LEGAL_EXTERNAL_RESEARCH_DIGEST.md",
                    "docs/LEGAL_ADOPTION_RESEARCH_BRIDGE.md",
                    "docs/LEGAL_DOCUMENT_EXPORT_READINESS.md",
                    "docs/LEGAL_DOCUMENT_TEMPLATE_MATRIX.md",
                    "docs/LEGAL_RESEARCH_BACKLOG.md",
                    "docs/LEGAL_PUBLIC_BENCHMARK_SAMPLER.md",
                    "docs/LEGAL_FIXTURE_QUICK_SUITE.md",
                    "docs/LEGAL_BENCHMARK_FIXTURES.md",
                    "docs/LEGAL_FIXTURE_MODEL_MATRIX.md",
                    "docs/LEGAL_FIXTURE_PROMPT_PACK.md",
                    "docs/LEGAL_FIXTURE_GATEWAY_MANIFEST.md",
                    "docs/LEGAL_FIXTURE_RUN_PLAN.md",
                    "docs/LEGAL_FIXTURE_LOCAL_RUN_PACKAGE.md",
                    "docs/LEGAL_FIXTURE_RESPONSE_NORMALIZER.md",
                    "docs/LEGAL_FIXTURE_LOCAL_RUN_REVIEW.md",
                    "docs/LEGAL_FIXTURE_RESULT_ARCHIVE.md",
                    "docs/LEGAL_FIXTURE_RUN_REPORT.md",
                    "docs/LEGAL_FIXTURE_EVIDENCE_BUNDLE.md",
                    "docs/LEGAL_FIXTURE_IMPROVEMENT.md",
                ),
                weight=15,
            ),
            MaintenanceSignal(
                id="citation-and-evidence-audits",
                category="review_ops",
                title="Citation and evidence audits",
                description="Citation, evidence, source freshness, exhibit package, evidence catalog export preflight, evidence bundle integrity, grounding, case intake, workbench persistence planning, runtime state binding and routes, metadata-only risk refresh planning, privacy-safe case edit runtime events, metadata-only export readiness download gating, selected-source request metadata, matter intake readiness, deadline-risk, deadline validation, delivery-risk, delivery transparency, and graph services flag weak legal authorities, stale sources, duplicate evidence, missing reviewable citations, missing evidence plans, incomplete intake fields, urgent deadlines, missing client disclosures, unsupported legal claims, and blocking pending facts.",
                responsibility="Legal-source freshness review, issue triage, exhibit package review, evidence catalog export preflight review, evidence bundle integrity review, grounding quick-audit review, selected-source metadata review, workbench persistence, runtime-binding, router and risk-refresh-plan review, privacy-safe edit-event review, export-readiness download gate review, intake completeness review, matter-readiness review, deadline-risk and deadline-validation review, client-delivery checklist and transparency review, and evidence completeness checks.",
                cadence="Review when legal knowledge sources, report sections, or risk-item fields change.",
                evidence_paths=(
                    "app/backend/services/citation_audit.py",
                    "app/backend/services/evidence_audit.py",
                    "app/backend/services/evidence_bundle_integrity.py",
                    "app/backend/services/legal_source_freshness_policy.py",
                    "app/backend/services/legal_grounding_quick_audit.py",
                    "app/backend/services/case_evidence_graph.py",
                    "app/backend/services/case_workbench_payload.py",
                    "app/backend/services/case_workbench_persistence_plan.py",
                    "app/backend/services/case_workbench_state_repository.py",
                    "app/backend/services/case_workbench_runtime_binding.py",
                    "app/backend/services/case_workbench_risk_refresh_plan.py",
                    "app/backend/routers/case_workbench_runtime.py",
                    "app/backend/services/legal_rag_request_metadata.py",
                    "app/backend/tests/test_legal_rag_request_metadata.py",
                    "app/backend/services/case_intake_completeness.py",
                    "app/backend/services/matter_intake_readiness_policy.py",
                    "app/backend/services/case_timeline_deadline_risk.py",
                    "app/backend/services/deadline_validation_policy.py",
                    "app/backend/services/client_delivery_risk_checklist.py",
                    "app/backend/services/client_delivery_transparency_policy.py",
                    "app/backend/services/evidence_exhibit_package_policy.py",
                    "app/backend/services/case_evidence_catalog_export_preflight.py",
                    "app/backend/tests/test_citation_audit.py",
                    "app/backend/tests/test_evidence_audit.py",
                    "app/backend/tests/test_legal_source_freshness_policy.py",
                    "app/backend/tests/test_legal_grounding_quick_audit.py",
                    "app/backend/tests/test_case_evidence_graph.py",
                    "app/backend/tests/test_case_workbench_payload.py",
                    "app/backend/tests/test_case_workbench_persistence_plan.py",
                    "app/backend/tests/test_case_workbench_state_repository.py",
                    "app/backend/tests/test_case_workbench_runtime_binding.py",
                    "app/backend/tests/test_case_workbench_risk_refresh_plan.py",
                    "app/backend/tests/test_case_workbench_runtime_router.py",
                    "app/frontend/src/components/cases/CaseWorkbenchRuntimePanel.tsx",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/scripts/ui-regression.mjs",
                    "app/frontend/src/lib/workbenchRuntimeApi.ts",
                    "app/backend/tests/test_case_intake_completeness.py",
                    "app/backend/tests/test_matter_intake_readiness_policy.py",
                    "app/backend/tests/test_case_timeline_deadline_risk.py",
                    "app/backend/tests/test_deadline_validation_policy.py",
                    "app/backend/tests/test_client_delivery_risk_checklist.py",
                    "app/backend/tests/test_client_delivery_transparency_policy.py",
                    "app/backend/tests/test_evidence_exhibit_package_policy.py",
                    "app/backend/tests/test_case_evidence_catalog_export_preflight.py",
                    "docs/DEEP_REVIEW_CITATION_AUDIT.md",
                    "docs/DEEP_REVIEW_EVIDENCE_AUDIT.md",
                    "docs/LEGAL_SOURCE_FRESHNESS_POLICY.md",
                    "docs/LEGAL_GROUNDING_QUICK_AUDIT.md",
                    "docs/CASE_EVIDENCE_GRAPH.md",
                    "docs/CASE_WORKBENCH_PAYLOAD.md",
                    "docs/CASE_WORKBENCH_PERSISTENCE_PLAN.md",
                    "docs/CASE_WORKBENCH_RISK_REFRESH_PLAN.md",
                    "docs/CASE_EVIDENCE_CATALOG_EXPORT_PREFLIGHT.md",
                    "docs/CASE_EXPORT_READINESS_DOWNLOAD_GATE.md",
                    "docs/CASE_INTAKE_COMPLETENESS.md",
                    "docs/MATTER_INTAKE_READINESS_POLICY.md",
                    "docs/CASE_TIMELINE_DEADLINE_RISK.md",
                    "docs/DEADLINE_VALIDATION_POLICY.md",
                    "docs/CLIENT_DELIVERY_RISK_CHECKLIST.md",
                    "docs/CLIENT_DELIVERY_TRANSPARENCY_POLICY.md",
                    "docs/EVIDENCE_EXHIBIT_PACKAGE_POLICY.md",
                ),
                weight=20,
            ),
            MaintenanceSignal(
                id="ocr-import-readiness-policy",
                category="quality",
                title="OCR import readiness policy",
                description="The project defines explicit uploaded, preflight, OCR-needed, OCR-failed, parsed, blocked, and manual-review states for scanned or low-text legal uploads.",
                responsibility="Document-intake readiness review, OCR retry policy upkeep, manual-review routing, and metadata-only privacy checks.",
                cadence="Review whenever upload preflight, OCR engines, parsing, or import retry behavior changes.",
                evidence_paths=(
                    "app/backend/services/ocr_import_readiness_policy.py",
                    "app/backend/tests/test_ocr_import_readiness_policy.py",
                    "docs/OCR_IMPORT_READINESS_POLICY.md",
                ),
                weight=10,
            ),
            MaintenanceSignal(
                id="case-team-access-policy",
                category="security",
                title="Case team access policy",
                description="The project defines least-privilege case collaboration roles, role-operation permissions, a first runtime cases API access-control gate, CaseDetail permission UI state, client-only scopes, sensitive-operation approval rules, task runtime notification summaries, matter audit retention buckets, forbidden audit fields, and audit event requirements before richer team workflows are exposed.",
                responsibility="Runtime access gate review, role matrix review, permission decision review, sensitive-operation audit coverage, task runtime notification-summary review, matter audit retention review, client access minimization, and firm-retention policy alignment.",
                cadence="Review whenever team roles, sharing actions, export behavior, or case membership storage changes.",
                evidence_paths=(
                    "app/backend/services/case_team_access_policy.py",
                    "app/backend/services/case_role_permission_matrix.py",
                    "app/backend/services/case_access_control.py",
                    "app/backend/routers/cases.py",
                    "app/backend/services/case_task_notification_policy.py",
                    "app/backend/services/matter_audit_retention_policy.py",
                    "app/backend/tests/test_case_team_access_policy.py",
                    "app/backend/tests/test_case_role_permission_matrix.py",
                    "app/backend/tests/test_case_access_control.py",
                    "app/backend/tests/test_case_permission_runtime_router.py",
                    "app/backend/tests/test_case_task_notification_policy.py",
                    "app/backend/tests/test_matter_audit_retention_policy.py",
                    "app/frontend/src/lib/caseApi.ts",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "docs/CASE_ACCESS_CONTROL_RUNTIME_GATE.md",
                    "docs/CASE_TEAM_ACCESS_POLICY.md",
                    "docs/CASE_ROLE_PERMISSION_MATRIX.md",
                    "docs/CASE_TASK_NOTIFICATION_POLICY.md",
                    "docs/MATTER_AUDIT_RETENTION_POLICY.md",
                ),
                weight=10,
            ),
            MaintenanceSignal(
                id="risk-scoring-release-decision",
                category="release_management",
                title="Risk scoring and release decision",
                description="The project computes deterministic risk scores and combines quality, citation, evidence, lawyer-review workflow, document delivery manifest, version diff checklist, and risk signals into client delivery decisions.",
                responsibility="Release readiness review, lawyer-review workflow routing, document delivery manifest review, version diff review, and delivery-blocker management.",
                cadence="Review before public releases and after high-risk workflow changes.",
                evidence_paths=(
                    "app/backend/services/risk_scoring.py",
                    "app/backend/services/release_decision.py",
                    "app/backend/services/lawyer_review_workflow_policy.py",
                    "app/backend/services/document_delivery_package_manifest.py",
                    "app/backend/services/document_version_diff_checklist.py",
                    "app/backend/tests/test_risk_scoring.py",
                    "app/backend/tests/test_release_decision.py",
                    "app/backend/tests/test_lawyer_review_workflow_policy.py",
                    "app/backend/tests/test_document_delivery_package_manifest.py",
                    "app/backend/tests/test_document_version_diff_checklist.py",
                    "docs/DEEP_REVIEW_RISK_SCORING.md",
                    "docs/DEEP_REVIEW_RELEASE_DECISION.md",
                    "docs/LAWYER_REVIEW_WORKFLOW_POLICY.md",
                    "docs/DOCUMENT_DELIVERY_PACKAGE_MANIFEST.md",
                    "docs/DOCUMENT_VERSION_DIFF_CHECKLIST.md",
                ),
                weight=20,
            ),
            MaintenanceSignal(
                id="frontend-review-visibility",
                category="product",
                title="Frontend report visibility",
                description="The report, case, and maintenance UI expose quality, citation, evidence, risk, delivery, lawyer-review, runtime event, selected-source legal RAG context, benchmark registry metadata, and quota-consumption signals to reviewers.",
                responsibility="Reviewer workflow usability, report mapping, case page runtime wiring, benchmark registry UI review, selected-source request metadata wiring, and frontend type maintenance.",
                cadence="Review with every report-schema change and user-facing delivery workflow update.",
                evidence_paths=(
                    "app/frontend/src/lib/deepReviewApi.ts",
                    "app/frontend/src/lib/reportMapper.ts",
                    "app/frontend/src/pages/DeepReportPage.tsx",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/components/cases/LegalRagResearchPanel.tsx",
                    "app/frontend/src/lib/caseApi.ts",
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/lib/mockData.ts",
                ),
                weight=15,
            ),
            MaintenanceSignal(
                id="user-need-implementation-priority-queue",
                category="maintenance",
                title="User need implementation priority queue",
                description="Metadata-only queue evidence links high-priority user needs, legal benchmark coverage gaps, cheap-first calibration/model routing risk, and product execution actions for release review.",
                responsibility="Review the priority queue before product, benchmark, or model-routing implementation slices are promoted.",
                cadence="Review before medium or large user-need, benchmark, calibration, or model-routing updates.",
                evidence_paths=(
                    "app/backend/services/release_readiness.py",
                    "app/backend/services/continuous_update_ledger.py",
                    "app/backend/services/maintenance_evidence.py",
                    "app/backend/tests/test_release_readiness.py",
                    "app/backend/tests/test_continuous_update_ledger.py",
                    "app/backend/tests/test_maintenance_evidence.py",
                    "docs/CONTINUOUS_UPDATE_LEDGER.md",
                    "docs/USER_NEED_BENCHMARK_COVERAGE.md",
                    "docs/USER_NEEDS_RADAR.md",
                ),
                weight=10,
            ),
            MaintenanceSignal(
                id="user-need-gemini-route-coverage",
                category="maintenance",
                title="User need Gemini route coverage",
                description="Metadata-only route coverage evidence links user needs to cheap-first calibration tasks and Gemini route preflight rows so maintainers can review Flash-Lite protection, premium exceptions, public benchmark/license gaps, and unmapped route blockers.",
                responsibility="Review user-need route coverage before promoting Gemini default, benchmark, or route-mapping changes.",
                cadence="Review before medium or large user-need, Gemini route, benchmark, calibration, or default-change updates.",
                evidence_paths=(
                    "app/backend/services/user_need_gemini_route_coverage.py",
                    "app/backend/tests/test_user_need_gemini_route_coverage.py",
                    "app/backend/services/user_need_benchmark_coverage.py",
                    "app/backend/services/gemini_newapi_cheap_first_calibration.py",
                    "app/backend/services/model_ops_gemini_cheap_first_route_preflight.py",
                    "app/backend/routers/maintenance.py",
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                    "app/frontend/scripts/ui-regression.mjs",
                    "docs/USER_NEED_GEMINI_ROUTE_COVERAGE.md",
                    "docs/USER_NEED_BENCHMARK_COVERAGE.md",
                    "docs/USER_NEEDS_RADAR.md",
                ),
                weight=10,
            ),
            MaintenanceSignal(
                id="user-research-maintenance-notes",
                category="maintenance",
                title="User research and maintenance notes",
                description="The repository documents target users, workflow priorities, feedback lifecycle, repeated issue clustering, billing quota evidence, entitlement quota binding, usage routes and preflight, generated-document CRUD, case generation, and deep-review document quota guards, quota delivery decisions, privacy retention rules, release claim compliance, admin audit policy, local payment reconciliation policy, frontend runtime API helpers, document-generation quota attempts, migration planning, maintenance metrics, heartbeat evidence format, validation event evidence normalization, continuous session review packets, and application-safe claims.",
                responsibility="User workflow research, feedback lifecycle and issue-cluster review, billing quota, entitlement binding, generated-document, case-generation, and deep-review document quota guards, quota delivery decisions, retention, claim-compliance, admin-audit, local payment reconciliation, usage-route, preflight, API-helper, and migration review, maintenance roadmap updates, heartbeat evidence review, validation event metadata review, review-packet accuracy, and support-application accuracy.",
                cadence="Review when user segments, product scope, or public support applications change.",
                evidence_paths=(
                    "docs/USER_RESEARCH_AND_MAINTENANCE.md",
                    "app/backend/services/continuous_update_ledger.py",
                    "app/backend/services/continuous_session_evidence.py",
                    "app/backend/services/continuous_session_timeline.py",
                    "app/backend/services/continuous_session_run_monitor.py",
                    "app/backend/services/continuous_session_review_packet.py",
                    "app/backend/services/legal_fixture_local_run_review.py",
                    "app/backend/services/git_history_evidence.py",
                    "app/backend/services/validation_event_evidence.py",
                    "app/backend/services/feedback_roadmap_alignment.py",
                    "app/backend/services/feedback_capture_plan.py",
                    "app/backend/services/feedback_lifecycle_policy.py",
                    "app/backend/routers/admin_ops.py",
                    "app/backend/services/billing_entitlement_gap.py",
                    "app/backend/services/billing_usage_quota_policy.py",
                    "app/backend/services/billing_quota_persistence_plan.py",
                    "app/backend/services/billing_quota_migration_plan.py",
                    "app/backend/services/billing_quota_repository.py",
                    "app/backend/services/billing_entitlement_quota_binding.py",
                    "app/backend/routers/billing_usage.py",
                    "app/backend/routers/generated_documents.py",
                    "app/backend/routers/case_intelligence.py",
                    "app/backend/routers/deep_review.py",
                    "app/backend/services/deep_review_document_quota.py",
                    "app/backend/services/billing_payment_reconciliation.py",
                    "app/backend/services/quota_delivery_decision.py",
                    "app/backend/services/feedback_issue_cluster.py",
                    "app/backend/services/privacy_retention_rules.py",
                    "app/backend/services/release_claim_compliance.py",
                    "app/backend/services/admin_audit_policy.py",
                    "app/backend/services/product_feature_gap_radar.py",
                    "app/backend/services/user_needs_radar.py",
                    "app/backend/tests/test_billing_entitlement_gap.py",
                    "app/backend/tests/test_billing_usage_quota_policy.py",
                    "app/backend/tests/test_billing_quota_persistence_plan.py",
                    "app/backend/tests/test_billing_quota_migration_plan.py",
                    "app/backend/tests/test_billing_quota_repository.py",
                    "app/backend/tests/test_billing_entitlement_quota_binding.py",
                    "app/backend/tests/test_billing_usage_router.py",
                    "app/backend/tests/test_generated_documents_quota.py",
                    "app/backend/tests/test_case_generation_quota.py",
                    "app/backend/tests/test_deep_review_document_quota.py",
                    "app/backend/tests/test_billing_payment_reconciliation.py",
                    "app/backend/tests/test_quota_delivery_decision.py",
                    "app/backend/tests/test_feedback_issue_cluster.py",
                    "app/backend/tests/test_privacy_retention_rules.py",
                    "app/backend/tests/test_release_claim_compliance.py",
                    "app/backend/tests/test_admin_audit_policy.py",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/lib/billingUsageApi.ts",
                    "app/backend/tests/test_continuous_update_ledger.py",
                    "app/backend/tests/test_continuous_session_evidence.py",
                    "app/backend/tests/test_continuous_session_timeline.py",
                    "app/backend/tests/test_continuous_session_run_monitor.py",
                    "app/backend/tests/test_continuous_session_review_packet.py",
                    "app/backend/tests/test_git_history_evidence.py",
                    "app/backend/tests/test_validation_event_evidence.py",
                    "app/backend/tests/test_feedback_roadmap_alignment.py",
                    "app/backend/tests/test_admin_feedback_capture_summary.py",
                    "app/backend/tests/test_feedback_capture_plan.py",
                    "app/backend/tests/test_feedback_lifecycle_policy.py",
                    "app/backend/tests/test_product_feature_gap_radar.py",
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/components/feedback/FeedbackCapturePanel.tsx",
                    "app/frontend/src/pages/AdminPage.tsx",
                    "app/frontend/src/pages/DeepReportPage.tsx",
                    "app/frontend/src/lib/feedbackApi.ts",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                    "app/frontend/scripts/ui-regression.mjs",
                    "docs/CONTINUOUS_UPDATE_LEDGER.md",
                    "docs/CONTINUOUS_SESSION_EVIDENCE.md",
                    "docs/CONTINUOUS_SESSION_TIMELINE.md",
                    "docs/CONTINUOUS_SESSION_RUN_MONITOR.md",
                    "docs/CONTINUOUS_SESSION_REVIEW_PACKET.md",
                    "docs/GIT_HISTORY_EVIDENCE.md",
                    "docs/VALIDATION_EVENT_EVIDENCE.md",
                    "app/backend/services/maintenance_heartbeat_evidence.py",
                    "app/backend/tests/test_maintenance_heartbeat_evidence.py",
                    "docs/MAINTENANCE_HEARTBEAT_EVIDENCE.md",
                    "docs/BILLING_ENTITLEMENT_GAP.md",
                    "docs/BILLING_USAGE_QUOTA_POLICY.md",
                    "docs/BILLING_QUOTA_PERSISTENCE_PLAN.md",
                    "docs/BILLING_QUOTA_MIGRATION_PLAN.md",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                    "docs/USER_NEEDS_RADAR.md",
                    "docs/FEEDBACK_ROADMAP_ALIGNMENT.md",
                    "docs/FEEDBACK_CAPTURE_PLAN.md",
                    "docs/FEEDBACK_LIFECYCLE_POLICY.md",
                ),
                weight=10,
            ),
        ]

    def _summary(self, language: Language) -> str:
        if language == "zh":
            return "项目有可审核的代码、测试、文档、质量控制、交付门禁和维护职责说明。"
        return "The project has reviewable code, tests, documentation, quality controls, release gates, and maintainer responsibilities."

    def _responsibilities(self, signals: list[MaintenanceSignal]) -> list[str]:
        seen: set[str] = set()
        responsibilities: list[str] = []
        for signal in signals:
            if signal.responsibility not in seen:
                seen.add(signal.responsibility)
                responsibilities.append(signal.responsibility)
        return responsibilities

    def _evidence_score(self, signals: list[MaintenanceSignal]) -> int:
        if not signals:
            return 0
        return min(100, sum(max(0, signal.weight) for signal in signals))

    def _normalize_language(self, language: str) -> Language:
        return "zh" if language == "zh" else "en"
