from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Literal


Language = Literal["en", "zh"]


REPOSITORY_URL = "https://github.com/lixinglongye/xiaolvshi"


@dataclass(frozen=True)
class MaintenanceSignal:
    id: str
    category: str
    title: str
    description: str
    responsibility: str
    cadence: str
    evidence_paths: tuple[str, ...]
    weight: int

    def to_api(self) -> dict:
        data = asdict(self)
        data["evidence_paths"] = list(self.evidence_paths)
        return data


class MaintenanceEvidenceService:
    """Builds application-safe OSS maintenance evidence for this project."""

    def build_profile(self, language: Language = "en") -> dict:
        language = self._normalize_language(language)
        signals = self._signals()

        return {
            "project": {
                "name": "xiaolvshi",
                "display_name": "律审雷达",
                "repository_url": REPOSITORY_URL,
                "domain": "Legal document review, case material organization, and litigation preparation",
            },
            "maintainer_role": "primary_project_maintainer",
            "evidence_score": self._evidence_score(signals),
            "active_maintenance_summary": self._summary(language),
            "form_answer": self.build_form_answer(language),
            "signals": [signal.to_api() for signal in signals],
            "responsibilities": self._responsibilities(signals),
            "release_management": {
                "current_stage": "active_pre_release_development",
                "release_readiness_controls": [
                    "Deep-review quality gate",
                    "Citation audit",
                    "Evidence audit",
                    "Risk scoring",
                    "Unified release decision",
                    "Model configuration audit",
                    "Model default optimization",
                    "Model default recommendation snapshot",
                    "Gemini/NewAPI cheap-first policy",
                    "Gemini/NewAPI model selector",
                    "Gemini and gateway price refresh monitor",
                    "Model cost regression snapshots",
                    "Model gateway compatibility",
                "Model operations readiness",
                "Case workbench payload contract",
                "Model route guardrails",
                "Gemini reasoning effort policy",
                "Generation request parameter policy",
                "Model request cost bounds",
                "Model cache policy",
                "Continuous update ledger",
                "Maintenance heartbeat evidence",
                "Continuous session evidence validator",
                "Continuous session timeline",
                "Continuous session review packet",
                "Git history cadence evidence",
                "Validation event evidence normalizer",
                "Case team access policy",
                "Case role permission matrix",
                "Document delivery package manifest",
                "Document version diff checklist",
                "Client delivery risk checklist",
                "Legal document template matrix",
                "Legal document export readiness",
                "OCR import readiness policy",
                "Case timeline deadline risk",
                "Deadline validation policy",
                "Matter intake readiness policy",
                "Matter audit retention policy",
                "Lawyer review workflow policy",
                "Evidence exhibit package policy",
                "Case task notification policy",
                "Client delivery transparency policy",
                "Legal document benchmark fixtures",
                "Contract clause extraction schema",
                "Small legal document corpus expansion",
                "Legal RAG failure fixtures",
                "Legal source freshness policy",
                "Legal source ingestion metadata",
                "Legal source durable index plan",
                "Legal source index repository",
                "Legal RAG index binding",
                "Legal RAG index route",
                "Billing usage quota policy",
                "Billing quota persistence plan",
                "Billing quota migration plan",
                "Billing quota repository",
                "Billing entitlement quota binding",
                "Billing quota consumption route",
                "Billing report preflight route",
                "Case workbench persistence plan",
                "Case workbench state repository",
                "Case workbench runtime binding",
                "Case workbench runtime router",
                "Frontend runtime API client bindings",
                "Case edit runtime event binding",
                "Legal RAG research context cache",
                "Document generation quota consumption attempt",
                "Generated documents CRUD quota guard",
                "Case generation quota guard",
                "Deep-review document generation quota guard",
                "Legal RAG selected-source request metadata",
                "Legal RAG selected-source citation validation",
                "Legal RAG selected-source validation maintenance route",
                "Deep-review selected-source binding",
                "Quota delivery decision",
                "Feedback issue cluster",
                "Evidence bundle integrity",
                "Privacy retention rules",
                "Release claim compliance",
                "Case export readiness",
                "Admin audit policy",
                "Billing payment reconciliation policy",
                "Case task runtime notification summary",
                "Legal document benchmark suite",
                "Legal benchmark research registry UI",
                "Feedback lifecycle policy",
            ],
                "client_delivery_policy": "Reports are not marked client-deliverable until release_decision allows delivery.",
            },
            "application_guardrails": [
                "Only claim maintenance work that is visible in this repository.",
                "Do not claim external ecosystem adoption without public evidence.",
                "Do not claim third-party PR or issue volume unless GitHub records show it.",
                "Payment evidence is currently local policy only; do not claim real provider settlement, webhook signature verification, or invoice collection until external integration evidence is merged.",
                "Selected-source Legal RAG evidence now includes metadata propagation and citation-map validation; do not claim automatic deep-review report binding until merged evidence exists.",
                "Deep-review selected-source binding exists as metadata evidence; do not claim live report persistence/export integration until it is wired into production flows.",
                "The continuous session evidence validator can review explicit 24-hour metadata, but it does not prove completion unless the submitted events cover the full window.",
                "The continuous session timeline joins metadata evidence for reviewers, but support claims must remain blocked until real timestamped events prove the full 24-hour window.",
                "The continuous session review packet is a metadata-only index with blockers, review questions, and a stable hash; it is not a substitute for real timestamped 24-hour evidence.",
                "Git history cadence evidence can show commit windows and gaps, but it does not prove tests, pushes, credential scans, low-resource fixture runs, or release review by itself.",
                "Validation event evidence accepts only sanitized test, credential-scan, push, release-review, and legal fixture metadata; raw logs, legal text, model output, credentials, and emails stay out of the support claim.",
                "Generated document CRUD, case generation, and deep-review first-principles generation are quota guarded; quota delivery decisions exist as metadata evidence but do not prove real payment provider settlement or universal cross-endpoint quota coverage.",
                "Human maintainer must confirm ownership and final form attestations before submission.",
            ],
        }

    def build_form_answer(self, language: Language = "en") -> str:
        language = self._normalize_language(language)
        if language == "zh":
            return (
                "我是 xiaolvshi 项目的维护者，仓库地址为 "
                f"{REPOSITORY_URL}。该项目正在持续维护，目前包含 FastAPI 后端、React/Vite "
                "前端、本地法律知识库、文件处理、深度审查流水线、自动化测试和维护文档。"
                "近期维护内容包括 Gemini/NewAPI 模型路由与预算策略、确定性风险评分、报告质量门禁、"
                "引用审计、证据审计，以及法律深度审查报告的统一交付决策流程。"
                "我持续负责发布就绪检查、质量控制、测试覆盖、文档更新和问题分级处理，使该项目作为"
                "可维护的开源法律审查工具持续演进，而不是一次性演示项目。"
            )

        return (
            "I am the maintainer of the xiaolvshi project: "
            f"{REPOSITORY_URL}. The repository is under active development and includes a FastAPI "
            "backend, React/Vite frontend, local legal knowledge base, file processing, deep-review "
            "pipeline, automated tests, and maintenance documentation. Recent maintenance work includes "
            "Gemini/NewAPI model routing and budget policy, deterministic risk scoring, report quality "
            "gates, citation auditing, evidence auditing, and a unified release decision workflow for "
            "legal deep-review reports. I actively handle release readiness, quality checks, test coverage, "
            "documentation updates, and issue-style triage logic so the project can be maintained as a usable "
            "open-source legal review tool rather than a one-time demo."
        )

    def _signals(self) -> list[MaintenanceSignal]:
        return [
            MaintenanceSignal(
                id="model-routing-cost-control",
                category="model_ops",
                title="Cost-aware Gemini/NewAPI routing",
                description="OpenAI-compatible gateway routing prefers cheaper Gemini models for routine tasks and keeps defaults pinned to stable lifecycle-safe models with safe gateway health planning, model selector audits, default recommendation snapshots, price-refresh monitoring, cost regression snapshots, route telemetry persistence planning, and sanitized probe evaluation.",
                responsibility="Model catalog maintenance, budget policy review, task-level selector review, default recommendation review, price-refresh review, cost regression review, route telemetry privacy review, gateway compatibility updates, gateway health-plan review, sanitized probe evaluation, and Gemini lifecycle policy review.",
                cadence="Review when gateway model names, pricing, or task defaults change.",
                evidence_paths=(
                    "app/backend/services/model_catalog.py",
                    "app/backend/services/model_budget.py",
                    "app/backend/services/model_capability_matrix.py",
                    "app/backend/services/model_configuration_audit.py",
                    "app/backend/services/model_default_optimization.py",
                    "app/backend/services/model_default_recommendation_snapshot.py",
                    "app/backend/services/gemini_newapi_cheap_first_policy.py",
                    "app/backend/services/gemini_newapi_model_selector.py",
                    "app/backend/services/model_price_refresh_monitor.py",
                    "app/backend/services/model_cost_regression_snapshots.py",
                    "app/backend/services/route_telemetry_persistence_plan.py",
                    "app/backend/services/model_gateway_compatibility.py",
                    "app/backend/services/model_gateway_health_plan.py",
                    "app/backend/services/model_gateway_probe_evaluation.py",
                    "app/backend/services/model_lifecycle_policy.py",
                    "app/backend/services/model_ops_readiness.py",
                    "app/backend/services/model_runtime_router.py",
                    "app/backend/services/model_reasoning_policy.py",
                    "app/backend/services/model_request_policy.py",
                    "app/backend/services/model_request_cost_bounds.py",
                    "app/backend/services/model_cache_policy.py",
                    "app/backend/services/model_route_telemetry.py",
                    "app/backend/services/model_route_guardrails.py",
                    "app/backend/services/model_task_inference.py",
                    "app/backend/services/model_callsite_audit.py",
                    "app/backend/services/model_escalation_policy.py",
                    "app/backend/services/model_cost_forecast.py",
                    "app/backend/services/model_cost_guardrails.py",
                    "app/backend/services/model_routing_replay.py",
                    "app/backend/services/model_fallback_chains.py",
                    "app/backend/tests/test_model_catalog.py",
                    "app/backend/tests/test_model_capability_matrix.py",
                    "app/backend/tests/test_model_configuration_audit.py",
                    "app/backend/tests/test_model_default_optimization.py",
                    "app/backend/tests/test_model_default_recommendation_snapshot.py",
                    "app/backend/tests/test_gemini_newapi_cheap_first_policy.py",
                    "app/backend/tests/test_gemini_newapi_model_selector.py",
                    "app/backend/tests/test_model_price_refresh_monitor.py",
                    "app/backend/tests/test_model_cost_regression_snapshots.py",
                    "app/backend/tests/test_route_telemetry_persistence_plan.py",
                    "app/backend/tests/test_model_gateway_compatibility.py",
                    "app/backend/tests/test_model_gateway_health_plan.py",
                    "app/backend/tests/test_model_gateway_probe_evaluation.py",
                    "app/backend/tests/test_model_lifecycle_policy.py",
                    "app/backend/tests/test_model_ops_readiness.py",
                    "app/backend/tests/test_model_runtime_router.py",
                    "app/backend/tests/test_model_reasoning_policy.py",
                    "app/backend/tests/test_model_request_policy.py",
                    "app/backend/tests/test_model_request_cost_bounds.py",
                    "app/backend/tests/test_model_cache_policy.py",
                    "app/backend/tests/test_model_route_telemetry.py",
                    "app/backend/tests/test_model_route_guardrails.py",
                    "app/backend/tests/test_aihub_runtime_routing.py",
                    "app/backend/tests/test_model_task_inference.py",
                    "app/backend/tests/test_model_callsite_audit.py",
                    "app/backend/tests/test_model_escalation_policy.py",
                    "app/backend/tests/test_model_cost_forecast.py",
                    "app/backend/tests/test_model_cost_guardrails.py",
                    "app/backend/tests/test_model_routing_replay.py",
                    "app/backend/tests/test_model_fallback_chains.py",
                    "docs/AI_MODEL_STRATEGY.md",
                    "docs/MODEL_CONFIGURATION_AUDIT.md",
                    "docs/MODEL_DEFAULT_OPTIMIZATION.md",
                    "docs/MODEL_DEFAULT_RECOMMENDATION_SNAPSHOT.md",
                    "docs/GEMINI_NEWAPI_CHEAP_FIRST_POLICY.md",
                    "docs/GEMINI_NEWAPI_MODEL_SELECTOR.md",
                    "docs/MODEL_PRICE_REFRESH_MONITOR.md",
                    "docs/MODEL_COST_REGRESSION_SNAPSHOTS.md",
                    "docs/ROUTE_TELEMETRY_PERSISTENCE_PLAN.md",
                    "docs/MODEL_GATEWAY_COMPATIBILITY.md",
                    "docs/MODEL_GATEWAY_HEALTH_PLAN.md",
                    "docs/MODEL_GATEWAY_PROBE_EVALUATION.md",
                    "docs/MODEL_LIFECYCLE_POLICY.md",
                    "docs/MODEL_OPS_READINESS.md",
                    "docs/MODEL_RUNTIME_ROUTER.md",
                    "docs/MODEL_REASONING_POLICY.md",
                    "docs/MODEL_REQUEST_POLICY.md",
                    "docs/MODEL_REQUEST_COST_BOUNDS.md",
                    "docs/MODEL_CACHE_POLICY.md",
                    "docs/MODEL_ROUTE_TELEMETRY.md",
                    "docs/MODEL_ROUTE_GUARDRAILS.md",
                    "docs/MODEL_TASK_INFERENCE.md",
                    "docs/MODEL_CALLSITE_AUDIT.md",
                    "docs/MODEL_ESCALATION_POLICY.md",
                    "docs/MODEL_COST_FORECAST.md",
                    "docs/MODEL_COST_GUARDRAILS.md",
                    "docs/MODEL_ROUTING_REPLAY.md",
                    "docs/MODEL_FALLBACK_CHAINS.md",
                ),
                weight=15,
            ),
            MaintenanceSignal(
                id="deep-review-quality-gates",
                category="quality",
                title="Deep-review quality gate",
                description="Deterministic gates, legal document template coverage, contract clause extraction schema, export-readiness checks, research-backed legal AI backlog planning, LegalBench/LexGLUE/COLIEE research registry mapping and UI evidence, public benchmark sampling plans, quick laptop-safe fixture suites, small legal document benchmark fixtures, deterministic legal document benchmark suite checks, small synthetic corpus expansion, RAG failure fixtures, legal source freshness policy, durable source index planning, metadata-only RAG index binding and route exposure, metadata-only research context cache/copy controls, selected-source request metadata propagation and citation validation, selected-source validation maintenance self-checks, deep-review selected-source binding, case export readiness, fixture-level Gemini/NewAPI model matrices, cheap-first fixture prompt packs, safe gateway manifests, laptop-safe fixture run plans, one-at-a-time local run packages, response normalizers, one-step local run reviews, cheap-first run reports, evidence bundles, archive-safe result summaries, fixture smoke tests, and fixture improvement plans verify report structure, grounding, pending-fact handling, disclaimers, and small legal document coverage before review.",
                responsibility="Quality gate tuning, legal template matrix review, contract clause schema review, export-readiness review, research backlog review, benchmark research registry and UI review, public benchmark sampler review, document benchmark fixture review, benchmark-suite review, small corpus review, RAG failure fixture review, source freshness, durable-index, RAG-index-binding, selected-source metadata, citation validation, deep-review binding, maintenance self-check route, quick-suite review, legal fixture model matrix review, prompt coverage, safe gateway manifest upkeep, fixture run-plan, local-package, response-normalizer, local-run-review, result-archive, run-report, and evidence-bundle maintenance, smoke coverage, prompt/schema improvement planning, regression tests, and release criteria maintenance.",
                cadence="Review whenever report schema, legal source handling, or delivery policy changes.",
                evidence_paths=(
                    "app/backend/services/report_quality_gate.py",
                    "app/backend/services/legal_review_benchmark.py",
                    "app/backend/services/contract_clause_extraction_schema.py",
                    "app/backend/services/legal_document_benchmark_fixtures.py",
                    "app/backend/services/legal_benchmark_research_registry.py",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                    "app/backend/services/legal_document_benchmark_suite.py",
                    "app/backend/services/small_legal_document_corpus_expansion.py",
                    "app/backend/services/legal_rag_failure_fixtures.py",
                    "app/backend/services/legal_source_ingestion_metadata.py",
                    "app/backend/services/legal_source_freshness_policy.py",
                    "app/backend/services/legal_source_durable_index_plan.py",
                    "app/backend/services/legal_source_index_repository.py",
                    "app/backend/services/legal_rag_index_binding.py",
                    "app/backend/routers/legal_rag.py",
                    "app/backend/services/legal_rag_request_metadata.py",
                    "app/backend/services/legal_rag_selected_source_validation.py",
                    "app/backend/services/deep_review_selected_source_binding.py",
                    "app/backend/services/case_export_readiness.py",
                    "app/backend/routers/case_intelligence.py",
                    "app/backend/services/case_intelligence.py",
                    "app/backend/services/case_ai_workbench.py",
                    "app/backend/services/legal_external_research_digest.py",
                    "app/backend/services/legal_document_export_readiness.py",
                    "app/backend/services/legal_document_template_matrix.py",
                    "app/backend/services/legal_research_backlog.py",
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                    "app/backend/services/legal_public_benchmark_sampler.py",
                    "app/backend/services/legal_fixture_quick_suite.py",
                    "app/backend/services/legal_fixture_model_matrix.py",
                    "app/backend/services/legal_fixture_prompt_pack.py",
                    "app/backend/services/legal_fixture_gateway_manifest.py",
                    "app/backend/services/legal_fixture_run_plan.py",
                    "app/backend/services/legal_fixture_local_run_package.py",
                    "app/backend/services/legal_fixture_response_normalizer.py",
                    "app/backend/services/legal_fixture_local_run_review.py",
                    "app/backend/services/legal_fixture_result_archive.py",
                    "app/backend/services/legal_fixture_run_report.py",
                    "app/backend/services/legal_fixture_evidence_bundle.py",
                    "app/backend/services/legal_fixture_improvement.py",
                    "app/backend/tests/test_report_quality_gate.py",
                    "app/backend/tests/test_legal_review_benchmark.py",
                    "app/backend/tests/test_contract_clause_extraction_schema.py",
                    "app/backend/tests/test_legal_document_benchmark_fixtures.py",
                    "app/backend/tests/test_legal_benchmark_research_registry.py",
                    "app/backend/tests/test_legal_document_benchmark_suite.py",
                    "app/backend/tests/test_small_legal_document_corpus_expansion.py",
                    "app/backend/tests/test_legal_rag_failure_fixtures.py",
                    "app/backend/tests/test_legal_source_ingestion_metadata.py",
                    "app/backend/tests/test_legal_source_freshness_policy.py",
                    "app/backend/tests/test_legal_source_durable_index_plan.py",
                    "app/backend/tests/test_legal_source_index_repository.py",
                    "app/backend/tests/test_legal_rag_index_binding.py",
                    "app/backend/tests/test_legal_rag_router.py",
                    "app/backend/tests/test_legal_rag_request_metadata.py",
                    "app/backend/tests/test_legal_rag_selected_source_validation.py",
                    "app/frontend/src/components/cases/LegalRagResearchPanel.tsx",
                    "app/frontend/src/lib/legalRagApi.ts",
                    "app/backend/tests/test_legal_external_research_digest.py",
                    "app/backend/tests/test_legal_document_export_readiness.py",
                    "app/backend/tests/test_legal_document_template_matrix.py",
                    "app/backend/tests/test_legal_research_backlog.py",
                    "app/backend/tests/test_legal_public_benchmark_sampler.py",
                    "app/backend/tests/test_legal_fixture_quick_suite.py",
                    "app/backend/tests/test_legal_fixture_model_matrix.py",
                    "app/backend/tests/test_legal_fixture_prompt_pack.py",
                    "app/backend/tests/test_legal_fixture_gateway_manifest.py",
                    "app/backend/tests/test_legal_fixture_run_plan.py",
                    "app/backend/tests/test_legal_fixture_local_run_package.py",
                    "app/backend/tests/test_legal_fixture_response_normalizer.py",
                    "app/backend/tests/test_legal_fixture_local_run_review.py",
                    "app/backend/tests/test_legal_fixture_result_archive.py",
                    "app/backend/tests/test_legal_fixture_run_report.py",
                    "app/backend/tests/test_legal_fixture_evidence_bundle.py",
                    "app/backend/tests/test_legal_fixture_improvement.py",
                    "docs/DEEP_REVIEW_QUALITY_GATES.md",
                    "docs/LEGAL_REVIEW_BENCHMARK.md",
                    "docs/CONTRACT_CLAUSE_EXTRACTION_SCHEMA.md",
                    "docs/LEGAL_DOCUMENT_BENCHMARK_FIXTURES.md",
                    "docs/SMALL_LEGAL_DOCUMENT_CORPUS_EXPANSION.md",
                    "docs/LEGAL_RAG_FAILURE_FIXTURES.md",
                    "docs/LEGAL_SOURCE_INGESTION_METADATA.md",
                    "docs/LEGAL_SOURCE_FRESHNESS_POLICY.md",
                    "docs/LEGAL_SOURCE_DURABLE_INDEX_PLAN.md",
                    "docs/LEGAL_EXTERNAL_RESEARCH_DIGEST.md",
                    "docs/LEGAL_DOCUMENT_EXPORT_READINESS.md",
                    "docs/LEGAL_DOCUMENT_TEMPLATE_MATRIX.md",
                    "docs/LEGAL_RESEARCH_BACKLOG.md",
                    "docs/LEGAL_PUBLIC_BENCHMARK_SAMPLER.md",
                    "docs/LEGAL_FIXTURE_QUICK_SUITE.md",
                    "docs/LEGAL_BENCHMARK_FIXTURES.md",
                    "docs/LEGAL_FIXTURE_MODEL_MATRIX.md",
                    "docs/LEGAL_FIXTURE_PROMPT_PACK.md",
                    "docs/LEGAL_FIXTURE_GATEWAY_MANIFEST.md",
                    "docs/LEGAL_FIXTURE_RUN_PLAN.md",
                    "docs/LEGAL_FIXTURE_LOCAL_RUN_PACKAGE.md",
                    "docs/LEGAL_FIXTURE_RESPONSE_NORMALIZER.md",
                    "docs/LEGAL_FIXTURE_LOCAL_RUN_REVIEW.md",
                    "docs/LEGAL_FIXTURE_RESULT_ARCHIVE.md",
                    "docs/LEGAL_FIXTURE_RUN_REPORT.md",
                    "docs/LEGAL_FIXTURE_EVIDENCE_BUNDLE.md",
                    "docs/LEGAL_FIXTURE_IMPROVEMENT.md",
                ),
                weight=15,
            ),
            MaintenanceSignal(
                id="citation-and-evidence-audits",
                category="review_ops",
                title="Citation and evidence audits",
                description="Citation, evidence, source freshness, exhibit package, evidence bundle integrity, grounding, case intake, workbench persistence planning, runtime state binding and routes, privacy-safe case edit runtime events, selected-source request metadata, matter intake readiness, deadline-risk, deadline validation, delivery-risk, delivery transparency, and graph services flag weak legal authorities, stale sources, duplicate evidence, missing reviewable citations, missing evidence plans, incomplete intake fields, urgent deadlines, missing client disclosures, unsupported legal claims, and blocking pending facts.",
                responsibility="Legal-source freshness review, issue triage, exhibit package review, evidence bundle integrity review, grounding quick-audit review, selected-source metadata review, workbench persistence, runtime-binding, router review, privacy-safe edit-event review, intake completeness review, matter-readiness review, deadline-risk and deadline-validation review, client-delivery checklist and transparency review, and evidence completeness checks.",
                cadence="Review when legal knowledge sources, report sections, or risk-item fields change.",
                evidence_paths=(
                    "app/backend/services/citation_audit.py",
                    "app/backend/services/evidence_audit.py",
                    "app/backend/services/evidence_bundle_integrity.py",
                    "app/backend/services/legal_source_freshness_policy.py",
                    "app/backend/services/legal_grounding_quick_audit.py",
                    "app/backend/services/case_evidence_graph.py",
                    "app/backend/services/case_workbench_payload.py",
                    "app/backend/services/case_workbench_persistence_plan.py",
                    "app/backend/services/case_workbench_state_repository.py",
                    "app/backend/services/case_workbench_runtime_binding.py",
                    "app/backend/routers/case_workbench_runtime.py",
                    "app/backend/services/legal_rag_request_metadata.py",
                    "app/backend/tests/test_legal_rag_request_metadata.py",
                    "app/backend/services/case_intake_completeness.py",
                    "app/backend/services/matter_intake_readiness_policy.py",
                    "app/backend/services/case_timeline_deadline_risk.py",
                    "app/backend/services/deadline_validation_policy.py",
                    "app/backend/services/client_delivery_risk_checklist.py",
                    "app/backend/services/client_delivery_transparency_policy.py",
                    "app/backend/services/evidence_exhibit_package_policy.py",
                    "app/backend/tests/test_citation_audit.py",
                    "app/backend/tests/test_evidence_audit.py",
                    "app/backend/tests/test_legal_source_freshness_policy.py",
                    "app/backend/tests/test_legal_grounding_quick_audit.py",
                    "app/backend/tests/test_case_evidence_graph.py",
                    "app/backend/tests/test_case_workbench_payload.py",
                    "app/backend/tests/test_case_workbench_persistence_plan.py",
                    "app/backend/tests/test_case_workbench_state_repository.py",
                    "app/backend/tests/test_case_workbench_runtime_binding.py",
                    "app/backend/tests/test_case_workbench_runtime_router.py",
                    "app/frontend/src/components/cases/CaseWorkbenchRuntimePanel.tsx",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/lib/workbenchRuntimeApi.ts",
                    "app/backend/tests/test_case_intake_completeness.py",
                    "app/backend/tests/test_matter_intake_readiness_policy.py",
                    "app/backend/tests/test_case_timeline_deadline_risk.py",
                    "app/backend/tests/test_deadline_validation_policy.py",
                    "app/backend/tests/test_client_delivery_risk_checklist.py",
                    "app/backend/tests/test_client_delivery_transparency_policy.py",
                    "app/backend/tests/test_evidence_exhibit_package_policy.py",
                    "docs/DEEP_REVIEW_CITATION_AUDIT.md",
                    "docs/DEEP_REVIEW_EVIDENCE_AUDIT.md",
                    "docs/LEGAL_SOURCE_FRESHNESS_POLICY.md",
                    "docs/LEGAL_GROUNDING_QUICK_AUDIT.md",
                    "docs/CASE_EVIDENCE_GRAPH.md",
                    "docs/CASE_WORKBENCH_PAYLOAD.md",
                    "docs/CASE_WORKBENCH_PERSISTENCE_PLAN.md",
                    "docs/CASE_INTAKE_COMPLETENESS.md",
                    "docs/MATTER_INTAKE_READINESS_POLICY.md",
                    "docs/CASE_TIMELINE_DEADLINE_RISK.md",
                    "docs/DEADLINE_VALIDATION_POLICY.md",
                    "docs/CLIENT_DELIVERY_RISK_CHECKLIST.md",
                    "docs/CLIENT_DELIVERY_TRANSPARENCY_POLICY.md",
                    "docs/EVIDENCE_EXHIBIT_PACKAGE_POLICY.md",
                ),
                weight=20,
            ),
            MaintenanceSignal(
                id="ocr-import-readiness-policy",
                category="quality",
                title="OCR import readiness policy",
                description="The project defines explicit uploaded, preflight, OCR-needed, OCR-failed, parsed, blocked, and manual-review states for scanned or low-text legal uploads.",
                responsibility="Document-intake readiness review, OCR retry policy upkeep, manual-review routing, and metadata-only privacy checks.",
                cadence="Review whenever upload preflight, OCR engines, parsing, or import retry behavior changes.",
                evidence_paths=(
                    "app/backend/services/ocr_import_readiness_policy.py",
                    "app/backend/tests/test_ocr_import_readiness_policy.py",
                    "docs/OCR_IMPORT_READINESS_POLICY.md",
                ),
                weight=10,
            ),
            MaintenanceSignal(
                id="case-team-access-policy",
                category="security",
                title="Case team access policy",
                description="The project defines least-privilege case collaboration roles, role-operation permissions, client-only scopes, sensitive-operation approval rules, task runtime notification summaries, matter audit retention buckets, forbidden audit fields, and audit event requirements before richer team workflows are exposed.",
                responsibility="Role matrix review, permission decision review, sensitive-operation audit coverage, task runtime notification-summary review, matter audit retention review, client access minimization, and firm-retention policy alignment.",
                cadence="Review whenever team roles, sharing actions, export behavior, or case membership storage changes.",
                evidence_paths=(
                    "app/backend/services/case_team_access_policy.py",
                    "app/backend/services/case_role_permission_matrix.py",
                    "app/backend/services/case_task_notification_policy.py",
                    "app/backend/services/matter_audit_retention_policy.py",
                    "app/backend/tests/test_case_team_access_policy.py",
                    "app/backend/tests/test_case_role_permission_matrix.py",
                    "app/backend/tests/test_case_task_notification_policy.py",
                    "app/backend/tests/test_matter_audit_retention_policy.py",
                    "docs/CASE_TEAM_ACCESS_POLICY.md",
                    "docs/CASE_ROLE_PERMISSION_MATRIX.md",
                    "docs/CASE_TASK_NOTIFICATION_POLICY.md",
                    "docs/MATTER_AUDIT_RETENTION_POLICY.md",
                ),
                weight=10,
            ),
            MaintenanceSignal(
                id="risk-scoring-release-decision",
                category="release_management",
                title="Risk scoring and release decision",
                description="The project computes deterministic risk scores and combines quality, citation, evidence, lawyer-review workflow, document delivery manifest, version diff checklist, and risk signals into client delivery decisions.",
                responsibility="Release readiness review, lawyer-review workflow routing, document delivery manifest review, version diff review, and delivery-blocker management.",
                cadence="Review before public releases and after high-risk workflow changes.",
                evidence_paths=(
                    "app/backend/services/risk_scoring.py",
                    "app/backend/services/release_decision.py",
                    "app/backend/services/lawyer_review_workflow_policy.py",
                    "app/backend/services/document_delivery_package_manifest.py",
                    "app/backend/services/document_version_diff_checklist.py",
                    "app/backend/tests/test_risk_scoring.py",
                    "app/backend/tests/test_release_decision.py",
                    "app/backend/tests/test_lawyer_review_workflow_policy.py",
                    "app/backend/tests/test_document_delivery_package_manifest.py",
                    "app/backend/tests/test_document_version_diff_checklist.py",
                    "docs/DEEP_REVIEW_RISK_SCORING.md",
                    "docs/DEEP_REVIEW_RELEASE_DECISION.md",
                    "docs/LAWYER_REVIEW_WORKFLOW_POLICY.md",
                    "docs/DOCUMENT_DELIVERY_PACKAGE_MANIFEST.md",
                    "docs/DOCUMENT_VERSION_DIFF_CHECKLIST.md",
                ),
                weight=20,
            ),
            MaintenanceSignal(
                id="frontend-review-visibility",
                category="product",
                title="Frontend report visibility",
                description="The report, case, and maintenance UI expose quality, citation, evidence, risk, delivery, lawyer-review, runtime event, selected-source legal RAG context, benchmark registry metadata, and quota-consumption signals to reviewers.",
                responsibility="Reviewer workflow usability, report mapping, case page runtime wiring, benchmark registry UI review, selected-source request metadata wiring, and frontend type maintenance.",
                cadence="Review with every report-schema change and user-facing delivery workflow update.",
                evidence_paths=(
                    "app/frontend/src/lib/deepReviewApi.ts",
                    "app/frontend/src/lib/reportMapper.ts",
                    "app/frontend/src/pages/DeepReportPage.tsx",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/components/cases/LegalRagResearchPanel.tsx",
                    "app/frontend/src/lib/caseApi.ts",
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/lib/mockData.ts",
                ),
                weight=15,
            ),
            MaintenanceSignal(
                id="user-research-maintenance-notes",
                category="maintenance",
                title="User research and maintenance notes",
                description="The repository documents target users, workflow priorities, feedback lifecycle, repeated issue clustering, billing quota evidence, entitlement quota binding, usage routes and preflight, generated-document CRUD, case generation, and deep-review document quota guards, quota delivery decisions, privacy retention rules, release claim compliance, admin audit policy, local payment reconciliation policy, frontend runtime API helpers, document-generation quota attempts, migration planning, maintenance metrics, heartbeat evidence format, validation event evidence normalization, continuous session review packets, and application-safe claims.",
                responsibility="User workflow research, feedback lifecycle and issue-cluster review, billing quota, entitlement binding, generated-document, case-generation, and deep-review document quota guards, quota delivery decisions, retention, claim-compliance, admin-audit, local payment reconciliation, usage-route, preflight, API-helper, and migration review, maintenance roadmap updates, heartbeat evidence review, validation event metadata review, review-packet accuracy, and support-application accuracy.",
                cadence="Review when user segments, product scope, or public support applications change.",
                evidence_paths=(
                    "docs/USER_RESEARCH_AND_MAINTENANCE.md",
                    "app/backend/services/continuous_update_ledger.py",
                    "app/backend/services/continuous_session_evidence.py",
                    "app/backend/services/continuous_session_timeline.py",
                    "app/backend/services/continuous_session_review_packet.py",
                    "app/backend/services/git_history_evidence.py",
                    "app/backend/services/validation_event_evidence.py",
                    "app/backend/services/feedback_roadmap_alignment.py",
                    "app/backend/services/feedback_lifecycle_policy.py",
                    "app/backend/services/billing_entitlement_gap.py",
                    "app/backend/services/billing_usage_quota_policy.py",
                    "app/backend/services/billing_quota_persistence_plan.py",
                    "app/backend/services/billing_quota_migration_plan.py",
                    "app/backend/services/billing_quota_repository.py",
                    "app/backend/services/billing_entitlement_quota_binding.py",
                    "app/backend/routers/billing_usage.py",
                    "app/backend/routers/generated_documents.py",
                    "app/backend/routers/case_intelligence.py",
                    "app/backend/routers/deep_review.py",
                    "app/backend/services/deep_review_document_quota.py",
                    "app/backend/services/billing_payment_reconciliation.py",
                    "app/backend/services/quota_delivery_decision.py",
                    "app/backend/services/feedback_issue_cluster.py",
                    "app/backend/services/privacy_retention_rules.py",
                    "app/backend/services/release_claim_compliance.py",
                    "app/backend/services/admin_audit_policy.py",
                    "app/backend/services/product_feature_gap_radar.py",
                    "app/backend/services/user_needs_radar.py",
                    "app/backend/tests/test_billing_entitlement_gap.py",
                    "app/backend/tests/test_billing_usage_quota_policy.py",
                    "app/backend/tests/test_billing_quota_persistence_plan.py",
                    "app/backend/tests/test_billing_quota_migration_plan.py",
                    "app/backend/tests/test_billing_quota_repository.py",
                    "app/backend/tests/test_billing_entitlement_quota_binding.py",
                    "app/backend/tests/test_billing_usage_router.py",
                    "app/backend/tests/test_generated_documents_quota.py",
                    "app/backend/tests/test_case_generation_quota.py",
                    "app/backend/tests/test_deep_review_document_quota.py",
                    "app/backend/tests/test_billing_payment_reconciliation.py",
                    "app/backend/tests/test_quota_delivery_decision.py",
                    "app/backend/tests/test_feedback_issue_cluster.py",
                    "app/backend/tests/test_privacy_retention_rules.py",
                    "app/backend/tests/test_release_claim_compliance.py",
                    "app/backend/tests/test_admin_audit_policy.py",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/lib/billingUsageApi.ts",
                    "app/backend/tests/test_continuous_update_ledger.py",
                    "app/backend/tests/test_continuous_session_evidence.py",
                    "app/backend/tests/test_continuous_session_timeline.py",
                    "app/backend/tests/test_continuous_session_review_packet.py",
                    "app/backend/tests/test_git_history_evidence.py",
                    "app/backend/tests/test_validation_event_evidence.py",
                    "app/backend/tests/test_feedback_roadmap_alignment.py",
                    "app/backend/tests/test_feedback_lifecycle_policy.py",
                    "app/backend/tests/test_product_feature_gap_radar.py",
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                    "docs/CONTINUOUS_UPDATE_LEDGER.md",
                    "docs/CONTINUOUS_SESSION_EVIDENCE.md",
                    "docs/CONTINUOUS_SESSION_TIMELINE.md",
                    "docs/CONTINUOUS_SESSION_REVIEW_PACKET.md",
                    "docs/GIT_HISTORY_EVIDENCE.md",
                    "docs/VALIDATION_EVENT_EVIDENCE.md",
                    "app/backend/services/maintenance_heartbeat_evidence.py",
                    "app/backend/tests/test_maintenance_heartbeat_evidence.py",
                    "docs/MAINTENANCE_HEARTBEAT_EVIDENCE.md",
                    "docs/BILLING_ENTITLEMENT_GAP.md",
                    "docs/BILLING_USAGE_QUOTA_POLICY.md",
                    "docs/BILLING_QUOTA_PERSISTENCE_PLAN.md",
                    "docs/BILLING_QUOTA_MIGRATION_PLAN.md",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                    "docs/USER_NEEDS_RADAR.md",
                    "docs/FEEDBACK_ROADMAP_ALIGNMENT.md",
                    "docs/FEEDBACK_LIFECYCLE_POLICY.md",
                ),
                weight=10,
            ),
        ]

    def _summary(self, language: Language) -> str:
        if language == "zh":
            return "项目有可审核的代码、测试、文档、质量控制、交付门禁和维护职责说明。"
        return "The project has reviewable code, tests, documentation, quality controls, release gates, and maintainer responsibilities."

    def _responsibilities(self, signals: list[MaintenanceSignal]) -> list[str]:
        seen: set[str] = set()
        responsibilities: list[str] = []
        for signal in signals:
            if signal.responsibility not in seen:
                seen.add(signal.responsibility)
                responsibilities.append(signal.responsibility)
        return responsibilities

    def _evidence_score(self, signals: list[MaintenanceSignal]) -> int:
        if not signals:
            return 0
        return min(100, sum(max(0, signal.weight) for signal in signals))

    def _normalize_language(self, language: str) -> Language:
        return "zh" if language == "zh" else "en"
