from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


@dataclass(frozen=True)
class ProductFeatureGap:
    id: str
    title: str
    module: str
    current_state: str
    target_capability: str
    user_segments: tuple[str, ...]
    impact: int
    urgency: int
    effort: int
    confidence: int
    dependencies: tuple[str, ...]
    evidence_paths: tuple[str, ...]
    next_actions: tuple[str, ...]

    def to_api(self) -> dict[str, Any]:
        data = asdict(self)
        data["user_segments"] = list(self.user_segments)
        data["dependencies"] = list(self.dependencies)
        data["evidence_paths"] = list(self.evidence_paths)
        data["next_actions"] = list(self.next_actions)
        data["priority_score"] = priority_score(
            self.impact,
            self.urgency,
            self.effort,
            self.confidence,
        )
        data["priority_band"] = priority_band(data["priority_score"])
        data["completion_state"] = "gap"
        return data


@dataclass(frozen=True)
class DeliveryPhase:
    id: str
    title: str
    objective: str
    gap_ids: tuple[str, ...]
    exit_criteria: tuple[str, ...]

    def to_api(self) -> dict[str, Any]:
        data = asdict(self)
        data["gap_ids"] = list(self.gap_ids)
        data["exit_criteria"] = list(self.exit_criteria)
        return data


class ProductFeatureGapRadarService:
    """Expose the unfinished product surface as deterministic roadmap data."""

    def build_radar(self) -> dict[str, Any]:
        feature_gaps = sorted(
            (gap.to_api() for gap in self._feature_gaps()),
            key=lambda item: (-item["priority_score"], item["id"]),
        )
        high_priority = [gap for gap in feature_gaps if gap["priority_band"] in {"critical", "high"}]
        modules = sorted({gap["module"] for gap in feature_gaps})

        return {
            "status": "incomplete",
            "summary": {
                "feature_gap_count": len(feature_gaps),
                "high_priority_count": len(high_priority),
                "module_count": len(modules),
                "top_gap_ids": [gap["id"] for gap in feature_gaps[:5]],
                "modules": modules,
                "ready_for_public_feature_claim": False,
                "completion_policy": (
                    "Treat this radar as a product gap register until each high-priority gap has shipped evidence.",
                    "Do not claim full legal workflow coverage while any listed module remains in gap state.",
                ),
            },
            "feature_gaps": feature_gaps,
            "delivery_phases": [phase.to_api() for phase in self._delivery_phases()],
            "validation_commands": [
                "python -m pytest tests/test_product_feature_gap_radar.py -q",
                "rg -n \"(s[k]-[A-Za-z0-9]{20,}|APP_AI_KEY=s[k]-)\" app/backend/services/product_feature_gap_radar.py docs/PRODUCT_FEATURE_GAP_RADAR.md",
            ],
            "privacy_note": (
                "This privacy-safe radar is product planning metadata only. It must not include user documents, "
                "credentials, raw feedback text, API keys, account passwords, or personally identifying legal "
                "matter content."
            ),
        }

    def _feature_gaps(self) -> tuple[ProductFeatureGap, ...]:
        return (
            ProductFeatureGap(
                id="case-workbench",
                title="Case workbench",
                module="case_management",
                current_state="Case primitives, dashboard payload contract, notification policy, persistence plan, validated state repository, runtime binding facade, authenticated runtime routes, typed frontend API helper, route discovery smoke, a case overview runtime state/event panel, metadata-only risk/evidence refresh planning from runtime event deltas, privacy-safe material/evidence/fact/task edit event binding, and task runtime notification policy summaries exist, but collaborative editing, notification dispatch, escalation persistence, and actual live risk-state/evidence graph writes are not complete.",
                target_capability="A lawyer-grade case workspace that ties facts, parties, tasks, documents, risks, and review decisions together.",
                user_segments=("lawyer", "legal_ops"),
                impact=10,
                urgency=10,
                effort=7,
                confidence=9,
                dependencies=("evidence-management", "document-generation", "feedback-loop"),
                evidence_paths=(
                    "app/backend/services/cases.py",
                    "app/backend/services/case_tasks.py",
                    "app/backend/services/case_facts.py",
                    "app/backend/services/case_workbench_payload.py",
                    "app/backend/services/case_workbench_persistence_plan.py",
                    "app/backend/services/case_workbench_state_repository.py",
                    "app/backend/services/case_workbench_runtime_binding.py",
                    "app/backend/services/case_workbench_risk_refresh_plan.py",
                    "app/backend/routers/case_workbench_runtime.py",
                    "app/backend/services/case_task_notification_policy.py",
                    "app/backend/services/case_timeline_deadline_risk.py",
                    "app/backend/services/deadline_validation_policy.py",
                    "app/backend/services/matter_intake_readiness_policy.py",
                    "app/backend/tests/test_case_task_notification_policy.py",
                    "app/backend/tests/test_case_workbench_payload.py",
                    "app/backend/tests/test_case_workbench_persistence_plan.py",
                    "app/backend/tests/test_case_workbench_state_repository.py",
                    "app/backend/tests/test_case_workbench_runtime_binding.py",
                    "app/backend/tests/test_case_workbench_risk_refresh_plan.py",
                    "app/backend/tests/test_case_workbench_runtime_router.py",
                    "app/backend/tests/test_runtime_router_discovery.py",
                    "app/frontend/src/components/cases/CaseWorkbenchRuntimePanel.tsx",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/lib/workbenchRuntimeApi.ts",
                    "app/backend/tests/test_case_timeline_deadline_risk.py",
                    "app/backend/tests/test_deadline_validation_policy.py",
                    "app/backend/tests/test_matter_intake_readiness_policy.py",
                    "docs/CASE_WORKBENCH_PAYLOAD.md",
                    "docs/CASE_WORKBENCH_PERSISTENCE_PLAN.md",
                    "docs/CASE_WORKBENCH_RISK_REFRESH_PLAN.md",
                    "docs/CASE_TASK_NOTIFICATION_POLICY.md",
                    "docs/CASE_TIMELINE_DEADLINE_RISK.md",
                    "docs/DEADLINE_VALIDATION_POLICY.md",
                    "docs/MATTER_INTAKE_READINESS_POLICY.md",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                next_actions=(
                    "Wire runtime task notification policy summaries into durable escalation review queues.",
                    "Add explicit notification dispatch review and audit flows before sending messages.",
                    "Connect the risk refresh plan to actual live risk-state badges and evidence graph writes.",
                ),
            ),
            ProductFeatureGap(
                id="document-generation",
                title="Legal document generation",
                module="document_generation",
                current_state="Generated document storage, generated_documents CRUD quota guard, case evidence-catalog/civil-complaint quota guard, deep-review first-principles document-generation quota guard, selected-source binding, export-readiness metadata checks, quota delivery decisions, template governance evidence, delivery package manifest checks, version diff checklist, and a best-effort frontend report-quota consumption attempt after successful generation exist, but clause variables and renderer enforcement remain incomplete.",
                target_capability="Generate pleadings, notices, settlement drafts, and review memos with template provenance and lawyer review checkpoints.",
                user_segments=("lawyer", "individual", "legal_ops"),
                impact=10,
                urgency=9,
                effort=8,
                confidence=8,
                dependencies=("case-workbench", "legal-knowledge-rag", "safety-compliance"),
                evidence_paths=(
                    "app/backend/services/generated_documents.py",
                    "app/backend/services/documents.py",
                    "app/backend/services/legal_document_export_readiness.py",
                    "app/backend/services/legal_document_template_matrix.py",
                    "app/backend/services/document_delivery_package_manifest.py",
                    "app/backend/services/document_version_diff_checklist.py",
                    "app/backend/services/lawyer_review_workflow_policy.py",
                    "app/backend/services/client_delivery_transparency_policy.py",
                    "app/backend/routers/generated_documents.py",
                    "app/backend/routers/case_intelligence.py",
                    "app/backend/routers/deep_review.py",
                    "app/backend/services/deep_review_document_quota.py",
                    "app/backend/services/deep_review_selected_source_binding.py",
                    "app/backend/services/case_export_readiness.py",
                    "app/backend/services/quota_delivery_decision.py",
                    "app/backend/routers/billing_usage.py",
                    "app/backend/tests/test_generated_documents_quota.py",
                    "app/backend/tests/test_case_generation_quota.py",
                    "app/backend/tests/test_deep_review_document_quota.py",
                    "app/backend/tests/test_deep_review_selected_source_binding.py",
                    "app/backend/tests/test_case_export_readiness.py",
                    "app/backend/tests/test_quota_delivery_decision.py",
                    "app/backend/tests/test_legal_document_export_readiness.py",
                    "app/backend/tests/test_legal_document_template_matrix.py",
                    "app/backend/tests/test_document_delivery_package_manifest.py",
                    "app/backend/tests/test_document_version_diff_checklist.py",
                    "app/backend/tests/test_lawyer_review_workflow_policy.py",
                    "app/backend/tests/test_client_delivery_transparency_policy.py",
                    "app/backend/tests/test_billing_usage_router.py",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/lib/billingUsageApi.ts",
                    "docs/LEGAL_DOCUMENT_EXPORT_READINESS.md",
                    "docs/LEGAL_DOCUMENT_TEMPLATE_MATRIX.md",
                    "docs/DOCUMENT_DELIVERY_PACKAGE_MANIFEST.md",
                    "docs/DOCUMENT_VERSION_DIFF_CHECKLIST.md",
                    "docs/LAWYER_REVIEW_WORKFLOW_POLICY.md",
                    "docs/CLIENT_DELIVERY_TRANSPARENCY_POLICY.md",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                next_actions=(
                    "Wire the document template matrix into concrete generation and export flows.",
                    "Wire export-readiness gates into DOCX/PDF export actions.",
                    "Bind delivery package manifest checks to final package release actions.",
                    "Attach version diff metadata to client-visible delivery packages.",
                    "Wire case export readiness checks into the live report export buttons.",
                ),
            ),
            ProductFeatureGap(
                id="contract-review",
                title="Contract review workflow",
                module="contract_review",
                current_state="Deep review, report quality checks, clause extraction schema, tiny legal document fixtures, and a metadata-only benchmark coverage matrix exist, but raw contract extraction, fallback language, broader real-world document coverage, and negotiation workflow are incomplete.",
                target_capability="Clause-level review with risk grading, proposed edits, negotiation notes, and source-backed explanations.",
                user_segments=("lawyer", "legal_ops", "individual"),
                impact=9,
                urgency=9,
                effort=7,
                confidence=8,
                dependencies=("ocr-import", "legal-knowledge-rag", "model-cost-ops"),
                evidence_paths=(
                    "app/backend/services/deep_review.py",
                    "app/backend/services/report_quality_gate.py",
                    "app/backend/services/contract_clause_extraction_schema.py",
                    "app/backend/services/legal_document_benchmark_fixtures.py",
                    "app/backend/services/legal_document_benchmark_coverage.py",
                    "app/backend/services/small_legal_document_corpus_expansion.py",
                    "app/backend/tests/test_contract_clause_extraction_schema.py",
                    "app/backend/tests/test_legal_document_benchmark_fixtures.py",
                    "app/backend/tests/test_legal_document_benchmark_coverage.py",
                    "app/backend/tests/test_small_legal_document_corpus_expansion.py",
                    "docs/CONTRACT_CLAUSE_EXTRACTION_SCHEMA.md",
                    "docs/LEGAL_DOCUMENT_BENCHMARK_FIXTURES.md",
                    "docs/LEGAL_DOCUMENT_BENCHMARK_COVERAGE.md",
                    "docs/SMALL_LEGAL_DOCUMENT_CORPUS_EXPANSION.md",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                next_actions=(
                    "Bind raw contract parsing into the clause extraction schema.",
                    "Add contract-specific quality checks for missing clauses and unsupported recommendations.",
                    "Use the benchmark coverage matrix to prioritize missing legal document types before broad coverage claims.",
                    "Use the expanded small legal corpus to cover common commercial and civil scenarios.",
                ),
            ),
            ProductFeatureGap(
                id="evidence-management",
                title="Evidence management",
                module="evidence",
                current_state="Evidence services and a metadata-only evidence bundle integrity checker exist, covering duplicates, missing sources, missing proof purposes, and date/amount/checksum gaps; exhibit organization, chain-of-custody notes, and case linking still need a fuller workflow.",
                target_capability="Manage uploads, exhibits, source excerpts, relevance, authenticity notes, and case-level evidence bundles.",
                user_segments=("lawyer", "legal_ops"),
                impact=9,
                urgency=8,
                effort=6,
                confidence=8,
                dependencies=("case-workbench", "ocr-import", "safety-compliance"),
                evidence_paths=(
                    "app/backend/services/evidences.py",
                    "app/backend/services/evidence_audit.py",
                    "app/backend/services/case_materials.py",
                    "app/backend/services/evidence_exhibit_package_policy.py",
                    "app/backend/services/evidence_bundle_integrity.py",
                    "app/backend/tests/test_evidence_exhibit_package_policy.py",
                    "app/backend/tests/test_evidence_bundle_integrity.py",
                    "docs/EVIDENCE_EXHIBIT_PACKAGE_POLICY.md",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                next_actions=(
                    "Wire the evidence exhibit package policy into evidence catalog export.",
                    "Wire duplicate and missing-source bundle checks into evidence catalog export.",
                    "Expose relevance and authenticity flags in backend payloads.",
                ),
            ),
            ProductFeatureGap(
                id="ocr-import",
                title="OCR and import pipeline",
                module="document_intake",
                current_state="Extraction quality checks exist, but scanned-file OCR routing, import retry state, and structured import mapping need more coverage.",
                target_capability="Robust import for PDFs, images, Word files, and structured forms with visible extraction confidence and retry handling.",
                user_segments=("lawyer", "legal_ops", "individual"),
                impact=9,
                urgency=8,
                effort=6,
                confidence=8,
                dependencies=("safety-compliance", "model-cost-ops"),
                evidence_paths=(
                    "app/backend/services/document_extraction.py",
                    "app/backend/services/extraction_quality.py",
                    "app/backend/services/document_preflight.py",
                    "app/backend/services/ocr_import_readiness_policy.py",
                    "app/backend/tests/test_ocr_import_readiness_policy.py",
                    "docs/OCR_IMPORT_READINESS_POLICY.md",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                next_actions=(
                    "Wire the OCR import readiness policy into upload preflight and retry flows.",
                    "Track import parser, page count, low-text pages, and retry eligibility.",
                    "Create small scanned-document fixtures for local testing.",
                ),
            ),
            ProductFeatureGap(
                id="permissions-team",
                title="Permissions and team workspace",
                module="collaboration",
                current_state="Authentication, entitlements, case team policy, and role permission matrix evidence exist, but database-backed matter memberships, sharing enforcement, and reviewer assignment are incomplete.",
                target_capability="Team workspace with owner, lawyer, reviewer, assistant, and client roles scoped to cases and documents.",
                user_segments=("lawyer", "legal_ops", "team_admin"),
                impact=8,
                urgency=8,
                effort=8,
                confidence=7,
                dependencies=("case-workbench", "billing-entitlements", "safety-compliance"),
                evidence_paths=(
                    "app/backend/services/auth.py",
                    "app/backend/services/entitlements.py",
                    "app/backend/services/audit_logs.py",
                    "app/backend/services/case_role_permission_matrix.py",
                    "app/backend/services/case_team_access_policy.py",
                    "app/backend/tests/test_case_role_permission_matrix.py",
                    "app/backend/tests/test_case_team_access_policy.py",
                    "docs/CASE_ROLE_PERMISSION_MATRIX.md",
                    "docs/CASE_TEAM_ACCESS_POLICY.md",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                next_actions=(
                    "Persist case-scoped roles and enforce the permission matrix in membership queries.",
                    "Add reviewer assignment and access audit payloads.",
                    "Keep role changes visible in audit logs.",
                ),
            ),
            ProductFeatureGap(
                id="billing-entitlements",
                title="Billing and entitlement control",
                module="billing",
                current_state="Entitlement checks, local quota policy, privacy-safe quota persistence and migration plans, quota counter repository, entitlement/quota binding facade, authenticated billing usage routes, report preflight, generated_documents CRUD quota guard, case generation quota guard, deep-review first-principles document-generation quota guard, typed frontend API helper, a global workspace quota badge, a best-effort document-generation quota consumption attempt, and local-only payment/invoice/plan-change reconciliation policy evidence exist, but product packaging, real payment provider settlement verification, webhook signature handling, and reviewed invoice/plan-change workflows are incomplete.",
                target_capability="Plans, quotas, invoices, review credits, and model-cost controls that protect low-cost usage.",
                user_segments=("individual", "legal_ops", "team_admin"),
                impact=8,
                urgency=7,
                effort=7,
                confidence=7,
                dependencies=("model-cost-ops", "permissions-team"),
                evidence_paths=(
                    "app/backend/services/entitlements.py",
                    "app/backend/services/billing_entitlement_gap.py",
                    "app/backend/services/billing_usage_quota_policy.py",
                    "app/backend/services/billing_quota_persistence_plan.py",
                    "app/backend/services/billing_quota_migration_plan.py",
                    "app/backend/services/billing_quota_repository.py",
                    "app/backend/services/billing_entitlement_quota_binding.py",
                    "app/backend/services/billing_payment_reconciliation.py",
                    "app/backend/routers/billing_usage.py",
                    "app/backend/routers/generated_documents.py",
                    "app/backend/routers/case_intelligence.py",
                    "app/backend/routers/deep_review.py",
                    "app/backend/services/deep_review_document_quota.py",
                    "app/backend/services/model_budget.py",
                    "app/backend/tests/test_billing_entitlement_gap.py",
                    "app/backend/tests/test_billing_usage_quota_policy.py",
                    "app/backend/tests/test_billing_quota_persistence_plan.py",
                    "app/backend/tests/test_billing_quota_migration_plan.py",
                    "app/backend/tests/test_billing_quota_repository.py",
                    "app/backend/tests/test_billing_entitlement_quota_binding.py",
                    "app/backend/tests/test_billing_payment_reconciliation.py",
                    "app/backend/tests/test_billing_usage_router.py",
                    "app/backend/tests/test_generated_documents_quota.py",
                    "app/backend/tests/test_case_generation_quota.py",
                    "app/backend/tests/test_deep_review_document_quota.py",
                    "app/backend/tests/test_runtime_router_discovery.py",
                    "app/frontend/src/components/billing/BillingUsageBadge.tsx",
                    "app/frontend/src/components/Layout.tsx",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/lib/billingUsageApi.ts",
                    "docs/BILLING_ENTITLEMENT_GAP.md",
                    "docs/BILLING_USAGE_QUOTA_POLICY.md",
                    "docs/BILLING_QUOTA_PERSISTENCE_PLAN.md",
                    "docs/BILLING_QUOTA_MIGRATION_PLAN.md",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                next_actions=(
                    "Bind quota usage summaries into account plan review and export decisions.",
                    "Add real payment provider webhook signature verification without storing payment secrets.",
                    "Expose reviewed invoice and plan-change states without claiming settlement until provider evidence is verified.",
                ),
            ),
            ProductFeatureGap(
                id="feedback-loop",
                title="Feedback loop",
                module="feedback",
                current_state="Feedback triage, roadmap alignment, lifecycle policy, deterministic repeated issue clustering, and a metadata-only adoption research bridge exist, connecting public research/adoption signals to user need IDs, product gap IDs, survey intake questions, and release validation actions. In-product capture and persistent closure tracking still need implementation.",
                target_capability="Close the loop from user report to triage, roadmap gap, release gate, fix evidence, and customer-visible resolution.",
                user_segments=("maintainer", "support_ops", "lawyer"),
                impact=8,
                urgency=8,
                effort=5,
                confidence=8,
                dependencies=("case-workbench", "model-cost-ops"),
                evidence_paths=(
                    "app/backend/services/feedback_tickets.py",
                    "app/backend/services/feedback_triage.py",
                    "app/backend/services/feedback_roadmap_alignment.py",
                    "app/backend/services/feedback_lifecycle_policy.py",
                    "app/backend/services/feedback_issue_cluster.py",
                    "app/backend/services/legal_adoption_research_bridge.py",
                    "app/backend/tests/test_feedback_lifecycle_policy.py",
                    "app/backend/tests/test_feedback_issue_cluster.py",
                    "app/backend/tests/test_legal_adoption_research_bridge.py",
                    "docs/FEEDBACK_LIFECYCLE_POLICY.md",
                    "docs/LEGAL_ADOPTION_RESEARCH_BRIDGE.md",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                next_actions=(
                    "Bind lifecycle policy to persisted feedback tickets.",
                    "Persist repeated issue clusters without storing raw legal matter text.",
                    "Wire structured adoption-bridge survey questions into in-product feedback capture.",
                    "Expose customer-visible resolution state in the maintenance UI.",
                ),
            ),
            ProductFeatureGap(
                id="model-cost-ops",
                title="Model cost operations",
                module="model_ops",
                current_state="Model routing, budgets, compatibility checks, Gemini/NewAPI cheap-first policy, task-level model selector audits, deterministic selector replay evidence, metadata-only cheap-first calibration in AIHub and ModelOps, a sanitized ModelOps calibration review form, public benchmark research mappings in calibration rows, privacy-safe route telemetry repository aggregates, persisted route telemetry operations summary checks, route telemetry triage actions, operator-reviewed route telemetry remediation plans, deep-review document quota blocking before AI drafting, a laptop-safe legal document benchmark suite, a LegalBench/LexGLUE/COLIEE research registry, a maintenance UI for the metadata-only registry, and a public adoption/research bridge UI evidence exist, but live cost dashboards, result archives, and cheap-first guardrails still need product hardening.",
                target_capability="Cheap-first legal AI operations with route telemetry, budget limits, fallback policy, and benchmark-backed model choices.",
                user_segments=("maintainer", "legal_ops", "team_admin"),
                impact=9,
                urgency=9,
                effort=5,
                confidence=8,
                dependencies=("contract-review", "legal-knowledge-rag", "billing-entitlements"),
                evidence_paths=(
                    "app/backend/services/model_budget.py",
                    "app/backend/services/model_runtime_router.py",
                    "app/backend/services/model_route_telemetry.py",
                    "app/backend/services/model_default_recommendation_snapshot.py",
                    "app/backend/services/legal_adoption_research_bridge.py",
                    "app/backend/services/gemini_newapi_cheap_first_policy.py",
                    "app/backend/services/gemini_newapi_model_selector.py",
                    "app/backend/services/gemini_newapi_selector_replay.py",
                    "app/backend/services/gemini_newapi_cheap_first_calibration.py",
                    "app/backend/services/model_price_refresh_monitor.py",
                    "app/backend/services/model_cost_regression_snapshots.py",
                    "app/backend/services/route_telemetry_persistence_plan.py",
                    "app/backend/services/route_telemetry_repository.py",
                    "app/backend/services/route_telemetry_ops_summary.py",
                    "app/backend/services/route_telemetry_triage_queue.py",
                    "app/backend/services/route_telemetry_remediation_plan.py",
                    "app/backend/services/legal_document_benchmark_suite.py",
                    "app/backend/services/legal_benchmark_research_registry.py",
                    "app/backend/services/deep_review_document_quota.py",
                    "app/backend/tests/test_model_default_recommendation_snapshot.py",
                    "app/backend/tests/test_legal_adoption_research_bridge.py",
                    "app/backend/tests/test_gemini_newapi_cheap_first_policy.py",
                    "app/backend/tests/test_gemini_newapi_model_selector.py",
                    "app/backend/tests/test_gemini_newapi_selector_replay.py",
                    "app/backend/tests/test_gemini_newapi_cheap_first_calibration.py",
                    "app/frontend/scripts/ui-regression.mjs",
                    "app/frontend/src/pages/ModelOpsPage.tsx",
                    "app/frontend/src/lib/modelOpsApi.ts",
                    "app/backend/tests/test_model_price_refresh_monitor.py",
                    "app/backend/tests/test_model_cost_regression_snapshots.py",
                    "app/backend/tests/test_route_telemetry_persistence_plan.py",
                    "app/backend/tests/test_route_telemetry_repository.py",
                    "app/backend/tests/test_route_telemetry_ops_summary.py",
                    "app/backend/tests/test_route_telemetry_triage_queue.py",
                    "app/backend/tests/test_route_telemetry_remediation_plan.py",
                    "app/backend/tests/test_legal_document_benchmark_suite.py",
                    "app/backend/tests/test_legal_benchmark_research_registry.py",
                    "app/backend/tests/test_deep_review_document_quota.py",
                    "app/frontend/src/pages/MaintenanceEvidencePage.tsx",
                    "app/frontend/src/lib/maintenanceApi.ts",
                    "docs/MODEL_DEFAULT_RECOMMENDATION_SNAPSHOT.md",
                    "docs/LEGAL_ADOPTION_RESEARCH_BRIDGE.md",
                    "docs/GEMINI_NEWAPI_CHEAP_FIRST_POLICY.md",
                    "docs/GEMINI_NEWAPI_MODEL_SELECTOR.md",
                    "docs/GEMINI_NEWAPI_SELECTOR_REPLAY.md",
                    "docs/GEMINI_NEWAPI_CHEAP_FIRST_CALIBRATION.md",
                    "docs/MODEL_PRICE_REFRESH_MONITOR.md",
                    "docs/MODEL_COST_REGRESSION_SNAPSHOTS.md",
                    "docs/ROUTE_TELEMETRY_PERSISTENCE_PLAN.md",
                    "docs/ROUTE_TELEMETRY_OPS_SUMMARY.md",
                    "docs/ROUTE_TELEMETRY_TRIAGE_QUEUE.md",
                    "docs/ROUTE_TELEMETRY_REMEDIATION_PLAN.md",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                next_actions=(
                    "Archive small benchmark results by model, cost band, and legal task.",
                    "Wire price refresh and cost regression snapshots into recurring maintenance review.",
                    "Use model selector audits to keep high-volume Gemini/NewAPI routes on cheap Flash-Lite defaults.",
                    "Replay selector scenarios before changing cheap-first Gemini/NewAPI defaults.",
                    "Use cheap-first calibration and public benchmark research mappings before promoting legal review routes beyond Flash-Lite precheck or balanced Flash.",
                    "Feed production route events into the privacy-safe telemetry repository and review the operations summary before release checks.",
                    "Review route telemetry triage actions before changing Gemini/NewAPI defaults.",
                    "Review remediation-plan env suggestions before changing Gemini/NewAPI defaults.",
                    "Keep Gemini-compatible cheap models first for eligible low-risk work.",
                ),
            ),
            ProductFeatureGap(
                id="legal-knowledge-rag",
                title="Legal knowledge base and RAG",
                module="legal_knowledge",
                current_state="Knowledge, RAG audits, failure fixtures, source-freshness policy, source ingestion metadata contracts, durable index plan, metadata-only index repository, indexed retrieval-plan binding, metadata-only legal RAG routes, typed frontend API helper, route discovery smoke, a case research metadata-only RAG panel with localStorage summary cache, Copy context, Clear cache, selected-source request metadata propagation into case AI prompts/generation plans/citation maps, metadata-level selected-source citation validation, a metadata-only maintenance self-check route, and deep-review selected-source report binding exist, but live report persistence/export integration remains incomplete.",
                target_capability="A jurisdiction-aware legal knowledge base with retrieval quality checks, citation freshness, and source provenance.",
                user_segments=("lawyer", "legal_ops", "maintainer"),
                impact=10,
                urgency=9,
                effort=9,
                confidence=8,
                dependencies=("safety-compliance", "model-cost-ops", "contract-review"),
                evidence_paths=(
                    "app/backend/services/legal_knowledge_audit.py",
                    "app/backend/services/legal_rag_evaluation.py",
                    "app/backend/services/legal_rag_failure_fixtures.py",
                    "app/backend/services/legal_source_ingestion_metadata.py",
                    "app/backend/services/legal_source_freshness_policy.py",
                    "app/backend/services/legal_source_durable_index_plan.py",
                    "app/backend/services/legal_source_index_repository.py",
                    "app/backend/services/legal_rag_index_binding.py",
                    "app/backend/services/legal_rag_request_metadata.py",
                    "app/backend/services/legal_rag_selected_source_validation.py",
                    "app/backend/services/deep_review_selected_source_binding.py",
                    "app/backend/routers/maintenance.py",
                    "app/backend/services/case_ai_workbench.py",
                    "app/backend/services/case_intelligence.py",
                    "app/backend/routers/legal_rag.py",
                    "app/backend/routers/case_intelligence.py",
                    "app/backend/services/citation_audit.py",
                    "app/backend/tests/test_legal_rag_failure_fixtures.py",
                    "app/backend/tests/test_legal_source_ingestion_metadata.py",
                    "app/backend/tests/test_legal_source_freshness_policy.py",
                    "app/backend/tests/test_legal_source_durable_index_plan.py",
                    "app/backend/tests/test_legal_source_index_repository.py",
                    "app/backend/tests/test_legal_rag_index_binding.py",
                    "app/backend/tests/test_legal_rag_router.py",
                    "app/backend/tests/test_legal_rag_request_metadata.py",
                    "app/backend/tests/test_legal_rag_selected_source_validation.py",
                    "app/backend/tests/test_deep_review_selected_source_binding.py",
                    "app/backend/tests/test_maintenance_legal_rag_selected_source_validation_route.py",
                    "app/backend/tests/test_runtime_router_discovery.py",
                    "app/frontend/src/components/cases/LegalRagResearchPanel.tsx",
                    "app/frontend/src/pages/CaseDetailPage.tsx",
                    "app/frontend/src/lib/legalRagApi.ts",
                    "docs/LEGAL_RAG_FAILURE_FIXTURES.md",
                    "docs/LEGAL_SOURCE_INGESTION_METADATA.md",
                    "docs/LEGAL_SOURCE_FRESHNESS_POLICY.md",
                    "docs/LEGAL_SOURCE_DURABLE_INDEX_PLAN.md",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                next_actions=(
                    "Wire selected-source binding into live deep-review persistence and export actions.",
                    "Use RAG failure fixtures to block stale, unsupported, and wrong-jurisdiction answers.",
                ),
            ),
            ProductFeatureGap(
                id="safety-compliance",
                title="Safety and compliance",
                module="safety",
                current_state="Privacy redaction, injection audit, audit logs, privacy retention rules, release-claim compliance checks, and admin audit policy evidence exist, but export control and product-level compliance ownership still need implementation.",
                target_capability="Auditable privacy, security, retention, and legal-output safety controls suitable for sensitive legal workflows.",
                user_segments=("lawyer", "legal_ops", "team_admin", "maintainer"),
                impact=10,
                urgency=10,
                effort=8,
                confidence=8,
                dependencies=("permissions-team", "ocr-import", "legal-knowledge-rag"),
                evidence_paths=(
                    "app/backend/services/privacy_redaction.py",
                    "app/backend/services/instruction_injection_audit.py",
                    "app/backend/services/audit_logs.py",
                    "app/backend/services/privacy_retention_rules.py",
                    "app/backend/services/release_claim_compliance.py",
                    "app/backend/services/admin_audit_policy.py",
                    "app/backend/tests/test_privacy_retention_rules.py",
                    "app/backend/tests/test_release_claim_compliance.py",
                    "app/backend/tests/test_admin_audit_policy.py",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                next_actions=(
                    "Wire retention and deletion rules into uploaded-material lifecycle jobs.",
                    "Wire release-claim compliance checks into public release and support-application workflows.",
                    "Persist admin audit decisions for sensitive actions.",
                ),
            ),
            ProductFeatureGap(
                id="continuous-maintenance-evidence",
                title="Continuous maintenance evidence",
                module="maintenance",
                current_state="The 100+ update ledger, heartbeat evidence export, continuous session evidence validator, metadata-only continuous session timeline, active-run monitor, continuous session review packet, git history cadence evidence, and validation event evidence normalizer exist, including elapsed-hour, current-gap, next-checkpoint, max-gap, commit-window, credential-scan, push, release-review, low-resource legal fixture, blocker, next-action, privacy-boundary, stable packet hash, reviewer questions, and 100+ update-count checks. The reviewer-facing product still lacks persisted real session records and a fully interactive timeline that joins commits, tests, pushes, credential scans, low-resource benchmark events, release reviews, and support-claim readiness.",
                target_capability="A reviewer-facing maintenance timeline that proves or blocks 24-hour claims with timestamped repository evidence.",
                user_segments=("maintainer", "support_ops"),
                impact=8,
                urgency=9,
                effort=5,
                confidence=8,
                dependencies=("feedback-loop", "model-cost-ops", "safety-compliance"),
                evidence_paths=(
                    "app/backend/services/continuous_update_ledger.py",
                    "app/backend/services/maintenance_heartbeat_evidence.py",
                    "app/backend/services/continuous_session_evidence.py",
                    "app/backend/services/continuous_session_timeline.py",
                    "app/backend/services/continuous_session_run_monitor.py",
                    "app/backend/services/continuous_session_review_packet.py",
                    "app/backend/services/git_history_evidence.py",
                    "app/backend/services/validation_event_evidence.py",
                    "app/backend/tests/test_continuous_update_ledger.py",
                    "app/backend/tests/test_maintenance_heartbeat_evidence.py",
                    "app/backend/tests/test_continuous_session_evidence.py",
                    "app/backend/tests/test_continuous_session_timeline.py",
                    "app/backend/tests/test_continuous_session_run_monitor.py",
                    "app/backend/tests/test_continuous_session_review_packet.py",
                    "app/backend/tests/test_git_history_evidence.py",
                    "app/backend/tests/test_validation_event_evidence.py",
                    "docs/CONTINUOUS_UPDATE_LEDGER.md",
                    "docs/MAINTENANCE_HEARTBEAT_EVIDENCE.md",
                    "docs/CONTINUOUS_SESSION_EVIDENCE.md",
                    "docs/CONTINUOUS_SESSION_TIMELINE.md",
                    "docs/CONTINUOUS_SESSION_RUN_MONITOR.md",
                    "docs/CONTINUOUS_SESSION_REVIEW_PACKET.md",
                    "docs/GIT_HISTORY_EVIDENCE.md",
                    "docs/VALIDATION_EVENT_EVIDENCE.md",
                    "docs/PRODUCT_FEATURE_GAP_RADAR.md",
                ),
                next_actions=(
                    "Persist reviewed session events without storing raw legal text or credentials.",
                    "Wire the timeline into the maintenance page as a combined 100+ update and 24-hour reviewer surface.",
                    "Use the active-run monitor to surface next checkpoint, current-gap, required-evidence, and blocker status while the 24-hour run is still collecting.",
                    "Use the review packet as the support-facing index only after timestamped events satisfy the timeline gate.",
                    "Use the validation event normalizer to join git cadence evidence with test, push, credential-scan, low-resource fixture, and release-review events.",
                    "Attach low-resource legal fixture checks to the session evidence report.",
                ),
            ),
        )

    def _delivery_phases(self) -> tuple[DeliveryPhase, ...]:
        return (
            DeliveryPhase(
                id="phase-1-core-legal-workflow",
                title="Core legal workflow",
                objective="Make the legal workbench useful before adding broad collaboration and monetization flows.",
                gap_ids=(
                    "case-workbench",
                    "document-generation",
                    "contract-review",
                    "evidence-management",
                    "ocr-import",
                ),
                exit_criteria=(
                    "A case can move from import to evidence review, contract review, and draft generation.",
                    "Every generated legal output has missing-fact, source-support, and review-required markers.",
                ),
            ),
            DeliveryPhase(
                id="phase-2-quality-and-ops",
                title="Quality, knowledge, and cost controls",
                objective="Harden legal accuracy and cheap-first model operations before higher-volume usage.",
                gap_ids=(
                    "legal-knowledge-rag",
                    "model-cost-ops",
                    "feedback-loop",
                    "safety-compliance",
                    "continuous-maintenance-evidence",
                ),
                exit_criteria=(
                    "Legal knowledge retrieval has jurisdiction, freshness, and citation checks.",
                    "Small benchmark archives show cost, quality, and fallback behavior for target legal tasks.",
                    "Feedback can be tied back to roadmap gaps and release gates.",
                ),
            ),
            DeliveryPhase(
                id="phase-3-commercial-workspace",
                title="Team and commercial readiness",
                objective="Add team, permission, and billing controls once the core workflow is auditable.",
                gap_ids=("permissions-team", "billing-entitlements"),
                exit_criteria=(
                    "Case access is role-scoped and auditable.",
                    "Plan limits, usage metering, and model-cost limits are deterministic and privacy-safe.",
                ),
            ),
        )


def priority_score(impact: int, urgency: int, effort: int, confidence: int) -> int:
    raw = impact * 5 + urgency * 4 + confidence * 3 - effort * 2
    return max(0, min(100, raw))


def priority_band(score: int) -> str:
    if score >= 90:
        return "critical"
    if score >= 75:
        return "high"
    if score >= 55:
        return "medium"
    return "low"
