const EXACT_TEXT: Record<string, string> = {
  '案件 AI': 'Case AI',
  '新对话': 'New chat',
  '案件列表': 'Cases',
  '报告下载': 'Download report',
  '委托人': 'Client',
  '委托人：': 'Client:',
  '对方': 'Opposing party',
  '对方：': 'Opposing party:',
  '管辖': 'Venue',
  '管辖：': 'Venue:',
  '代理方': 'Representing',
  '代理方：': 'Representing:',
  '期限': 'Deadline',
  '期限：': 'Deadline:',
  '证据：': 'Evidence:',
  '概览': 'Overview',
  '材料': 'Materials',
  '证据': 'Evidence',
  '事实': 'Facts',
  '时间线': 'Timeline',
  '法律研究': 'Legal research',
  '文书': 'Documents',
  '任务': 'Tasks',
  '团队': 'Team',
  '设置': 'Settings',
  '待办': 'To-do',
  '案件摘要': 'Case summary',
  '争议焦点': 'Disputed issues',
  '诉讼请求/目标': 'Claims / goals',
  '待补材料': 'Missing materials',
  '一键生成': 'One-click drafts',
  '案件分析报告': 'Case analysis report',
  '证据目录': 'Evidence catalog',
  '起诉状': 'Complaint',
  '答辩状': 'Defense',
  '律师函': 'Lawyer letter',
  '庭审提纲': 'Hearing outline',
  '补证清单': 'Evidence supplement list',
  '开始类案检索': 'Search similar cases',
  '上传/登记案件材料': 'Upload / register case material',
  '材料名称': 'Material name',
  '材料类型': 'Material type',
  '来源': 'Source',
  '页码/段落引用': 'Page / paragraph reference',
  '证明目的': 'Proof purpose',
  '解析文本/摘要': 'Extracted text / summary',
  '入库': 'Add to library',
  '补充案件事实': 'Add case fact',
  '发生日期': 'Event date',
  '涉及人物': 'People involved',
  '金额': 'Amount',
  '来源证据': 'Source evidence',
  '事实内容': 'Fact content',
  '矛盾提示/待核实说明': 'Conflict / verification note',
  '加入事实库': 'Add to facts',
  '新建任务/期限': 'New task / deadline',
  '任务名称': 'Task name',
  '负责人': 'Owner',
  '截止日期': 'Due date',
  '说明': 'Description',
  '创建任务': 'Create task',
  '新增当事人/团队对象': 'Add party / team object',
  '名称': 'Name',
  '身份/角色': 'Identity / role',
  '证件号/统一社会信用代码': 'ID / business registration number',
  '联系方式': 'Contact',
  '代理人': 'Representative',
  '保存': 'Save',
  '生成案件文书': 'Generate case document',
  '文书类型': 'Document type',
  '生成草稿': 'Generate draft',
  '复制': 'Copy',
  '下载': 'Download',
  '材料库': 'Material library',
  '上传材料': 'Upload material',
  '编号': 'No.',
  '类型': 'Type',
  '状态': 'Status',
  '操作': 'Action',
  '标记证据': 'Mark evidence',
  '导出证据目录': 'Export evidence catalog',
  '生成补强任务': 'Create reinforcement task',
  '补充事实': 'Add fact',
  '暂无争议焦点。': 'No disputed issues yet.',
  '暂无诉讼请求或非诉目标。': 'No claims or non-litigation goals yet.',
  '暂无待补材料清单。': 'No missing material list yet.',
  '暂无摘要，请在设置中补充案件背景。': 'No summary yet. Add case background in settings.',
  '合同纠纷': 'Contract dispute',
  '证据整理': 'Evidence review',
  '民事': 'Civil',
  '材料整理': 'Material review',
  '原告代理人': 'Counsel for plaintiff',
  '本地测试管理员': 'Local test admin',
  'A公司与B公司买卖合同纠纷': 'Company A v. Company B sale contract dispute',
  'A公司': 'Company A',
  'B公司': 'Company B',
  '星河科技与华北供应链买卖合同纠纷': 'Xinghe Technology v. North China Supply Chain sale contract dispute',
  '杭州星河科技有限公司': 'Hangzhou Xinghe Technology Co., Ltd.',
  '华北供应链管理有限公司': 'North China Supply Chain Management Co., Ltd.',
  '杭州市滨江区人民法院': "Hangzhou Binjiang District People's Court",
  '系统从 ZIP 案件包识别出 2 份材料，建议案件名称：A公司与B公司买卖合同纠纷。 聚类理由：用户选择单案件材料包；置信度：0.95。 检测到关键日期：2025年1月1日、2025年2月1日、2025年1月、2025年2月、2025年2月10日。 检测到金额线索：人民币120000元、120000元。 本概览由 AI 自动生成，案件分组、证据编号、证明目的和诉讼请求需律师确认。': 'The ZIP case bundle contains 2 materials and suggests the case name Company A v. Company B sale contract dispute. Clustering reason: single case material bundle selected by the user; confidence: 0.95. Key dates detected: January 1, 2025; February 1, 2025; January 2025; February 2025; February 10, 2025. Amount clues detected: RMB 120,000. This overview was generated by AI; case grouping, evidence numbers, proof purposes, and claims require lawyer confirmation.',
  '客户主张对方逾期交付核心设备并拒绝退还预付款，现需完成证据目录、事实时间线、律师函和起诉状草稿。': 'The client alleges delayed delivery of core equipment and refusal to return the prepayment. The next work products are an evidence catalog, fact timeline, lawyer letter, and complaint draft.',
  '合同是否有效成立': 'Whether the contract was validly formed',
  '交付迟延是否构成根本违约': 'Whether delayed delivery constitutes a material breach',
  '预付款返还、违约金及损失是否有合同与证据支持。': 'Whether the contract and evidence support refund of prepayment, liquidated damages, and losses.',
  '解除合同': 'Terminate the contract',
  '返还预付款128万元': 'Return RMB 1.28 million prepayment',
  '支付违约金及资金占用损失': 'Pay liquidated damages and capital occupation losses',
  '承担律师费、保全费和诉讼费。': 'Bear attorney fees, preservation fees, and court costs.',
  '对方工商信息、付款流水原件、催告函EMS回执、设备验收记录、实际损失测算依据。': 'Counterparty registration records, original payment flows, EMS receipt for demand letter, equipment acceptance records, and actual loss calculation basis.',
  '高': 'High',
  '中': 'Medium',
  '低': 'Low',
  '风险': ' risk',
  '有': '',
  '项事实缺少证据来源，生成正式文书时会标注“待核实”。': 'fact(s) lack evidence sources; formal drafts will mark them as "to be verified".',
};

const PLACEHOLDERS: Record<string, string> = {
  '询问证据链、事实缺口、诉讼策略或文书草稿...': 'Ask about evidence chains, factual gaps, litigation strategy, or draft documents...',
  '例：银行转账记录': 'Example: bank transfer record',
  '例：第1页 / 第15行': 'Example: page 1 / line 15',
  '说明该材料证明什么事实': 'Describe which fact this material proves',
  '可粘贴 OCR/转写/材料摘要，后续将用于事实提取': 'Paste OCR, transcript, or material summary for later fact extraction',
};

type Replacement = string | ((substring: string, ...args: string[]) => string);

const INLINE_REPLACEMENTS: Array<[RegExp, Replacement]> = [
  [/^系统从\s*ZIP[\s\S]*A公司与B公司买卖合同纠纷[\s\S]*$/, 'The ZIP case bundle contains 2 materials and suggests the case name Company A v. Company B sale contract dispute. Clustering reason: single case material bundle selected by the user; confidence: 0.95. Key dates detected: January 1, 2025; February 1, 2025; January 2025; February 2025; February 10, 2025. Amount clues detected: RMB 120,000. This overview was generated by AI; case grouping, evidence numbers, proof purposes, and claims require lawyer confirmation.'],
  [/^对话\s*(\d+)$/, 'Chat $1'],
  [/^([高中低])风险$/, (_, level: string) => ({ 高: 'High risk', 中: 'Medium risk', 低: 'Low risk' })[level] || 'Medium risk'],
  [/^(\d+)份$/, '$1 items'],
  [/^有\s*(\d+)\s*项事实缺少证据来源，生成正式文书时会标注“待核实”。$/, '$1 fact(s) lack evidence sources; formal drafts will mark them as "to be verified".'],
  [/^CASE-(\d+)\s*\|\s*合同纠纷\s*\|\s*证据整理$/, 'CASE-$1 | Contract dispute | Evidence review'],
];

function translateText(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return value;
  if (EXACT_TEXT[trimmed]) return value.replace(trimmed, EXACT_TEXT[trimmed]);
  for (const [pattern, replacement] of INLINE_REPLACEMENTS) {
    if (pattern.test(trimmed)) {
      const translated =
        typeof replacement === 'function'
          ? trimmed.replace(pattern, replacement)
          : trimmed.replace(pattern, replacement);
      return value.replace(trimmed, translated);
    }
  }
  return value;
}

function walkTextNodes(root: Node) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      if (!node.nodeValue?.trim()) return NodeFilter.FILTER_REJECT;
      const parent = node.parentElement;
      if (!parent) return NodeFilter.FILTER_REJECT;
      if (['SCRIPT', 'STYLE', 'TEXTAREA', 'INPUT'].includes(parent.tagName)) return NodeFilter.FILTER_REJECT;
      return NodeFilter.FILTER_ACCEPT;
    },
  });

  const nodes: Text[] = [];
  while (walker.nextNode()) nodes.push(walker.currentNode as Text);
  nodes.forEach((node) => {
    const next = translateText(node.nodeValue || '');
    if (next !== node.nodeValue) node.nodeValue = next;
  });
}

function translateAttributes(root: ParentNode) {
  root.querySelectorAll<HTMLElement>('[placeholder], [title], [aria-label]').forEach((element) => {
    for (const attr of ['placeholder', 'title', 'aria-label']) {
      const value = element.getAttribute(attr);
      if (!value) continue;
      element.setAttribute(attr, PLACEHOLDERS[value] || translateText(value));
    }
  });
}

export function normalizeEnglishStaticText() {
  if (typeof document === 'undefined') return () => {};

  const normalize = (root: ParentNode = document.body) => {
    walkTextNodes(root);
    translateAttributes(root);
  };

  normalize();
  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === 'characterData') {
        const text = mutation.target as Text;
        const next = translateText(text.nodeValue || '');
        if (next !== text.nodeValue) text.nodeValue = next;
        continue;
      }
      mutation.addedNodes.forEach((node) => {
        if (node.nodeType === Node.TEXT_NODE) {
          const text = node as Text;
          const next = translateText(text.nodeValue || '');
          if (next !== text.nodeValue) text.nodeValue = next;
        } else if (node instanceof HTMLElement) {
          normalize(node);
        }
      });
    }
  });
  observer.observe(document.body, { childList: true, characterData: true, subtree: true });

  return () => observer.disconnect();
}
